"19478" "英特尔新志强E5系列发布 加强云计算支撑" "资讯" "c(\"服务器\", \"数据中心\", \"云计算\", \"英特尔\", \"e5\")" NA "E" "E5"
"19479" "英特尔10G Romley服务器推动以太网交换机增长" "资讯" "c(\"Romley服务器\", \"E5\", \"Xeon\", \"以太网交换机\", \"Intel\")" NA "E" "E5"
"19480" "Sandy Bridge服务器版Xeon E5再添新丁" "资讯" "c(\"Sandy\", \"Bridge\", \"服务器\", \"Xeon\", \"E5\")" NA "E" "E5"
"19481" "1000美元打不住 单路至强E5售价确定" "资讯" "c(\"服务器\", \"至强\", \"英特尔\", \"e5\", \"E5\")" NA "E" "E5"
"19482" "英特尔发布E5服务器芯片 可用于云计算环境" "资讯" "c(\"数据中心\", \"服务器\", \"云计算\", \"e5\", \"英特尔\")" NA "E" "E5"
"19483" "IDF2011:Xeon E5服务器2012年初面世" "资讯" "c(\"英特尔\", \"服务器\", \"产品\", \"数据中心\", \"e5\")" NA "E" "E5"
"19484" "新的沙盒逃逸技术" "极客头条" "c(\"沙盒技术\", \"沙盒逃逸\", \"恶意软件\", \"绿盟科技\", \"e5\")" "gnaw0725" "E" "恶意软件"
"19485" "警报：XcodeGhost已扩散至第三方框架" "资讯" "c(\"安全\", \"XcodeGhost\", \"Xcode\", \"框架\", \"移动安全\")" NA "E" "恶意软件"
"19486" "恶意代码清除实战" "极客头条" "c(\"恶意代码\", \"恶意软件\", \"网站安全\", \"网站运维\", \"移动安全\")" "gnaw0725" "E" "恶意软件"
"19487" "安全专家：每天发现4900种安卓恶意软件" "资讯" "c(\"安卓病毒\", \"恶意软件\", \"网站安全\", \"网站运维\", \"移动安全\")" NA "E" "恶意软件"
"19488" "360安全卫士for Linux正式发布，引社区热议" "资讯" "c(\"360安全卫士\", \"Linux\", \"恶意软件\", \"网站运维\", \"移动安全\")" NA "E" "恶意软件"
"19489" "2014年最危险的五大软件漏洞" "资讯" "c(\"互联网\", \"安全漏洞\", \"恶意软件\", \"计算机\", \"OpenSSL\")" NA "E" "恶意软件"
"19490" "2015年Android五大挑战" "资讯" "c(\"Android\", \"iOS\", \"IBM软件\", \"开发者\", \"恶意软件\")" NA "E" "恶意软件"
"19491" "俄罗斯恶意软件SoakSoak已感染10万多个Wordpress网站" "资讯" "c(\"恶意软件\", \"病毒\", \"Google\", \"软件\", \"漏洞\")" NA "E" "恶意软件"
"19492" "A3：一个可以自动修复漏洞的软件" "资讯" "c(\"Web服务器\", \"恶意软件\", \"云计算平台\", \"操作系统\", \"服务器\")" NA "E" "恶意软件"
"19493" "iOS设备出现新恶意软件WireLurker 未越狱也受影响" "资讯" "c(\"恶意软件\", \"iPhone\", \"Mac\", \"iOS\", \"iPad\")" NA "E" "恶意软件"
"19494" "图说计算机病毒史" "资讯" "c(\"计算机病毒\", \"电子邮件\", \"恶意软件\", \"蠕虫\", \"iPad\")" NA "E" "恶意软件"
"19495" "研究人员：Pileup漏洞，让逾十亿Android设备存潜在危险" "资讯" "c(\"Android\", \"恶意软件\", \"安全漏洞\", \"Pileup\", \"iPad\")" NA "E" "恶意软件"
"19496" "2013年所有手机恶意软件中Android平台占97％" "资讯" "c(\"Android\", \"Google\", \"安全\", \"恶意软件\", \"手机\")" NA "E" "恶意软件"
"19497" "盘点黑客攻击途径：最常用的7个策略及简单的防护方法" "资讯" "c(\"黑客攻击\", \"数据安全\", \"Web开发\", \"恶意软件\", \"手机\")" NA "E" "恶意软件"
"19498" "“肮脏的”IT工作排行榜" "资讯" "c(\"IT\", \"编程语言\", \"Web\", \"恶意软件\", \"网络安全\")" NA "E" "恶意软件"
"19499" "隐私之战：金山手机毒霸宣布开放安全检测平台" "资讯" "c(\"金山\", \"安全\", \"智能手机\", \"金山毒霸\", \"Android\")" NA "E" "恶意软件"
"19500" "谷歌：受感染的合法网站远比恶意网站危险性大" "资讯" "c(\"Google\", \"安全\", \"恶意软件\", \"网络\", \"Android\")" NA "E" "恶意软件"
"19501" "卡巴斯基发现新型Android恶意软件 可入侵Windows" "资讯" "c(\"android\", \"windows\", \"google\", \"恶意软件\", \"安全\")" NA "E" "恶意软件"
"19502" "新型恶意软件瞄准Java服务器" "资讯" "c(\"恶意软件\", \"Java\", \"安全\", \"服务器\", \"安全\")" NA "E" "恶意软件"
"19503" "Android木马病毒：伪装成Google Play图标进行DDoS攻击" "资讯" "c(\"木马\", \"病毒\", \"安全\", \"GooglePlay\", \"Android\")" NA "E" "恶意软件"
"19504" "50万台感染！中国应用商店现隐形短信支付病毒" "资讯" "c(\"移动\", \"安全\", \"Android\", \"恶意软件\", \"Trojan!SMSZo\")" NA "E" "恶意软件"
"19505" "Java恶意软件出现新变种 攻击手法略有不同" "资讯" "c(\"恶意软件\", \"Java\", \"前端开发\", \"Web\", \"操作系统\")" NA "E" "恶意软件"
"19506" "谷歌官方应用市场惊现大量恶意软件" "资讯" "c(\"恶意软件\", \"Play\", \"Google\", \"Web\", \"操作系统\")" NA "E" "恶意软件"
"19507" "安全公司：Android恶意软件将越来越流行" "资讯" "c(\"Android\", \"恶意软件\", \"Google\", \"Web\", \"操作系统\")" NA "E" "恶意软件"
"19508" "工信部挥剑移动终端预置恶意软件" "资讯" "c(\"互联网\", \"智能终端\", \"终端\", \"恶意软件\", \"移动终端\")" NA "E" "恶意软件"
"19509" "Juniper：Android平台恶意软件缠身 移动平台威胁总体增长155%" "资讯" "c(\"移动平台\", \"恶意软件\", \"Android平台\", \"Juniper\", \"移动终端\")" NA "E" "恶意软件"
"19510" "赛门铁克称昨日公布的流氓软件判定有误" "资讯" "c(\"恶意软件\", \"赛门铁克\", \"Android平台\", \"Juniper\", \"移动终端\")" NA "E" "恶意软件"
"19511" "Android恶意软件数量飙升 影响百万用户" "资讯" "c(\"平台\", \"android\", \"恶意软件\", \"Juniper\", \"移动终端\")" NA "E" "恶意软件"
"19512" "2012年最大的移动安全隐患：恶意软件、欺骗性广告和数据窃取" "资讯" "c(\"数据窃取\", \"欺骗性广告\", \"恶意软件\", \"移动安全隐患\", \"移动终端\")" NA "E" "恶意软件"
"19513" "[简讯]MySQL.com网站被注入恶意软件" "资讯" "c(\"javascript\", \"浏览器\", \"mysq\", \"windows\", \"恶意软件\")" NA "E" "恶意软件"
"19514" "McAfee报告称Android成为恶意软件攻击的头号目标" "资讯" "c(\"数据库\", \"google\", \"android\", \"恶意软件\", \"杀毒软件\")" NA "E" "恶意软件"
"19515" "上半年全球50万Android用户受到恶意软件影响" "资讯" "c(\"恶意软件\", \"mobile\", \"security\", \"android用户\", \"android\")" NA "E" "恶意软件"
"19516" "苹果渐成恶意软件攻击目标 每秒检测到两个" "资讯" "c(\"活动\", \"平台\", \"android\", \"恶意软件\", \"苹果\")" NA "E" "恶意软件"
"19517" "谷歌推出恶意软件示警功能 搜索即可检测" "资讯" "c(\"微软\", \"windows\", \"恶意软件\", \"服务器\", \"谷歌\")" NA "E" "恶意软件"
"19518" "僵尸网络专家称：迁移到IPv6将产生更多的垃圾邮件和恶意软件" "资讯" "c(\"IPv6\", \"恶意软件\", \"垃圾邮件\", \"僵尸网络\", \"谷歌\")" NA "E" "恶意软件"
"19519" "黑帽和Defcon安全大会回顾：谷歌恶意链接最多" "资讯" "c(\"数据库\", \"浏览器\", \"黑帽安全大会\", \"漏洞\", \"恶意软件\")" NA "E" "恶意软件"
"19520" "为什么恶意软件开发者转向开放源代码" "资讯" "c(\"恶意软件\", \"开发者\", \"开放源代码\", \"赛门铁克\", \"恶意软件\")" NA "E" "恶意软件"
"19521" "中国反恶意软件联盟于昨天在天津成立" "资讯" "c(\"工作\", \"产品\", \"天津\", \"恶意软件\", \"中国\")" NA "E" "恶意软件"
"19522" "09年恶意软件放缓 2010年共享最危险" "资讯" "c(\"2009\", \"恶意软件\", \"2010\", \"共享\", \"中国\")" NA "E" "恶意软件"
"19523" "迈克菲报告：上季度恶意软件数量再创记录" "资讯" "c(\"report\", \"搜索引擎\", \"迈克菲\", \"恶意软件\", \"记录\")" NA "E" "恶意软件"
"19524" "谷歌董事长：一年后消费者才能用上Goolge Glass" "资讯" "c(\"Eric Schmidt\", \"Google\", \"Google Glass\", \"产品\", \"记录\")" NA "E" "Eric Schmidt"
"19525" "俄罗斯黑客窃取全球12亿用户用户名密码信息" "极客头条" "c(\"俄罗斯\", \"密码\", \"黑客\", \"产品\", \"记录\")" "linxiyu52" "E" "俄罗斯"
"19526" "为防止产品用于间谍活动 俄罗斯要求苹果、SAP提供源代码" "资讯" "c(\"源代码\", \"俄罗斯\", \"产品\", \"Apple\", \"SAP\")" NA "E" "俄罗斯"
"19527" "俄罗斯搜索霸主Yandex推出基于Docker的开源PaaS服务Cocaine" "极客头条" "c(\"Cocaine\", \"Yandex\", \"PaaS\", \"开源\", \"开源PaaS\")" "liujiangce" "E" "俄罗斯"
"19528" "聚焦全球移动市场：你所不知道的俄罗斯" "资讯" "c(\"俄罗斯\", \"聚焦全球移动市场\", \"移动市场\", \"应用\", \"移动广告\")" NA "E" "俄罗斯"
"19529" "《割绳子》开发者：俄罗斯双胞胎的奋斗史 曾应聘Rovio未果" "资讯" "c(\"ZeptoLab\", \"Semyon\", \"Efim\", \"割绳子\", \"割绳子：穿越时空\")" NA "E" "俄罗斯"
"19530" "俄罗斯门户网站Mail.ru推出微博服务Futubra" "资讯" "c(\"测试\", \"互联网\", \"twitter\", \"俄罗斯\", \"微博\")" NA "E" "俄罗斯"
"19531" "商业周刊：Facebook进军俄罗斯 象征精英阶层" "资讯" "c(\"生活\", \"语言\", \"网络\", \"俄罗斯\", \"facebook\")" NA "E" "俄罗斯"
"19532" "俄罗斯将进入千万亿次超算俱乐部" "资讯" "c(\"工作\", \"扩展\", \"数据中心\", \"超算\", \"俄罗斯\")" NA "E" "俄罗斯"
"19533" "微软拟在俄罗斯建立软件研发中心" "资讯" "c(\"产品\", \"微软\", \"俄罗斯\", \"软件研发中心\", \"俄罗斯\")" NA "E" "俄罗斯"
"19534" "俄追查世界垃圾邮件之王：个人年薪达200万美元" "资讯" "c(\"工作\", \"互联网\", \"垃圾邮件\", \"俄罗斯\", \"虚假广告\")" NA "E" "俄罗斯"
"19535" "俄罗斯“网虫”的虚拟生活" "资讯" "c(\"音乐\", \"工作\", \"搜索引擎\", \"生活\", \"俄罗斯\")" NA "E" "俄罗斯"
"19536" "谷歌董事长：一年后消费者才能用上Goolge Glass" "资讯" "c(\"Eric Schmidt\", \"Google\", \"Google Glass\", \"产品\", \"俄罗斯\")" NA "E" "Eric Schmidt"
"19537" "戴尔670亿美元收购EMC：戴尔舞剑，意在威睿" "资讯" "c(\"戴尔\", \"EMC\", \"云计算\", \"大数据\", \"数据库\")" NA "E" "EMC"
"19538" "传闻成真：戴尔收购了EMC公司" "资讯" "c(\"云计算\", \"VMware\", \"EMC\", \"混合云\", \"数据库\")" NA "E" "EMC"
"19539" "EMC/DSSD吞并Graphite Systems，旨在开启技术储备新道路" "极客头条" "c(\"存储\", \"emc\", \"EMC\", \"混合云\", \"数据库\")" "s110start" "E" "EMC"
"19540" "EMC推出开源版VIPR控制器Project CoprHD 并对多款产品升级" "资讯" "c(\"EMC\", \"产品\", \"开源\", \"数据中心\", \"解决方案\")" NA "E" "EMC"
"19541" "“用技术颠覆自己”，EMC 2015年在中国市场要做什么？" "资讯" "c(\"EMC\", \"叶成辉\", \"数据中心\", \"存储\", \"云计算\")" NA "E" "EMC"
"19542" "1万名IT业务决策者：混合云是未来发展大趋势" "资讯" "c(\"混合云\", \"云计算\", \"EMC\", \"大数据\", \"云计算\")" NA "E" "EMC"
"19543" "相比x86，Isilon支持Hadoop有五大优势" "资讯" "c(\"hadoop\", \"openstack swift\", \"isilon\", \"存储系统\", \"EMC\")" NA "E" "EMC"
"19544" "线内加密、可写快照、支持OpenStack的EMC XtremIO会是今年全闪存阵列的销量冠军？" "资讯" "c(\"openstack\", \"emc\", \"闪存\", \"内存数据库\", \"数据中心\")" NA "E" "EMC"
"19545" "EMC 2014存储布局及十大新技术要点" "资讯" "c(\"EMC\", \"VMAX\", \"XtremIO\", \"Isilon\", \"存储\")" NA "E" "EMC"
"19546" "OpenStack Swift 2.0发布，增加存储策略" "资讯" "c(\"云计算\", \"云存储\", \"OpenStack \", \"SwiftStack\", \"EMC\")" NA "E" "EMC"
"19547" "一周热点：准备迎接第一个量子计算软件公司吧！" "资讯" "c(\"云计算\", \"云热点\", \"Lockheed Martin\", \"PaaS\", \"R语言\")" NA "E" "EMC"
"19548" "盘点EMC World 2014三大看点" "资讯" "c(\"云计算\", \"云存储\", \"EMC\", \"DSSD\", \"SDS\")" NA "E" "EMC"
"19549" "EMC收购闪存初创公司DSSD，走出联合储存战略第一步" "资讯" "c(\"云计算\", \"EMC\", \"DSSN\", \"DSSD\", \"SDS\")" NA "E" "EMC"
"19550" "EMC：大数据时代中对于数据保护的重新定义" "资讯" "c(\"大数据\", \"数据中心\", \"数据安全\", \"数据备份\", \"EMC\")" NA "E" "EMC"
"19551" "集成GemFire，Hadoop生态圈的又一把火" "资讯" "c(\"大数据\", \"Hadoop\", \"Pivotal\", \"EMC\", \"VMware\")" NA "E" "EMC"
"19552" "投资超140亿美元，涨幅达30%，数据密集型应用将占领第三平台" "资讯" "c(\"大数据\", \"EMC\", \"存储\", \"EMC\", \"VMware\")" NA "E" "EMC"
"19553" "Pivotal聘用eBay前副总裁，继续发力云计算市场" "资讯" "c(\"云计算\", \"EMC\", \"VMware\", \"Pivotal\", \"Hugh E. Williams\")" NA "E" "EMC"
"19554" "技术团队新官上任之中层篇" "资讯" "c(\"《程序员》杂志\", \"2013年10月刊\", \"团队\", \"技术\", \"管理实践\")" NA "E" "EMC"
"19555" "VMware推出vCloud Suite及vSphere新版：可用性及性能双丰收" "资讯" "c(\"大数据\", \"EMC\", \"VMware\", \"数据中心\", \"SDN\")" NA "E" "EMC"
"19556" "多核优化软件MCx释放EMC VNX闪存潜能" "资讯" "c(\"数据仓库\", \"负载均衡\", \"存储\", \"闪存\", \"EMC\")" NA "E" "EMC"
"19557" "EMC全球营销CTO转投VMware" "资讯" "c(\"EMC\", \"CTO\", \"VMware\", \"Chuck Hollis\", \"人物\")" NA "E" "EMC"
"19558" "EMC:“随意架构”必将催生“备份即服务、归档即服务”" "资讯" "c(\"EMC\", \"备份\", \"存储\", \"云计算\", \"归档\")" NA "E" "EMC"
"19559" "RecoverPoint和VPLEX系统工程师谭强：高可用性环境的搭建" "资讯" "c(\"云计算\", \"云计算大会\", \"数据中心\", \"EMC\", \"EMC2013\")" NA "E" "EMC"
"19560" "EMC云计算事业部顾问崔大鹏：如何打造可信的大数据技术" "资讯" "c(\"云计算\", \"大数据\", \"EMC\", \"云计算大会\", \"崔大鹏\")" NA "E" "EMC"
"19561" "EMC解决方案集团大中华区总经理 卜晓军：实现应用程序转型" "资讯" "c(\"EMC\", \"卜晓军\", \"虚拟化\", \"云计算\", \"云计算大会\")" NA "E" "EMC"
"19562" "EMC合作伙伴销售经理杜术清：实现云的三种途径" "资讯" "c(\"EMC\", \"EMC2013\", \"云计算大会\", \"云计算\", \"数据中心\")" NA "E" "EMC"
"19563" "EMC企业存储产品部高级产品经理李君鹏：新一代 EMC将引领存储转型" "资讯" "c(\"EMC\", \"李君鹏\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC"
"19564" "EMC云和虚拟化数据中心咨询服务经理褚洪峰：新一代云应用程序可以增长700%" "资讯" "c(\"EMC\", \"褚洪峰\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC"
"19565" "EMC李岩：数据爆棚下，如何去保护数据的有效和安全" "资讯" "c(\"云计算\", \"云计算大会\", \"EMC\", \"EMC2013\", \"李岩\")" NA "E" "EMC"
"19566" "VMware全球研发高级副总裁范承工：移动/云时代的IT基础" "资讯" "c(\"VMware\", \"EMC\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC"
"19567" "EMC全球高级副总裁、大中华区总裁叶成辉：软件定义数据中心实现统一、开放的管理" "资讯" "c(\"EMC\", \"叶成辉\", \"云计算大会\", \"EMC2013\", \"云计算\")" NA "E" "EMC"
"19568" "EMC数据计算产品事业部刘琳：新一代PaaS平台前瞻" "资讯" "c(\"云计算\", \"大数据\", \"云计算大会\", \"EMC\", \"EMC2013\")" NA "E" "EMC"
"19569" "EMC在第五届中国云计算大会发布战略：EMC引领转型，软件定义存储" "资讯" "c(\"EMC2013\", \"EMC\", \"京东\", \"云计算\", \"云计算大会\")" NA "E" "EMC"
"19570" "EMC云计算咨询顾问耿煜：引领云计算变革" "资讯" "c(\"云计算大会\", \"云计算\", \"EMC\", \"数据中心\", \"虚拟化\")" NA "E" "EMC"
"19571" "EMC执行副总裁Sanjay Mirchandani：打造下一代云计算和大数据应用的平台" "资讯" "c(\"云计算\", \"云计算大会\", \"Sanjay Mirchandani\", \"EMC\", \"虚拟化\")" NA "E" "EMC"
"19572" "速度与金钱的碰撞：F1赛车将搭上大数据的东风" "资讯" "c(\"大数据\", \"EMC\", \"Sanjay Mirchandani\", \"EMC\", \"虚拟化\")" NA "E" "EMC"
"19573" "EMC World 2013：决胜第二次计算平台大迁移" "资讯" "c(\"2013年6月刊\", \"《程序员》\", \"EMC\", \"刘江\", \"虚拟化\")" NA "E" "EMC"
"19574" "Pivotal获通用电气1.05亿美元支持 或将改变大数据和物联网的游戏规则" "资讯" "c(\"VMware\", \"EMC\", \"Pivotal\", \"云先锋\", \"PaaS\")" NA "E" "EMC"
"19575" "EMC中国卓越研发集团总经理李映：私有云与公共云必将长期共存" "资讯" "c(\"《程序员》\", \"特别策划\", \"2013年4月刊\", \"EMC\", \"云计算\")" NA "E" "EMC"
"19576" "Pivotal宣布成立 EMC、VMware、通用电气铁三角组合正式起航" "资讯" "c(\"Pivotal\", \"Greenplum\", \"Cloud Foundry\", \"VMware\", \"EMC\")" NA "E" "EMC"
"19577" "EMC中国凭什么说营收5年再增5倍？" "资讯" "c(\"emc\", \"greenplum\", \"vmware\", \"云计算\", \"大数据\")" NA "E" "EMC"
"19578" "云计算一周热点回顾：Hadoop专家分享大数据技术工具与最佳实践" "资讯" "c(\"云热点\", \"大数据\", \"Hadoop\", \"亚马逊\", \"EMC\")" NA "E" "EMC"
"19579" "十一位EMC高管读2013技术趋势 你准备好了吗？" "资讯" "c(\"EMC\", \"大数据\", \"公有云\", \"高管\", \"私有云\")" NA "E" "EMC"
"19580" "VMware最快下周宣布分拆Cloud Foundry" "资讯" "c(\"VMware\", \"PaaS\", \"CloudFoundry\", \"EMC\", \"私有云\")" NA "E" "EMC"
"19581" "RSA身份认证决策树构建强身份认证体系" "资讯" "c(\"安全\", \"EMC\", \"RSA\", \"身份认证\", \"私有云\")" NA "E" "EMC"
"19582" "联想与EMC成立合资公司发力服务器与存储" "资讯" "c(\"解决方案\", \"联想\", \"EMC\", \"存储\", \"服务器\")" NA "E" "EMC"
"19583" "【早报】微软新推Outlook电邮 联想与EMC达成合作" "资讯" "c(\"EMC\", \"联想\", \"viddy\", \"微软\", \"邮箱\")" NA "E" "EMC"
"19584" "Nicira落入VMware之手 Cisco错失良机？" "资讯" "c(\"EMC\", \"VMware\", \"Cisco\", \"Nicira\", \"OpenStack\")" NA "E" "EMC"
"19585" "EMC/VMware业务大整合 CEO人事变动" "资讯" "c(\"EMC\", \"VMware\", \"Cloud\", \"Foundry\", \"虚拟化\")" NA "E" "EMC"
"19586" "Atos、EMC和VMware组建开放式云计算战略联盟" "资讯" "c(\"产品\", \"emc\", \"vmware\", \"云计算\", \"数据中心\")" NA "E" "EMC"
"19587" "甲骨文前高管蔡汉辉加盟EMC：任中国区总裁" "资讯" "c(\"工作\", \"中间件\", \"emc\", \"蔡汉辉\", \"甲骨文\")" NA "E" "EMC"
"19588" "Cloudera与NetApp建立合作关系 对抗EMC" "资讯" "c(\"cloudera\", \"netapp\", \"数据库\", \"数据中心\", \"emc\")" NA "E" "EMC"
"19589" "EMC收购数据库优化公司Zettapoint" "资讯" "c(\"EMC\", \"数据库优化\", \"分层存储\", \"Zettapoint\", \"emc\")" NA "E" "EMC"
"19590" "EMC在北卡州达勒姆新开设一家卓越中心" "资讯" "c(\"EMC\", \"卓越中心\", \"云计算\", \"服务型IT\", \"emc\")" NA "E" "EMC"
"19591" "EMC上演“变形金刚” 将阵列融入服务器" "资讯" "c(\"虚拟机\", \"应用服务器\", \"闪存\", \"阵列\", \"emc\")" NA "E" "EMC"
"19592" "EMC CTO：存储与服务器的界线变模糊" "资讯" "c(\"分布式存储\", \"emc\", \"存储\", \"商业智能\", \"服务器\")" NA "E" "EMC"
"19593" "EMC基辛格：大数据和云计算概念不同但有交集" "资讯" "c(\"虚拟化\", \"数据库\", \"分布式应用\", \"云计算\", \"emc\")" NA "E" "EMC"
"19594" "EMC Isilon否认放弃iSCSI支持" "资讯" "c(\"工作\", \"扩展\", \"microsoft\", \"iscsi\", \"emc\")" NA "E" "EMC"
"19595" "Gartner：云存储的带宽费用或超过存储成本" "资讯" "c(\"emc\", \"云计算\", \"企业应用\", \"存储\", \"云存储\")" NA "E" "EMC"
"19596" "EMC Hadoop策略：以MapR技术改善HDFS" "资讯" "c(\"EMC\", \"Hadoop\", \"MapR\", \"HDFS\", \"云存储\")" NA "E" "EMC"
"19597" "EMC与Citrix合作 VNX运行XenDesktop" "资讯" "c(\"EMC\", \"Citrix\", \"VNX\", \"XenDesktop\", \"云存储\")" NA "E" "EMC"
"19598" "EMC World 2011拥抱开源" "资讯" "c(\"EMC\", \"EMCWorld2011\", \"云计算\", \"大数据\", \"开源\")" NA "E" "EMC"
"19599" "EMC与Box提供iPhone和Android内容管理服务" "资讯" "c(\"Box\", \"EMC\", \"iPhone\", \"Android\", \"开源\")" NA "E" "EMC"
"19600" "戴尔：不排除收购EMC的可能" "资讯" "c(\"虚拟化\", \"服务器\", \"数据中心\", \"emc\", \"戴尔\")" NA "E" "EMC"
"19601" "“云计算”机会几何" "资讯" "c(\"数据中心\", \"联想\", \"阿里巴巴\", \"云计算\", \"emc\")" NA "E" "EMC"
"19602" "EMC称雄存储市场 进军云计算和海量数据" "资讯" "c(\"EMC\", \"存储\", \"云计算\", \"海量数据\", \"emc\")" NA "E" "EMC"
"19603" "EMC大中华总裁：在一万美元云计算市场拼华为" "资讯" "c(\"数据中心\", \"中国电信\", \"华为\", \"云计算\", \"emc\")" NA "E" "EMC"
"19604" "EMC全闪存VNX阵列打破SPEC NFS记录" "资讯" "c(\"扩展\", \"磁盘\", \"存储\", \"emc\", \"虚拟化\")" NA "E" "EMC"
"19605" "EMC战略解读：收购Isilon和Greenplum完善Bigdata解决方案" "资讯" "c(\"EMC\", \"大数据\", \"Greenplum\", \"Isilon\", \"虚拟化\")" NA "E" "EMC"
"19606" "EMC整合产品线推出VNX统一存储系列" "资讯" "c(\"存储系统\", \"存储\", \"产品\", \"vnx\", \"emc\")" NA "E" "EMC"
"19607" "EMC使用Atmos平台发布基于云计算自服务存储" "资讯" "c(\"存储系统\", \"平台\", \"云计算\", \"atmos\", \"emc\")" NA "E" "EMC"
"19608" "消息称苹果、EMC与甲骨文参与Novell专利交易" "资讯" "c(\"苹果、emc\", \"虚拟化\", \"emc\", \"novell\", \"甲骨文\")" NA "E" "EMC"
"19609" "存储软件市场2010年Q3排名：EMC保持第一 NetApp增速最快" "资讯" "c(\"ibm\", \"2010\", \"存储\", \"emc\", \"netapp\")" NA "E" "EMC"
"19610" "思科EMC联合推出集成云计算交付平台" "资讯" "c(\"平台\", \"云计算\", \"EMC\", \"思科\", \"netapp\")" NA "E" "EMC"
"19611" "暗战云存储：EMC与NetApp互为“替代”" "资讯" "c(\"netapp\", \"数据备份\", \"云存储\", \"存储\", \"emc\")" NA "E" "EMC"
"19612" "EMC发布针对“大数据”的Greenplum数据计算设备" "资讯" "c(\"greenplum\", \"数据计算\", \"服务器\", \"数据库\", \"emc\")" NA "E" "EMC"
"19613" "EMC叶成辉：私有云一定要选择不同厂商产品" "资讯" "c(\"服务器\", \"vforum\", \"greenplum\", \"emc\", \"vmware\")" NA "E" "EMC"
"19614" "对话EMC执行副总裁兼RSA总裁亚瑟·科维洛：安全无疆界" "资讯" "c(\"开放平台\", \"电子商务\", \"emc\", \"亚瑟·科维洛\", \"rsa\")" NA "E" "EMC"
"19615" "华尔街传言甲骨文将收购EMC 分析师称不大可能" "资讯" "c(\"虚拟化\", \"存储\", \"数据中心\", \"emc\", \"甲骨文\")" NA "E" "EMC"
"19616" "图文：2010年Hadoop大会EMC展台" "资讯" "c(\"hadoop\", \"互联网\", \"云计算\", \"2010\", \"emc\")" NA "E" "EMC"
"19617" "分析：谁将是甲骨文的下一个收购目标？" "资讯" "c(\"数据分析\", \"甲骨文\", \"salesforce\", \"数据仓库\", \"emc\")" NA "E" "EMC"
"19618" "分析称EMC或成收购对象 微软成潜在收购方" "资讯" "c(\"思科\", \"存储\", \"云计算\", \"emc\", \"微软\")" NA "E" "EMC"
"19619" "竞购大战：惠普、戴尔缘何疯抢3PAR？" "资讯" "c(\"产品\", \"emc\", \"xp\", \"数据中心\", \"云计算\")" NA "E" "EMC"
"19620" "EMC首席信息官：拥抱私有云，要坚定而大胆" "资讯" "c(\"产品\", \"服务器\", \"云计算\", \"emc\", \"存储系统\")" NA "E" "EMC"
"19621" "EMC推出Data  Domain  DD670重复数据删除存储系统" "资讯" "c(\"嵌入式\", \"服务器\", \"emc\", \"domain\", \"存储系统\")" NA "E" "EMC"
"19622" "EMC任命李映为中国卓越研发集团总经理" "资讯" "c(\"工作\", \"招聘\", \"emc\", \"domain\", \"存储系统\")" NA "E" "EMC"
"19623" "存储业巨头EMC对中国市场加大投资" "资讯" "c(\"数据中心\", \"emc\", \"存储\", \"domain\", \"存储系统\")" NA "E" "EMC"
"19624" "EMC并购GreanPlum 全面进军云计算" "资讯" "c(\"存储\", \"产品\", \"greenplum\", \"emc\", \"云计算\")" NA "E" "EMC"
"19625" "EMC计划收购Greenplum 反击甲骨文" "资讯" "c(\"工作\", \"emc\", \"greenplum\", \"数据仓库\", \"数据库\")" NA "E" "EMC"
"19626" "大丰收 云计算再次收获思杰、EMC大单" "资讯" "c(\"跨平台\", \"英特尔\", \"数据中心\", \"emc\", \"产品\")" NA "E" "EMC"
"19627" "EMC与Brocade合作 思科将被“背叛”？" "资讯" "c(\"服务器\", \"虚拟化\", \"数据中心\", \"emc\", \"思科\")" NA "E" "EMC"
"19628" "期待《第二届中国云计算大会》" "资讯" "c(\"ibm\", \"emc\", \"云计算\", \"emc\", \"思科\")" NA "E" "EMC"
"19629" "关于云安全  四大顶尖公司各抒己见" "资讯" "c(\"emc\", \"工作\", \"工具\", \"存储\", \"微软\")" NA "E" "EMC"
"19630" "基辛格：EMC成立虚拟存储部 产品更\"中国化\"" "资讯" "c(\"存储\", \"产品更\\"中国化\\"\", \"虚拟存储部\", \"产品\", \"emc\")" NA "E" "EMC"
"19631" "EMC发布VMware环境下Celerra新软件" "资讯" "c(\"EMC\", \"VMware\", \"Celerra\", \"虚拟化\", \"emc\")" NA "E" "EMC"
"19632" "VMware将收购母公司EMC数据中心管理软件" "资讯" "c(\"VMware\", \"EMC\", \"Ionix\", \"虚拟化\", \"emc\")" NA "E" "EMC"
"19633" "VMware将12日宣布收购雅虎开源电邮部门" "资讯" "c(\"emc\", \"产品\", \"工作\", \"虚拟化\", \"vmware\")" NA "E" "EMC"
"19634" "VMware或将收购雅虎开源电子邮件部门" "资讯" "c(\"emc\", \"产品\", \"工作\", \"虚拟化\", \"vmware\")" NA "E" "EMC"
"19635" "IOMEGA推出虚拟化新技术 电脑可“装”进硬盘" "资讯" "c(\"存储\", \"虚拟化\", \"iomega\", \"emc\", \"虚拟化克隆\")" NA "E" "EMC"
"19636" "EMC范承工：发力云计算 EMC全球双核研发架构呼之欲出" "资讯" "c(\"存储系统\", \"数据中心\", \"emc\", \"云计算\", \"云计算，双核研发架构，e\")" NA "E" "EMC"
"19637" "传思科与EMC展开云计算合作" "资讯" "c(\"思科\", \"emc\", \"数据中心\", \"互联网\", \"服务器\")" NA "E" "EMC"
"19638" "英特尔实施重组 副总裁Gelsinger跳槽至EMC" "资讯" "c(\"产品\", \"服务器\", \"emc\", \"英特尔\", \"gelsinger\")" NA "E" "EMC"
"19639" "IDC:Q2全球存储软件市场收入同比减少9.8%" "资讯" "c(\"ibm\", \"emc\", \"存储\", \"英特尔\", \"gelsinger\")" NA "E" "EMC"
"19640" "思科EMC合资 加快数据中心战略建设步伐" "资讯" "c(\"存储\", \"服务器\", \"emc\", \"思科\", \"数据中心\")" NA "E" "EMC"
"19641" "传思科和EMC将组合资企业开发数据中心" "资讯" "c(\"服务器\", \"云计算\", \"emc\", \"思科\", \"虚拟化\")" NA "E" "EMC"
"19642" "Intel计划减持一半VMware股票" "资讯" "c(\"emc\", \"思科\", \"vmware\", \"思科\", \"虚拟化\")" NA "E" "EMC"
"19643" "甲骨文拟在欧洲地区裁员最多1000人" "资讯" "c(\"sap\", \"ibm\", \"emc\", \"微软\", \"英特尔\")" NA "E" "EMC"
"19644" "EMC提出18亿美元收购Data Domain" "资讯" "c(\"数据备份\", \"domain\", \"datadomain\", \"收购\", \"emc\")" NA "E" "EMC"
"19645" "EMC高管被判不得加盟惠普" "资讯" "c(\"制造\", \"网络\", \"存储\", \"服务器\", \"emc\")" NA "E" "EMC"
"19646" "EMC高管跳槽惠普被判违反竞业禁止协议" "资讯" "c(\"EMC\", \"高管\", \"跳槽\", \"惠普\", \"emc\")" NA "E" "EMC"
"19647" "EMC创新虚拟矩阵架构Symmetrix V-Max问世" "资讯" "c(\"数据库\", \"虚拟机\", \"虚拟化\", \"存储系统\", \"数据中心\")" NA "E" "EMC"
"19648" "为小企业度身打造削减成本的存储策略" "资讯" "c(\"saas\", \"emc\", \"希捷\", \"互联网\", \"云计算\")" NA "E" "EMC"
"19649" "RSA新报告为首席信息安全官提供战略路线图" "资讯" "c(\"emc\", \"加密\", \"工作\", \"优化\", \"扩展\")" NA "E" "EMC"
"19650" "详解二进制数中1的个数" "极客头条" "c(\"二进制\", \"加密\", \"工作\", \"优化\", \"扩展\")" "tiankonguse" "E" "二进制"
"19651" "二进制数中1的个数" "极客头条" "c(\"二进制\", \"加密\", \"工作\", \"优化\", \"扩展\")" "tiankonguse" "E" "二进制"
"19652" "node.js是如何处理二进制的" "极客头条" "c(\"node.js\", \"二进制\", \"工作\", \"优化\", \"扩展\")" "leogiese" "E" "二进制"
"19653" "二进制类型转换" "极客头条" "c(\"二进制\", \"二进制\", \"工作\", \"优化\", \"扩展\")" "leogiese" "E" "二进制"
"19654" "还在羡慕iOS应用多吗？Cider项目让Android也能运行iOS应用" "资讯" "c(\"Cider\", \"Android\", \"应用\", \"iOS\", \"操作系统\")" NA "E" "二进制"
"19655" "SpringMVC搭配Freemarker实例解析" "极客头条" "c(\"spring mvc\", \"freemarker\", \"java\", \"eclipse\", \"Tomcat\")" "u011225629" "E" "Eclipse"
"19656" "Eclipse 使用 Gradle 下载 Jar 包全纪录" "极客头条" "c(\"Gradle\", \"eclipse\", \"jar\", \"eclipse\", \"Tomcat\")" "never_cxb" "E" "Eclipse"
"19657" "Java实战_手把手编写记事本" "极客头条" "c(\"java\", \"eclipse\", \"SWT\", \"记事本\", \"Tomcat\")" "u011225629" "E" "Eclipse"
"19658" "阿里巴巴内部技术文章：从Eclipse平台看交易平台化" "极客头条" "c(\"Eclipse\", \"架构\", \"SWT\", \"记事本\", \"Tomcat\")" "wince7" "E" "Eclipse"
"19659" "Java基础之List集合原理(二)" "极客头条" "c(\"eclipse\", \"计算机\", \"android\", \"算法\", \"java\")" "xmt1139057136" "E" "Eclipse"
"19660" "Eclipse的Debug介绍与技巧" "极客头条" "c(\"eclipse\", \"debug\", \"android\", \"算法\", \"java\")" "greategatsby" "E" "Eclipse"
"19661" "Eclipse Code Recommenders：基于现实项目推荐代码补全" "极客头条" "c(\"IDE\", \"Eclipse\", \"android\", \"算法\", \"java\")" "u012396362" "E" "Eclipse"
"19662" "Eclipse的Debug介绍与技巧" "极客头条" "c(\"eclipse\", \"debug\", \"android\", \"算法\", \"java\")" "hollis_chuang" "E" "Eclipse"
"19663" "25个让Java程序员更高效的Eclipse插件" "极客头条" "c(\"Java\", \"eclipse\", \"android\", \"算法\", \"java\")" "wenwen091100304" "E" "Eclipse"
"19664" "WebService服务搭建" "极客头条" "c(\"eclipse\", \"WebService\", \"Tomcat配置\", \"Web服务运行\", \"java\")" "crazy1235" "E" "Eclipse"
"19665" "从Linux终端编译运行Eclipse Java项目" "极客头条" "c(\"ECLIPSE\", \"WebService\", \"Tomcat配置\", \"Web服务运行\", \"java\")" "u011109959" "E" "Eclipse"
"19666" "如何在Eclipse中快速导入static变量、方法？" "极客头条" "c(\"eclipse\", \"java\", \"Tomcat配置\", \"Web服务运行\", \"java\")" "u011110579" "E" "Eclipse"
"19667" "Windows下Eclipse连接hadoop" "极客头条" "c(\"eclipse\", \"windows\", \"hadoop\", \"Web服务运行\", \"java\")" "fuqifeipian" "E" "Eclipse"
"19668" "给 Eclipse 提速的7个技巧" "极客头条" "c(\"eclipse\", \"Java\", \"hadoop\", \"Web服务运行\", \"java\")" "u011110579" "E" "Eclipse"
"19669" "Eclipse常用的高效插件" "极客头条" "c(\"eclipse\", \"插件\", \"hadoop\", \"Web服务运行\", \"java\")" "cxygo" "E" "Eclipse"
"19670" "Eclipse常用快捷键，每个程序员都必须知道的" "极客头条" "c(\"程序员\", \"eclipse\", \"hadoop\", \"Web服务运行\", \"java\")" "love468092550" "E" "Eclipse"
"19671" "java swing开发游戏bunnypress,可以直接导入eclipse运行" "极客头条" "c(\"eclipse\", \"游戏\", \"swing\", \"java\", \"java\")" "springmvc_springdata" "E" "Eclipse"
"19672" "eclipse中hadoop2.3.0环境部署及在eclipse中直接提交mapreduce任务" "极客头条" "c(\"mapreduce\", \"eclipse\", \"hadoop\", \"java\", \"java\")" "longdeyun" "E" "Eclipse"
"19673" "openstack开发之通过eclipse导入openstack源码（python）高可靠文档" "极客头条" "c(\"openstack\", \"eclipse\", \"python\", \"源码\", \"文档\")" "bj278595437" "E" "Eclipse"
"19674" "GoClipse —— Eclipse 的 Go 语言开发插件" "极客头条" "c(\"Eclipse\", \"语言\", \"插件\", \"GoClipse\", \"GO\")" "qiansg123" "E" "Eclipse"
"19675" "如何导入JEECMS源代码到eclipse集成开发环境详细步骤" "极客头条" "c(\"源代码\", \"eclipse\", \"JEECMS\", \"MySQL\", \"GO\")" "wenkaishun" "E" "Eclipse"
"19676" "小心 Eclipse Java Compiler 编译出来的 Class" "极客头条" "c(\"Eclipse\", \"Java\", \"Compiler\", \"MySQL\", \"GO\")" "qiansg123" "E" "Eclipse"
"19677" "最常用的Eclipse快捷键" "极客头条" "c(\"eclipse\", \"Java\", \"Compiler\", \"MySQL\", \"GO\")" "kobi521" "E" "Eclipse"
"19678" "Eclipse 4.4 Luna发布：全面支持Java8，全新黑色主题" "极客头条" "c(\"eclipse\", \"发布\", \"java\", \"MySQL\", \"GO\")" "u011110579" "E" "Eclipse"
"19679" "Eclipse中Android公共库的正确建立及调用方法" "极客头条" "c(\"eclipse\", \"android\", \"库\", \"MySQL\", \"GO\")" "mary20110116" "E" "Eclipse"
"19680" "Eclipse 4.4 将于 6 月 25 日发布，代号 Luna" "极客头条" "c(\"Eclipse\", \"android\", \"库\", \"MySQL\", \"GO\")" "linxiyu52" "E" "Eclipse"
"19681" "浅析配置更快的Eclipse方法" "极客头条" "c(\"eclipse\", \"java\", \"库\", \"MySQL\", \"GO\")" "kobi521" "E" "Eclipse"
"19682" "Java常见的一些问题解决方法" "极客头条" "c(\"Java\", \"MyEclipse\", \"Eclipse\", \"bug\", \"GO\")" "u010544717" "E" "Eclipse"
"19683" "TypeScript1.0发布，完美支持Visual Studio系列产品" "资讯" "c(\"typescript\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" NA "E" "Eclipse"
"19684" "Eclipse酷炫项目、最新趋势介绍" "极客头条" "c(\"Eclipse\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" "u011110579" "E" "Eclipse"
"19685" "最好的Java IDE之争：Eclipse PK IntelliJ IDEA" "资讯" "c(\"intellij\", \"eclipse\", \"开源项目\", \"Java\", \"javascript\")" NA "E" "Eclipse"
"19686" "Eclipse基金会涉足物联网，M2M标准是否已获东风？" "资讯" "c(\"Eclipse\", \"物联网\", \"开源项目\", \"Java\", \"javascript\")" NA "E" "Eclipse"
"19687" "Eclipse 4.3 正式版发布 代号Kepler" "资讯" "c(\"Eclipse\", \"Java\", \"开源项目\", \"Java\", \"javascript\")" NA "E" "Eclipse"
"19688" "《程序员》2006年5月刊：Eclipse风暴" "资讯" "c(\"《程序员》\", \"2006年5月刊\", \"封面秀\", \"Eclipse\", \"javascript\")" NA "E" "Eclipse"
"19689" "你应该关注的几个Eclipse超酷插件" "资讯" "c(\"Eclipse\", \"IDE\", \"Java\", \"开源\", \"javascript\")" NA "E" "Eclipse"
"19690" "是时候抛弃Eclipse转向IntelliJ了" "资讯" "c(\"Eclipse\", \"Intellij\", \"Android\", \"Google\", \"IDE\")" NA "E" "Eclipse"
"19691" "Android Studio来了，它能取代Eclipse吗？" "资讯" "c(\"Android\", \"Google I/O\", \"Android Studio\", \"开发工具\", \"移动开发\")" NA "E" "Eclipse"
"19692" "移动周报：“先验证，后开发”的App开发必杀技" "资讯" "c(\"移动周报\", \"Eclipse\", \"Buffer\", \"Android\", \"Samsung\")" NA "E" "Eclipse"
"19693" "Android开发必备：Eclipse 4.2 SR2版本发布" "资讯" "c(\"Eclipse\", \"Android\", \"Java\", \"开发工具\", \"移动开发\")" NA "E" "Eclipse"
"19694" "6个Java项目UML反向工程工具" "资讯" "c(\"Java\", \"UML\", \"编程语言\", \"Eclipse\", \"ModelGoon\")" NA "E" "Eclipse"
"19695" "Java中十个常见的违规编码" "资讯" "c(\"Java\", \"Eclipse\", \"代码\", \"编程\", \"ModelGoon\")" NA "E" "Eclipse"
"19696" "神奇的AIDE：在Android设备上开发Android应用" "资讯" "c(\"Android\", \"AIDE\", \"移动开发\", \"Eclipse\", \"ModelGoon\")" NA "E" "Eclipse"
"19697" "Java程序员应该知道的10个调试技巧" "资讯" "c(\"Eclipse\", \"Java\", \"研发实践\", \"Bug\", \"ModelGoon\")" NA "E" "Eclipse"
"19698" "Cloud Foundry Eclipse集成支持数据通道功能" "资讯" "c(\"CloudFoundry\", \"Eclipse\", \"VMware\", \"Bug\", \"ModelGoon\")" NA "E" "Eclipse"
"19699" "开发人员眼中最好的代码编辑器是谁？" "资讯" "c(\"跨平台\", \"Eclipse\", \"开发\", \"前端开发\", \"VS\")" NA "E" "Eclipse"
"19700" "我为什么会使用Eclipse Juno？" "资讯" "c(\"Eclipse\", \"bug\", \"应用平台\", \"Git\", \"开源工具\")" NA "E" "Eclipse"
"19701" "Eclipse开发Android太麻烦？试试IntelliJ IDEA吧" "资讯" "c(\"google\", \"idea\", \"eclipse\", \"android\", \"intellij\")" NA "E" "Eclipse"
"19702" "Eclipse即将发布基于浏览器的IDE" "资讯" "c(\"javascript\", \"eclipse插件\", \"eclipse\", \"开发工具\", \"ide\")" NA "E" "Eclipse"
"19703" "为什么IDEA比Eclipse更好？" "资讯" "c(\"平台\", \"工作\", \"intellij\", \"idea\", \"eclipse\")" NA "E" "Eclipse"
"19704" "开发者吐槽Android Build Process：我已经出离愤怒了！" "资讯" "c(\"eclipse\", \"android\", \"facebook\", \"build\", \"开发\")" NA "E" "Eclipse"
"19705" "Eclipse Code Recommenders正式发布 智能代码建议工具" "资讯" "c(\"java\", \"tools\", \"公告\", \"eclipse\", \"工具\")" NA "E" "Eclipse"
"19706" "Lua开发工具脱离Eclipse 成为独立版本" "资讯" "c(\"游戏\", \"eclipse\", \"开发工具\", \"嵌入式\", \"lua\")" NA "E" "Eclipse"
"19707" "Jetty 9将有哪些新功能？" "资讯" "c(\"google\", \"eclipse\", \"服务器\", \"jetty\", \"网络协议\")" NA "E" "Eclipse"
"19708" "LG手机ICS更新名单出炉 明年分两批进行" "资讯" "c(\"android\", \"eclipse\", \"手机\", \"lg\", \"网络协议\")" NA "E" "Eclipse"
"19709" "Eclipse Xtend对Java说：我帮你瘦身" "资讯" "c(\"编程\", \"文档\", \"eclipse\", \"java\", \"xtend\")" NA "E" "Eclipse"
"19710" "Eclipse推出新语言Xtend" "资讯" "c(\"语言\", \"javascript\", \"coffeescript\", \"eclipse\", \"xtend\")" NA "E" "Eclipse"
"19711" "Eclipse 3.7.1发布 支持Java 7" "资讯" "c(\"eclipse\", \"websphere\", \"开发工具\", \"myeclipse\", \"java\")" NA "E" "Eclipse"
"19712" "Eclipse 3.8M1提供Java7支持" "资讯" "c(\"java\", \"idea\", \"netbeans\", \"eclipse\", \"java7\")" NA "E" "Eclipse"
"19713" "分析称：Android开放程度最低 Eclipse高于Linux聚首" "资讯" "c(\"android\", \"eclipse\", \"Linux\", \"开放\", \"java7\")" NA "E" "Eclipse"
"19714" "JDK 7首个RC版本发布！" "资讯" "c(\"测试\", \"eclipse\", \"单元测试\", \"rc\", \"jdk\")" NA "E" "Eclipse"
"19715" "Eclipse 3.7（代号Indigo）正式版发布！" "资讯" "c(\"工具\", \"平台\", \"开发工具\", \"eclipse\", \"版本控制系统\")" NA "E" "Eclipse"
"19716" "MyFaces Core v2.0.7/2.1.1 发布，JSF框架" "资讯" "c(\"eclipse\", \"web框架\", \"jsf\", \"框架\", \"jsf框架\")" NA "E" "Eclipse"
"19717" "如何成为优秀的开发人员？" "资讯" "c(\"eclipse\", \"语言\", \"工具\", \"数据结构\", \"文本编辑\")" NA "E" "Eclipse"
"19718" "2011 IBM Rational Jazz创新大赛启动" "资讯" "c(\"ibm\", \"jazz\", \"软件测试\", \"eclipse\", \"云计算\")" NA "E" "Eclipse"
"19719" "微软推出Eclipse插件CTP以优化Azure开发" "资讯" "c(\"Azure\", \"CTP\", \"Eclipse\", \"微软\", \"云计算\")" NA "E" "Eclipse"
"19720" "微软修改应用商店政策：由出版商提交和定价" "资讯" "c(\"eclipse\", \"microsoft\", \"出版\", \"微软\", \"应用商店\")" NA "E" "Eclipse"
"19721" "代码自动生成工具Acceleo 3.0 发布" "资讯" "c(\"框架\", \"eclipse\", \"工具\", \"3.0\", \"acceleo\")" NA "E" "Eclipse"
"19722" "JBoss Riftsaw 2.2.0.CR2 发布" "资讯" "c(\"服务器\", \"riftsaw\", \"eclipse\", \"jbosstools\", \"jboss\")" NA "E" "Eclipse"
"19723" "如何在Windows平台上用Eclipse调试运行HBase" "资讯" "c(\"server\", \"虚拟机\", \"eclipse\", \"平台\", \"windows\")" NA "E" "Eclipse"
"19724" "Apache威胁放弃Java 要求甲骨文放弃授权协议限制" "资讯" "c(\"eclipse\", \"平台\", \"微软\", \"apache\", \"java\")" NA "E" "Eclipse"
"19725" "甲骨文OTN用户超1000万 加大支持Java和开源社区" "资讯" "c(\"eclipse\", \"数据库\", \"java\", \"glassfish\", \"中间件\")" NA "E" "Eclipse"
"19726" "25个最佳最闪亮的Eclipse开发项目" "资讯" "c(\"http服务器\", \"eclipse\", \"java开发工具\", \"php开发工具\", \"eclipse插件\")" NA "E" "Eclipse"
"19727" "MyEclipse 8.6正式版发布" "资讯" "c(\"c\", \"linux\", \"64bit\", \"windows\", \"eclipse\")" NA "E" "Eclipse"
"19728" "Oracle发布JDK1.6 Update21修复导致Eclipse崩溃问题" "资讯" "c(\"linux\", \"开发工具\", \"jdk\", \"eclipse\", \"oracle\")" NA "E" "Eclipse"
"19729" "Oracle更换Java中企业名称致Eclipse崩溃" "资讯" "c(\"eclipse\", \"outofmemorye\", \"开发工具\", \"java\", \"oracle\")" NA "E" "Eclipse"
"19730" "Compuware Workbench八月推出  提升大型主机应用开发生产力" "资讯" "c(\"eclipse\", \"平台\", \"工作\", \"编程\", \"分布式应用\")" NA "E" "Eclipse"
"19731" "Eclipse SDK 4.0发布 新增面向服务的开发模板" "资讯" "c(\"tools\", \"css\", \"平台\", \"框架\", \"eclipse\")" NA "E" "Eclipse"
"19732" "Eclipse SDK 4.0发布 新增面向服务的开发模板" "资讯" "c(\"tools\", \"css\", \"平台\", \"框架\", \"eclipse\")" NA "E" "Eclipse"
"19733" "Symbian^3 Product Development Kit (PDK 3.0.0) 发布" "资讯" "c(\"图形\", \"手机\", \"eclipse\", \"平台\", \"symbian\")" NA "E" "Eclipse"
"19734" "重要快讯：首个Symbian^3 完整开发包发布" "资讯" "c(\"网络\", \"图形\", \"eclipse\", \"平台\", \"symbian\")" NA "E" "Eclipse"
"19735" "JBoss Tools on Eclipse 3.6 (Helios) 新版发布" "资讯" "c(\"freemarker\", \"开发工具\", \"tools\", \"jboss\", \"eclipse\")" NA "E" "Eclipse"
"19736" "Eclipse 3.6版本正式发布 代号“太阳神”" "资讯" "c(\"平台\", \"语言\", \"spring\", \"框架\", \"eclipse\")" NA "E" "Eclipse"
"19737" "Eclipse 3.6 最后一个RC版本(RC4)发布" "资讯" "c(\"2010\", \"eclipse\", \"spring\", \"框架\", \"eclipse\")" NA "E" "Eclipse"
"19738" "Eclipse 4.0 SDK 初始版及 E5 M5 发布" "资讯" "c(\"xml\", \"tools\", \"build\", \"2010\", \"eclipse\")" NA "E" "Eclipse"
"19739" "如何基于Eclipse的组件内使用RIA技术" "资讯" "c(\"工作\", \"扩展\", \"平台\", \"框架\", \"eclipse\")" NA "E" "Eclipse"
"19740" "IBM和Eclipse正努力推进OSGi的模块化" "资讯" "c(\"程序开发\", \"插件和扩展\", \"osgi\", \"eclipse\", \"ibm\")" NA "E" "Eclipse"
"19741" "Eclipse 3.6M5 发布 新增动态路径变量等特性" "资讯" "c(\"3.6，里程碑\", \"浏览器\", \"编译器\", \"java开发工具\", \"eclipse\")" NA "E" "Eclipse"
"19742" "Eclipse也推出了应用商店 Eclipse Marketplace" "资讯" "c(\"ubuntu\", \"android\", \"互联网\", \"中国移动\", \"eclipse\")" NA "E" "Eclipse"
"19743" "微软与Eclipse成伙伴推进Azure开发" "资讯" "c(\"工具\", \"扩展\", \"server\", \"silverlight\", \"eclipse\")" NA "E" "Eclipse"
"19744" "Eclipse也推出了应用商店" "资讯" "c(\"nokia\", \"ubuntu\", \"android\", \"互联网\", \"中国移动\")" NA "E" "Eclipse"
"19745" "盘点2009：Eclipse稳步前进" "资讯" "c(\"09盘点，eclipse\", \"thoughtworks\", \"eclipse插件\", \"eclipse\", \"移动开发\")" NA "E" "Eclipse"
"19746" "Eclipse Marketplace上线　取代Eclipse外挂中心" "资讯" "c(\"教育\", \"产品\", \"eclipse，mark\", \"平台\", \"eclipse\")" NA "E" "Eclipse"
"19747" "Eclipse 也推出了应用商店 Eclipse Marketplace" "资讯" "c(\"互联网\", \"中国移动\", \"marketplace，\", \"，eclipse\", \"eclipse\")" NA "E" "Eclipse"
"19748" "独家：Eclipse 的开源内幕 一个开源社区还是商业组织？" "资讯" "c(\"公告\", \"版本控制系统\", \"基金会\", \"，开源，eclipse\", \"eclipse\")" NA "E" "Eclipse"
"19749" "RIM推新开发工具 用于开发BlackBerry Web应用程序" "资讯" "c(\"RIM\", \"BlackBerry\", \"Eclipse\", \"智能手机\", \"eclipse\")" NA "E" "Eclipse"
"19750" "实例详解快捷搭建Android手机开发平台" "资讯" "c(\"Android\", \"JDK\", \"Eclipse\", \"手机开发平台\", \"eclipse\")" NA "E" "Eclipse"
"19751" "独家：Java版的Eclipse源代码控制插件发布" "资讯" "c(\"工具\", \"配置管理\", \"visualizatio\", \"java\", \"eclipse\")" NA "E" "Eclipse"
"19752" "独家：专访Groovy Eclipse v2开发团队 分享Eclipse插件开发经验" "资讯" "c(\"工具\", \"开发工具\", \"groovy\", \"eclipse\", \"eclipse插件\")" NA "E" "Eclipse"
"19753" "教程：如何编写一个基本的Android应用程序" "资讯" "c(\"Android\", \"应用程序\", \"iPhone OS\", \"BlackBerry\", \"Eclipse\")" NA "E" "Eclipse"
"19754" "利用跨站脚本攻击Eclipse本地Web服务器" "资讯" "c(\"websphere\", \"开发工具\", \"eclipse\", \"脚本\", \"web服务\")" NA "E" "Eclipse"
"19755" "详讯：Oracle发布Enterprise Pack for Eclipse 11gR1" "资讯" "c(\"database\", \"网络\", \"application\", \"eclipse\", \"oracle\")" NA "E" "Eclipse"
"19756" "独家： 6个备受程序员喜爱的Eclipse JDT 特性" "资讯" "c(\"import\", \"eclipse\", \"application\", \"eclipse\", \"oracle\")" NA "E" "Eclipse"
"19757" "整合Sun和Eclipse支持Solaris x86" "资讯" "c(\"平台\", \"服务器\", \"sun\", \"eclipse\", \"solaris\")" NA "E" "Eclipse"
"19758" "Eclipse 3.5发布" "资讯" "c(\"跨平台\", \"框架\", \"开发工具\", \"3.5\", \"eclipse\")" NA "E" "Eclipse"
"19759" "Eclipse SDK 3.5RC2（Stable Build）发布" "资讯" "c(\"跨平台\", \"框架\", \"开发工具\", \"build\", \"eclipse\")" NA "E" "Eclipse"
"19760" "独家：用于Java代码分析的Eclipse插件nWire 1.1发布" "资讯" "c(\"eclipse\", \"java\", \"代码分析\", \"编程\", \"eclipse插件\")" NA "E" "Eclipse"
"19761" "独家：新Eclipse插件—为Java 、PHP和Rails的应用添加云托管功能" "资讯" "c(\"rails\", \"java\", \"php\", \"eclipse插件\", \"eclipse\")" NA "E" "Eclipse"
"19762" "独家：基于Eclipse的Scala IDE发布更新" "资讯" "c(\"osgi框架\", \"scala\", \"ide\", \"eclipse\", \"开发工具\")" NA "E" "Eclipse"
"19763" "数据库开发这点事-1.4 Eclipse使用简介" "资讯" "c(\"工作\", \"database\", \"structure\", \"eclipse\", \"数据库\")" NA "E" "Eclipse"
"19764" "Android学习笔记（三）：Andriod程序框架" "资讯" "c(\"java\", \"框架\", \"colors\", \"eclipse\", \"android\")" NA "E" "Eclipse"
"19765" "基于模型的可复用移动web应用程序开发-画出一个iPhone应用" "资讯" "c(\"eclipse\", \"浏览器\", \"web\", \"iphone\", \"程序开发\")" NA "E" "Eclipse"
"19766" "Android学习笔记（二）：安装环境" "资讯" "c(\"android\", \"x86\", \"j2se\", \"工具\", \"eclipse\")" NA "E" "Eclipse"
"19767" "用纯JavaScript实现的微信二维码图片生成器" "极客头条" "c(\"JavaScript\", \"二维码\", \"j2se\", \"工具\", \"eclipse\")" "oudahe" "E" "二维码"
"19768" "取代现金和信用卡？移动支付需要剔除的绊脚石" "资讯" "c(\"移动支付\", \"漏洞\", \"二维码\", \"安全\", \"Apple\")" NA "E" "二维码"
"19769" "松下新技术把数据融入灯光中 智能手机读取" "资讯" "c(\"松下\", \"LED\", \"智能手机\", \"二维码\", \"数据\")" NA "E" "二维码"
"19770" "老外看中国：移动应用UI设计的十大精髓" "资讯" "c(\"移动开发\", \"UI\", \"设计\", \"微信\", \"趋势\")" NA "E" "二维码"
"19771" "酷炫的微信二维码" "极客头条" "c(\"微信\", \"二维码\", \"设计\", \"微信\", \"趋势\")" "kiritor" "E" "二维码"
"19772" "如何生成二维码过程详解" "极客头条" "c(\"blog\", \"二维码\", \"设计\", \"微信\", \"趋势\")" "longdeyun" "E" "二维码"
"19773" "详解Google Authenticator工作原理" "资讯" "c(\"Google\", \"二维码\", \"Google Authenticator\", \"算法\", \"趋势\")" NA "E" "二维码"
"19774" "开源门户系统蝉知发布 2.2 版本，全面集成微信" "资讯" "c(\"蝉知\", \"开源\", \"微信\", \"二维码\", \"趋势\")" NA "E" "二维码"
"19775" "专访多信创始人胡泊：将二维码包装成产品 让物体开口说话" "资讯" "c(\"社区之星\", \"胡泊\", \"多信\", \"云存储\", \"产品\")" NA "E" "二维码"
"19776" "死磕微信支付，新浪微博正式推出微博支付" "资讯" "c(\"新浪微博\", \"移动支付\", \"电子商务\", \"二维码\", \"移动互联网\")" NA "E" "二维码"
"19777" "“蛐蛐儿”创始人朱连兴：音频二维码的技术实现和应用场景" "资讯" "c(\"NFC\", \"音频二维码\", \"CMDN\", \"二维码\", \"移动互联网\")" NA "E" "二维码"
"19778" "信恩科技创始人林兴陆：QR Code二维码的前世今生" "资讯" "c(\"CMDN\", \"信恩科技\", \"二维码\", \"NFC\", \"移动互联网\")" NA "E" "二维码"
"19779" "CMDN Club 23期：开放平台和O2O移动产品开发" "资讯" "c(\"天翼开放平台\", \"二维码\", \"O2O\", \"CMDN\", \"移动互联网\")" NA "E" "二维码"
"19780" "正确使用二维码进行市场推广的20个要点（上）" "资讯" "c(\"二维码\", \"市场推广\", \"O2O\", \"CMDN\", \"移动互联网\")" NA "E" "二维码"
"19781" "危险的二维码" "资讯" "c(\"数据库\", \"浏览器\", \"网络\", \"安全\", \"二维码\")" NA "E" "二维码"
"19782" "移动开发者大视野02期：手机二维码应用潜力无限" "资讯" "c(\"移动开发\", \"手机\", \"大视野\", \"潜力\", \"二维码\")" NA "E" "二维码"
"19783" "物联网钱途浮现技术之争 二维码与RFID博弈加剧" "资讯" "c(\"电子商务\", \"跨平台\", \"物联网\", \"rfid\", \"二维码\")" NA "E" "二维码"
"19784" "张小龙作品：Mac版Foxmail下载－极简设计，Retina优化，让Exchange不再臃肿" "极客头条" "c(\"性能优化\", \"Mac\", \"Exchange\", \"Retina \", \"张小龙\")" "jiangtao" "E" "Exchange"
"19785" "扶持免费移动应用：Tapjoy的500万美元基金谁来拿？" "资讯" "c(\"exchange\", \"游戏\", \"移动游戏\", \"mobile\", \"tapjoy\")" NA "E" "Exchange"
"19786" "Equinix数据中心 配生物识别系统(图)" "资讯" "c(\"金融\", \"数据中心\", \"exchange\", \"生物\", \"equinix\")" NA "E" "Exchange"
"19787" "数据中心行业能耗测量标准任重而道远" "资讯" "c(\"资讯\", \"腾讯\", \"网格\", \"exchange\", \"数据中心\")" NA "E" "Exchange"
"19788" "【观点】在IT界取得成功应该知道的10件事" "资讯" "c(\"exchange\", \"网络\", \"数据库\", \"服务器\", \"it\")" NA "E" "Exchange"
"19789" "微软斥资58亿美元激励合作伙伴进军云计算" "资讯" "c(\"office\", \"产品\", \"exchange\", \"微软\", \"云计算\")" NA "E" "Exchange"
"19790" "微软内部称收购Skype完全为增援Lync" "资讯" "c(\"平台\", \"产品\", \"lync\", \"微软\", \"exchange\")" NA "E" "Exchange"
"19791" "Stack Exchange的架构" "资讯" "c(\"系统监控\", \"exchange\", \"cruisecontro\", \"数据中心\", \"架构\")" NA "E" "Exchange"
"19792" "谷歌称Apps用户达到3000万" "资讯" "c(\"office\", \"salesforce\", \"exchange\", \"google\", \"云计算\")" NA "E" "Exchange"
"19793" "Exchange For Change——第二届中国iOS开发者大会即将召开" "资讯" "c(\"平台\", \"开发\", \"ios\", \"exchange\", \"苹果应用\")" NA "E" "Exchange"
"19794" "分析：为什么多帐户登陆对谷歌很重要" "资讯" "c(\"gmail\", \"浏览器\", \"谷歌\", \"exchange\", \"多账户登录\")" NA "E" "Exchange"
"19795" "Android 2.2 (Froyo) 源码已经公布" "资讯" "c(\"google\", \"verizon\", \"exchange\", \"浏览器\", \"android\")" NA "E" "Exchange"
"19796" "苹果iPhone OS操作系统更名为iOS" "资讯" "c(\"server\", \"exchange\", \"手机\", \"搜索引擎\", \"iphone\")" NA "E" "Exchange"
"19797" "微软宣布Exchange Online云存储空间升级至25GB" "资讯" "c(\"powershell\", \"微软\", \"存储\", \"exchange\", \"云存储\")" NA "E" "Exchange"
"19798" "微软正式推出Exchange2010 邮件可整合语音信息" "资讯" "c(\"microsoft\", \"2010\", \"exchange\", \"微软\", \"exchange2010\")" NA "E" "Exchange"
"19799" "微软今天正式发布Exchange Server 2010" "资讯" "c(\"微软\", \"exchange\", \"微软，exchange\", \"，发布\", \"server\")" NA "E" "Exchange"
"19800" "微软：中国已有12家大型企业部署Win 7" "资讯" "c(\"exchange\", \"平台\", \"产品\", \"server\", \"微软\")" NA "E" "Exchange"
"19801" "实践电子医疗病历的9点经验" "资讯" "c(\"产品\", \"测试\", \"exchange\", \"医疗\", \"咨询\")" NA "E" "Exchange"
"19802" "微软技术大会Tech·Ed 2009召开在即" "资讯" "c(\"微软\", \"企业应用\", \"虚拟化\", \"exchange\", \"优化\")" NA "E" "Exchange"
"19803" "谷歌发布Android 2.0平台 新增许多功能" "资讯" "c(\"exchange\", \"编程\", \"平台\", \"浏览器\", \"android\")" NA "E" "Exchange"
"19804" "微软Exchange 2010 RTM版泄露" "资讯" "c(\"浏览器\", \"powershell\", \"2010\", \"exchange\", \"微软\")" NA "E" "Exchange"
"19805" "Exchange 2010 VS 2007：微软缘何厚此薄彼" "资讯" "c(\"测试\", \"邮件服务器\", \"exchange\", \"2010\", \"微软\")" NA "E" "Exchange"
"19806" "李开复等17员大将离职 凸显谷歌4大问题" "资讯" "c(\"工作\", \"创业\", \"exchange\", \"2010\", \"微软\")" NA "E" "Exchange"
"19807" "鲍尔默将亲自主持微软Windows 7发布会" "资讯" "c(\"exchange\", \"活动\", \"server\", \"windows\", \"微软\")" NA "E" "Exchange"
"19808" "苹果周五发售“雪豹”操作系统" "资讯" "c(\"优化\", \"微软\", \"server\", \"exchange\", \"英特尔\")" NA "E" "Exchange"
"19809" "NEC机架服务器顺利通过VMmark虚拟化测试" "资讯" "c(\"exchange\", \"测试\", \"测试工具\", \"服务器\", \"虚拟化\")" NA "E" "Exchange"
"19810" "微软发布Exchange 2010最终测试版" "资讯" "c(\"邮件服务器\", \"2010\", \"exchange\", \"微软\", \"测试\")" NA "E" "Exchange"
"19811" "微软:服务器转至网络托管 云计算有利Exchange" "资讯" "c(\"exchange\", \"微软\", \"网络\", \"云计算\", \"服务器\")" NA "E" "Exchange"
"19812" "商业周刊：微软应停止投资Windows Mobile" "资讯" "c(\"Windows Mobi\", \"微软\", \"谷歌\", \"智能手机\", \"Exchange\")" NA "E" "Exchange"
"19813" "Blueman - Ubuntu的蓝牙管理器" "资讯" "c(\"object\", \"exchange\", \"网络\", \"文本编辑\", \"ubuntu\")" NA "E" "Exchange"
"19814" "商业周刊：微软产品全面降价以提高市场份额" "资讯" "c(\"exchange\", \"google\", \"互联网\", \"搜索引擎\", \"微软\")" NA "E" "Exchange"
"19815" "从HPC的应用看刀片与机架服务器" "资讯" "c(\"hp\", \"x86\", \"exchange\", \"网络\", \"system\")" NA "E" "Exchange"
"19816" "邮件服务器软件——MDaemon与Exchange之PK" "资讯" "c(\"微软\", \"工作\", \"杀毒软件\", \"exchange\", \"邮件服务器\")" NA "E" "Exchange"
"19817" "安装Exchange 2000 实现随时随地的通讯" "资讯" "c(\"licensing\", \"components\", \"服务器\", \"http服务器\", \"exchange\")" NA "E" "Exchange"
"19818" "系统分析员眼中的从Exchange到Domino的应用迁移" "资讯" "c(\"服务器\", \"开发工具\", \"项目管理\", \"网络会议\", \"exchange\")" NA "E" "Exchange"
"19819" "Palm WebOS SDK夏末公布" "资讯" "c(\"iphone\", \"exchange\", \"手机\", \"google\", \"palm\")" NA "E" "Exchange"
"19820" "从HPC的应用看刀片与机架服务器" "资讯" "c(\"hp\", \"x86\", \"exchange\", \"网络\", \"system\")" NA "E" "Exchange"
"19821" "Google Apps Sync让Outlook搜索功能残废" "资讯" "c(\"server\", \"windows\", \"exchange\", \"微软\", \"企业应用\")" NA "E" "Exchange"
"19822" "远程集群技术: 让你的应用不间断" "资讯" "c(\"exchange\", \"磁盘\", \"network\", \"数据库\", \"集群\")" NA "E" "Exchange"
"19823" "两种Exchange集群的区别及优劣" "资讯" "c(\"windows\", \"存储\", \"数据库\", \"exchange\", \"集群\")" NA "E" "Exchange"
"19824" "苹果发布Snow Leopard 兼容微软Exchange" "资讯" "c(\"exchange\", \"微软\", \"，exchange\", \"leopard\", \"snow\")" NA "E" "Exchange"
"19825" "解决Exchange中服务器不能发送信息问题" "资讯" "c(\"server\", \"delay\", \"磁盘\", \"exchange\", \"服务器\")" NA "E" "Exchange"
"19826" "快讯：Borland将被Micro Focus International plc收购" "资讯" "c(\"service\", \"include\", \"security\", \"exchange\", \"borland\")" NA "E" "Exchange"
"19827" "RSA安全大会将亮相25款热门安全产品" "资讯" "c(\"exchange\", \"加密\", \"工具\", \"产品\", \"encryption\")" NA "E" "Exchange"
"19828" "为虚拟机选择合适的服务器硬件" "资讯" "c(\"exchange\", \"网络\", \"存储\", \"虚拟化\", \"虚拟机\")" NA "E" "Exchange"
"19829" "新版Hotmail终于支持Exchange ActiveSync协议" "资讯" "c(\"2010\", \"日历\", \"windows\", \"手机\", \"exchange\")" NA "E" "Exchange"
"19830" "Google和eBay在建设微服务生态系统中的深刻教训" "极客头条" "c(\"Google\", \"eBay\", \"微服务\", \"架构\", \"exchange\")" "zhong930" "E" "eBay"
"19831" "从Google与eBay的微服务生态系统架构学到的经验和教训" "极客头条" "c(\"Google\", \"eBay\", \"微服务\", \"架构\", \"exchange\")" "rnifeasy" "E" "eBay"
"19832" "ebay拥抱容器：OpenStack云环境下部署Kubernetes和Containers" "资讯" "c(\"云计算\", \"基础架构\", \"eBay\", \"Kubernetes\", \"容器\")" NA "E" "eBay"
"19833" "Apache Eagle——eBay开源分布式实时Hadoop数据安全方案" "资讯" "c(\"开源\", \"大数据\", \" Apache Eagle\", \"eBay\", \"Hadoop\")" NA "E" "eBay"
"19834" "eBay的Connected Commerce大数据平台实践" "资讯" "c(\"大数据\", \"eBay\", \"开源\", \"Kylin\", \"Hadoop\")" NA "E" "eBay"
"19835" "eBay：如何用HDFS分层策略优化数千节点、数百PB的数据存储" "资讯" "c(\"HDFS\", \"分层存储\", \"eBay\", \"hadoop集群\", \"大数据存储\")" NA "E" "eBay"
"19836" "大数据应用论坛（上）：现场直击百度、腾讯、eBay等大数据应用实践" "资讯" "c(\"大数据\", \"BDTC\", \"BDTC2014\", \"百度\", \"腾讯\")" NA "E" "eBay"
"19837" "eBay上海大数据峰会：技术热点与应用实践的融合" "资讯" "c(\"大数据\", \"eBay\", \"数据分析\", \"数据架构\", \"腾讯\")" NA "E" "eBay"
"19838" "Kylin正式发布：面向大数据的终极OLAP引擎方案" "资讯" "c(\"大数据\", \"Kylin\", \"eBay\", \"数据架构\", \"腾讯\")" NA "E" "eBay"
"19839" "eBay上海大数据峰会：大数据技术探讨和价值发现" "资讯" "c(\"大数据\", \"eBay\", \"机器学习\", \"架构\", \"数据仓库\")" NA "E" "eBay"
"19840" "阿里市值美科技股第四 首日即超亚马逊和eBay之和" "资讯" "c(\"阿里巴巴\", \"eBay\", \"Amazon\", \"Google\", \"Apple\")" NA "E" "eBay"
"19841" "Flash曝严重漏洞 波及eBay和Tumblr等网站" "极客头条" "c(\"tumblr\", \"漏洞\", \"flash\", \"ebay\", \"Apple\")" "u014648882" "E" "eBay"
"19842" "eBay基础设施的成功经验，我们该如何复制？" "资讯" "c(\"云计算\", \"eBay\", \"Hadoop\", \"Pivotal\", \"Apple\")" NA "E" "eBay"
"19843" "一周热点：Top100高薪技术岗位、高端种菜模式、麻省理工TR35" "资讯" "c(\"云热点\", \"大数据\", \"数据中心\", \"物联网\", \"NoSQL\")" NA "E" "eBay"
"19844" "早Google一步，eBay数据中心率先搭载了火星上使用的技术" "资讯" "c(\"数据中心\", \"Google\", \"eBay\", \"燃料电池\", \"Bloom Enegy\")" NA "E" "eBay"
"19845" "看eBay如何评价他们的Node.js首次尝鲜" "资讯" "c(\"Java\", \"eBay\", \"Node.js\", \"研发实践\", \"Bloom Enegy\")" NA "E" "eBay"
"19846" "来自eBay的实战经验分享：我们是如何构建首个Node.js应用程序的" "极客头条" "c(\"应用\", \"eBay\", \"Node.js\", \"经验\", \"Bloom Enegy\")" "mengyidan" "E" "eBay"
"19847" "来自Google、Amazon和Facebook等7大知名互联网的系统扩展经验" "资讯" "c(\"Google\", \"Twitter\", \"Facebook\", \"Instagram\", \"eBay\")" NA "E" "eBay"
"19848" "paypal和ebay的80000台服务器将用openstack替代vmware" "极客头条" "c(\"服务器\", \"OpenStack\", \"eBay\", \"PayPal\", \"VMware\")" "baozi0" "E" "eBay"
"19849" "两家巨头相继放弃移动广告，移动广告形势堪忧？" "资讯" "c(\"eBay\", \"Facebook\", \"移动广告\", \"PayPal\", \"VMware\")" NA "E" "eBay"
"19850" "当数据中心遭遇污水 微软新能源数据中心的诞生" "资讯" "c(\"燃料电池\", \"数据中心\", \"Microsoft\", \"Apple\", \"eBay\")" NA "E" "eBay"
"19851" "eBay收购社会化购物网站Svpply" "资讯" "c(\"Sypply\", \"eBay\", \"电子商务\", \"社会化\", \"ZachKlein\")" NA "E" "eBay"
"19852" "OpenStack与Nicira双剑合璧打造eBay云平台" "资讯" "c(\"云计算\", \"开源\", \"OpenStack\", \"eBay\", \"Nicira\")" NA "E" "eBay"
"19853" "eBay推出“当日送达”服务eBay Now" "资讯" "c(\"当日送达\", \"产品\", \"网购\", \"eBay\", \"now\")" NA "E" "eBay"
"19854" "那些战胜了美国互联网明星的本地网站" "资讯" "c(\"Facebook\", \"谷歌\", \"eBay\", \"国际网站\", \"本土\")" NA "E" "eBay"
"19855" "分析称eBay应分拆PayPal 股东价值将增长30%" "资讯" "c(\"产品\", \"测试\", \"ebay\", \"paypal\", \"分拆\")" NA "E" "eBay"
"19856" "API调用太麻烦 eBay推出Web查询语言" "资讯" "c(\"web服务\", \"web\", \"ql.io\", \"ebay\", \"api\")" NA "E" "eBay"
"19857" "eBay发布世界首个开放电子商务平台X.commerce" "资讯" "c(\"电子商务\", \"ebay\", \"x.commerce\", \"平台\", \"电子商务平台\")" NA "E" "eBay"
"19858" "eBay创建新部门以讨好开发者 吸引更多商家" "资讯" "c(\"magento\", \"平台\", \"互联网\", \"电子商务\", \"ebay\")" NA "E" "eBay"
"19859" "eBay收购TheGiftsProject 涉足社交商务市场" "资讯" "c(\"eBay\", \"交易\", \"TheGiftsProj\", \"社交商务\", \"ebay\")" NA "E" "eBay"
"19860" "eBay拟通过收购推动大中华区业务每年增长40%" "资讯" "c(\"腾讯\", \"收购\", \"ebay\", \"电子商务\", \"阿里巴巴\")" NA "E" "eBay"
"19861" "eBay犹他州模块化数据中心曝光" "资讯" "c(\"数据中心\", \"模块化\", \"ebay\", \"电子商务\", \"阿里巴巴\")" NA "E" "eBay"
"19862" "eBay完成收购开源电子商务平台Magento交易" "资讯" "c(\"平台\", \"腾讯\", \"ebay\", \"magento\", \"电子商务\")" NA "E" "eBay"
"19863" "eBay即时销售iOS应用让你随买随卖电子设备" "资讯" "c(\"手机\", \"电子商务\", \"ios应用\", \"ios\", \"ebay\")" NA "E" "eBay"
"19864" "eBay第二财季营收28.3亿美元 同比增长25%" "资讯" "c(\"网络\", \"产品\", \"腾讯\", \"电子商务\", \"ebay\")" NA "E" "eBay"
"19865" "eBay以2.4亿美元收购移动支付公司Zong" "资讯" "c(\"融资\", \"网络\", \"手机\", \"zong\", \"ebay\")" NA "E" "eBay"
"19866" "eBay的Turmeric和VJet的源程序移到了GitHub上" "资讯" "c(\"eBay\", \"Turmeric\", \"VJet\", \"GitHub\", \"ebay\")" NA "E" "eBay"
"19867" "eBay同GSI股东达成和解协议 收购本周内完成" "资讯" "c(\"腾讯\", \"ebay\", \"gsi\", \"电子商务\", \"网络\")" NA "E" "eBay"
"19868" "eBay完全收购电子商务平台Magento" "资讯" "c(\"电子商务\", \"ebay\", \"互联网\", \"平台\", \"magento\")" NA "E" "eBay"
"19869" "eBay一季度净利4.759亿美元 同比增长20%" "资讯" "c(\"2010\", \"ebay\", \"互联网\", \"平台\", \"magento\")" NA "E" "eBay"
"19870" "亚马逊与eBay财报前瞻：花钱争用户是否有回报" "资讯" "c(\"google\", \"电子商务\", \"亚马逊\", \"ebay\", \"财报\")" NA "E" "eBay"
"19871" "eBay将收购移动广告提供商WHERE" "资讯" "c(\"手机\", \"网络\", \"电子商务\", \"where\", \"ebay\")" NA "E" "eBay"
"19872" "eBay斥2亿美元收购德购物网站" "资讯" "c(\"活动\", \"ebay\", \"购物网站\", \"2010\", \"电子商务\")" NA "E" "eBay"
"19873" "eBay收购移动应用开发商Critical Path" "资讯" "c(\"手机\", \"互联网\", \"path\", \"移动\", \"ebay\")" NA "E" "eBay"
"19874" "eBay宣布收购本地化购物搜索引擎Milo" "资讯" "c(\"电子商务\", \"搜索引擎\", \"收购\", \"milo\", \"ebay\")" NA "E" "eBay"
"19875" "传eBay以7500万美元收购本地购物网站Milo" "资讯" "c(\"2010\", \"milo\", \"ebay\", \"milo\", \"ebay\")" NA "E" "eBay"
"19876" "eBay移动业务今年增长3倍 支付渠道成最大困扰" "资讯" "c(\"symbian\", \"ebay\", \"电子商务\", \"windows phon\", \"android\")" NA "E" "eBay"
"19877" "eBay四面楚歌 豪赌PayPal" "资讯" "c(\"电子商务\", \"paypal\", \"阿里巴巴\", \"ebay\", \"改版\")" NA "E" "eBay"
"19878" "Facebook市值超eBay 跻身美国第三大网络公司" "资讯" "c(\"网络\", \"网络公司\", \"平台\", \"ebay\", \"facebook\")" NA "E" "eBay"
"19879" "分析称Groupon难成下一个eBay" "资讯" "c(\"网络\", \"groupon\", \"产品\", \"电子商务\", \"ebay\")" NA "E" "eBay"
"19880" "iPhone程序今年将为eBay贡献15亿美元收入" "资讯" "c(\"手机\", \"电子商务\", \"ebay\", \"iphone\", \"ebay\")" NA "E" "eBay"
"19881" "砸烂最后一台服务器 eBay数据中心告别仪式揭秘" "资讯" "c(\"工作\", \"互联网\", \"数据中心\", \"ebay\", \"服务器\")" NA "E" "eBay"
"19882" "eBay和RIM联合发布适于黑莓手机的拍卖应用程序" "资讯" "c(\"应用程序\", \"RIM\", \"黑莓\", \"eBay\", \"服务器\")" NA "E" "eBay"
"19883" "API正在连接云中一切" "资讯" "c(\"云计算\", \"API\", \"AWS\", \"Eucalyptus\", \"服务器\")" NA "E" "Eucalyptus"
"19884" "OpenStack、OpenNebula、Eucalyptus、CloudStack社区活跃度比较" "资讯" "c(\"OpenStack\", \"CloudStack\", \"Eucalyptus\", \"OpenNebula\", \"云计算\")" NA "E" "Eucalyptus"
"19885" "AWS、VMware和OpenStack谁是赢家？" "资讯" "c(\"VMware\", \"OpenStack\", \"AWS\", \"云计算\", \"Eucalyptus\")" NA "E" "Eucalyptus"
"19886" "苏州园区开源云计算发展研讨会举行" "资讯" "c(\"OpenStack\", \"CloudStack\", \"Eucalyptus\", \"云计算\", \"Eucalyptus\")" NA "E" "Eucalyptus"
"19887" "Eucalyptus首席财务官王宁：有理想，就去追" "资讯" "c(\"Eucalyptus\", \"王宁\", \"《程序员》\", \"2013年3月刊\", \"Eucalyptus\")" NA "E" "Eucalyptus"
"19888" "以AWS和vCloud为标杆看四大开源平台的定位" "资讯" "c(\"数据中心\", \"云计算\", \"vmware\", \"AWS\", \"OpenStack\")" NA "E" "Eucalyptus"
"19889" "怎样用好Eucalyptus？" "资讯" "c(\"vmware\", \"AWS\", \"OpenStack\", \"CloudStack\", \"OpenNebula\")" NA "E" "Eucalyptus"
"19890" "四大开源云平台的命运基因" "资讯" "c(\"CloudStack\", \"OpenStack\", \"OpenNebula\", \"Eucalyptus\", \"开源云平台\")" NA "E" "Eucalyptus"
"19891" "云计算调查：PaaS未受青睐 OpenStack和GAE受欢迎" "资讯" "c(\"CloudStack\", \"Eucalyptus\", \"PaaS\", \"谷歌\", \"OpenStack\")" NA "E" "Eucalyptus"
"19892" "与Marten Mickos面对面：探索开源商业模式" "资讯" "c(\"MySQL\", \"Eucalyptus\", \"MartenMickos\", \"开源\", \"OpenStack\")" NA "E" "Eucalyptus"
"19893" "Rackspace HP启动OpenStack商用 真成熟了？" "资讯" "c(\"HP\", \"Rackspack\", \"云计算\", \"IaaS\", \"CloudStack\")" NA "E" "Eucalyptus"
"19894" "CloudStack、桉树加速开放 云平台格局渐显" "资讯" "c(\"OpenNebula\", \"Eucalyptus\", \"CloudStack\", \"IaaS\", \"云计算\")" NA "E" "Eucalyptus"
"19895" "OpenStack、桉树、vCloud Director对比" "资讯" "c(\"OpenStack\", \"开源\", \"云计算\", \"Eucalyptus\", \"CloudStack\")" NA "E" "Eucalyptus"
"19896" "2012Q2：四大开源IaaS社区活跃度对比" "资讯" "c(\"云计算\", \"IaaS\", \"CloudStack\", \"Eucalyptus\", \"OpenNebula\")" NA "E" "Eucalyptus"
"19897" "OpenStack供应商Eucalyptus版本升级 将全面开源" "资讯" "c(\"平台\", \"eucalyptus\", \"开源\", \"云计算平台\", \"云计算\")" NA "E" "Eucalyptus"
"19898" "四大巨头云策略：各领风骚" "资讯" "c(\"云策略\", \"红帽\", \"Eucalyptus\", \"VMware\", \"微软\")" NA "E" "Eucalyptus"
"19899" "jQuery开发俄罗斯方块小游戏源代码下载" "极客头条" "c(\"俄罗斯方块\", \"源代码\", \"jquery\", \"游戏\", \"微软\")" "springmvc_springdata" "E" "俄罗斯方块"
"19900" "史上最短小精悍的javascript编写的俄罗斯方块游戏，仅仅60行代码" "极客头条" "c(\"俄罗斯方块\", \"javascript\", \"游戏\", \"游戏\", \"微软\")" "yaerfeng" "E" "俄罗斯方块"
"19901" "HTML5简易版俄罗斯方块游戏" "极客头条" "c(\"俄罗斯方块\", \"html5\", \"css3\", \"游戏\", \"微软\")" "u013726302" "E" "俄罗斯方块"
"19902" "曾经的50大最好的科技产品——第二篇" "资讯" "c(\"科技产品\", \"俄罗斯方块\", \"Apple\", \"iPod\", \"微软\")" NA "E" "俄罗斯方块"
"19903" "10款最佳PC游戏：俄罗斯方块魔兽世界上榜" "资讯" "c(\"游戏\", \"最佳pc游戏\", \"魔兽世界\", \"俄罗斯方块\", \"微软\")" NA "E" "俄罗斯方块"
"19904" "俄罗斯方块25周年·未来有可能加入腾讯QQ" "资讯" "c(\"工作\", \"网络游戏\", \"休闲游戏\", \"腾讯\", \"俄罗斯方块\")" NA "E" "俄罗斯方块"
"19905" "最火搜索引擎：ElasticSearch详解与优化设计" "极客头条" "c(\"ElasticSearch\", \"搜索引擎\", \"休闲游戏\", \"腾讯\", \"俄罗斯方块\")" "sinat_33595594" "E" "ElasticSearch"
"19906" "Elastic 再次推出新工具：beats" "极客头条" "c(\"elasticsearch\", \"kibana\", \"logstash\", \"腾讯\", \"俄罗斯方块\")" "accesine960" "E" "ElasticSearch"
"19907" "利用Python进行Elasticsearch数据索引" "极客头条" "c(\"Python\", \"Elasticsearch\", \"logstash\", \"腾讯\", \"俄罗斯方块\")" "openskill" "E" "ElasticSearch"
"19908" "SQL for ElasticSearch–Crate.io安装配置和体验" "极客头条" "c(\"大数据\", \"elasticsearch\", \"crate\", \"sql\", \"俄罗斯方块\")" "lxw1234_com" "E" "ElasticSearch"
"19909" "使用ElasticSearch作为大数据平台的实时OLAP框架" "极客头条" "c(\"大数据\", \"elasticsearch\", \"olap\", \"sql\", \"俄罗斯方块\")" "lxw1234_com" "E" "ElasticSearch"
"19910" "使用Hive读写ElasticSearch中的数据" "极客头条" "c(\"大数据\", \"elasticsearch\", \"hive\", \"sql\", \"俄罗斯方块\")" "lxw1234_com" "E" "ElasticSearch"
"19911" "使用 Spring、Elasticsearch 及 Logstash 构建企业级数据搜索和分析平台" "极客头条" "c(\"Spring\", \"Elasticsearch\", \"Logstash\", \"sql\", \"俄罗斯方块\")" "u014664654" "E" "ElasticSearch"
"19912" "The Texas Tribune的Docker之旅" "资讯" "c(\"Docker\", \"image\", \"ElasticSearch\", \"Jenkins\", \"云计算\")" NA "E" "ElasticSearch"
"19913" "深入了解推荐引擎组件（基于Apache Mahout和Elasticsearch）" "资讯" "c(\"协同过滤算法\", \"推荐引擎\", \"elasticsearch\", \"Mahout\", \"机器学习\")" NA "E" "ElasticSearch"
"19914" "Java开发者值得关注的7款新工具" "资讯" "c(\"Java\", \"Plumbr\", \"Spark\", \"Elasticsearch\", \"Takipi\")" NA "E" "ElasticSearch"
"19915" "使用Mongo Connector和Elasticsearch实现模糊匹配" "资讯" "c(\"大数据\", \"NoSQL\", \"MongoDB\", \"Elasticsearch\", \"Takipi\")" NA "E" "ElasticSearch"
"19916" "开源大数据技术公司Elasticsearch获得7000万美元投资" "极客头条" "c(\"Elasticsearch\", \"大数据\", \"开源\", \"开源公司\", \"Takipi\")" "liujiangce" "E" "ElasticSearch"
"19917" "盘点Github所用的开源项目" "资讯" "c(\"开源项目\", \"编程语言\", \"web前端开发\", \"pjax\", \"Elasticsearch\")" NA "E" "ElasticSearch"
"19918" "盘点Github所用的开源项目" "资讯" "c(\"开源项目\", \"github\", \"开源\", \"Linguist\", \"pjax\")" NA "E" "ElasticSearch"
"19919" "GitHub怎么使用Elasticsearch" "极客头条" "c(\"Elasticsearch\", \"GitHub\", \"开源\", \"Linguist\", \"pjax\")" "jiangtao" "E" "ElasticSearch"
"19920" "ElasticSearch：一个基于Lucene构建的开源分布式RESTful搜索引擎" "极客头条" "c(\"搜索引擎\", \"开源\", \"分布式\", \"Lucene\", \"ElasticSearch\")" "mengyidan" "E" "ElasticSearch"
"19921" "【Cloud Edge第5期】开源搜索Elasticsearch：PB级数据的快速搜索 月下载量已达20万次" "资讯" "c(\"大数据\", \"初创公司\", \"Elasticsearch\", \"开源\", \"云先锋\")" NA "E" "ElasticSearch"
"19922" "Eclipse中Java工程UML图获取" "极客头条" "c(\"EClipse插件\", \"初创公司\", \"Elasticsearch\", \"开源\", \"云先锋\")" "wenwen091100304" "E" "Eclipse插件"
"19923" "Eclipse插件收藏列表（1）" "极客头条" "c(\"Eclipse插件\", \"初创公司\", \"Elasticsearch\", \"开源\", \"云先锋\")" "u011110579" "E" "Eclipse插件"
"19924" "Eclipse即将发布基于浏览器的IDE" "资讯" "c(\"javascript\", \"eclipse插件\", \"eclipse\", \"开发工具\", \"ide\")" NA "E" "Eclipse插件"
"19925" "Ceylon IDE首个里程碑版发布" "资讯" "c(\"hibernate\", \"ide\", \"语言\", \"eclipse插件\", \"ceylon\")" NA "E" "Eclipse插件"
"19926" "一周热闻回顾：10个最“优秀”的代码注释" "资讯" "c(\"eclipse插件\", \"网络应用\", \"虚拟机\", \"开发工具\", \"程序开发\")" NA "E" "Eclipse插件"
"19927" "Google开源其Eclipse插件" "资讯" "c(\"工具\", \"开发工具\", \"google\", \"开源\", \"eclipse插件\")" NA "E" "Eclipse插件"
"19928" "[观点]Scala很难" "资讯" "c(\"框架\", \"编程\", \"scala\", \"开发工具\", \"eclipse插件\")" NA "E" "Eclipse插件"
"19929" "打造一款Android联网tic-tac-toe游戏" "资讯" "c(\"android\", \"eclipse插件\", \"休闲游戏\", \"exception\", \"设计\")" NA "E" "Eclipse插件"
"19930" "四大Java云计算测评" "资讯" "c(\"云计算\", \"eclipse插件\", \"数据中心\", \"数据仓库\", \"java\")" NA "E" "Eclipse插件"
"19931" "微软插件为Java开发者在Azure开发提供便利" "资讯" "c(\"eclipse插件\", \"java\", \"微软\", \"microsoft\", \"azure\")" NA "E" "Eclipse插件"
"19932" "一个月内从零开始做webOS开发人员" "资讯" "c(\"浏览器\", \"webos\", \"语言\", \"web开发\", \"eclipse插件\")" NA "E" "Eclipse插件"
"19933" "推荐一些Linux下常用的软件" "资讯" "c(\"linux内核\", \"eclipse插件\", \"常用软件\", \"python开发工具\", \"linux\")" NA "E" "Eclipse插件"
"19934" "eBay开源SOA平台Turmeric" "资讯" "c(\"eclipse插件\", \"平台\", \"开源\", \"soa\", \"java\")" NA "E" "Eclipse插件"
"19935" "Java深度理解——Java字节代码的操纵" "资讯" "c(\"eclipse插件\", \"开源\", \"classloader\", \"编程语言\", \"java\")" NA "E" "Eclipse插件"
"19936" "Google与Spring合作推进云中的Java开发" "资讯" "c(\"google\", \"java\", \"eclipse插件\", \"web开发\", \"应用服务器\")" NA "E" "Eclipse插件"
"19937" "25个最佳最闪亮的Eclipse开发项目" "资讯" "c(\"http服务器\", \"eclipse\", \"java开发工具\", \"php开发工具\", \"eclipse插件\")" NA "E" "Eclipse插件"
"19938" "敏捷开发中编写高质量Java代码" "资讯" "c(\"开发工具\", \"代码分析\", \"eclipse插件\", \"java\", \"敏捷开发\")" NA "E" "Eclipse插件"
"19939" "盘点2009：Eclipse稳步前进" "资讯" "c(\"09盘点，eclipse\", \"thoughtworks\", \"eclipse插件\", \"eclipse\", \"移动开发\")" NA "E" "Eclipse插件"
"19940" "三星移动创新者园地将为JAVA开发者提供中文支持" "资讯" "c(\"java\", \"eclipse插件\", \"移动开发\", \"虚拟机\", \"三星\")" NA "E" "Eclipse插件"
"19941" "独家：专访Groovy Eclipse v2开发团队 分享Eclipse插件开发经验" "资讯" "c(\"工具\", \"开发工具\", \"groovy\", \"eclipse\", \"eclipse插件\")" NA "E" "Eclipse插件"
"19942" "独家：用于Java代码分析的Eclipse插件nWire 1.1发布" "资讯" "c(\"eclipse\", \"java\", \"代码分析\", \"编程\", \"eclipse插件\")" NA "E" "Eclipse插件"
"19943" "独家：新Eclipse插件—为Java 、PHP和Rails的应用添加云托管功能" "资讯" "c(\"rails\", \"java\", \"php\", \"eclipse插件\", \"eclipse\")" NA "E" "Eclipse插件"
"19944" "Evernote关闭3个办公室，裁员47人" "极客头条" "c(\"Evernote\", \"裁员\", \"php\", \"eclipse插件\", \"eclipse\")" "u012396362" "E" "Evernote"
"19945" "要与EverNote竞争？微软本月底将向Mac用户发布OneNote" "资讯" "c(\"Evernote\", \"微软\", \"OneNote\", \"Office\", \"Mac\")" NA "E" "Evernote"
"19946" "成功打造Evernote API生态系统的五大经验" "资讯" "c(\"evernote\", \"API\", \"用户体验\", \"可穿戴设备\", \"Mac\")" NA "E" "Evernote"
"19947" "把服务器搬进来：Splashtop在中国搭建Bridging Cloud" "资讯" "c(\"Splashtop\", \"Apple\", \"Evernote\", \"云计算\", \"开发经验\")" NA "E" "Evernote"
"19948" "Evernote推孵化器 不占股权" "资讯" "c(\"Evernote\", \"孵化器\", \"Devcup\", \"云计算\", \"开发经验\")" NA "E" "Evernote"
"19949" "一周消息树：谷歌推出云笔记产品Google Keep" "资讯" "c(\"一周消息树\", \"Google Keep\", \"Google\", \"EverNote\", \"Windows Phone\")" NA "E" "Evernote"
"19950" "剑指Evernote 谷歌正式推出Google Keep" "资讯" "c(\"Google Keep\", \"Google\", \"云笔记\", \"Evernote\", \"Windows Phone\")" NA "E" "Evernote"
"19951" "与EverNote竞争？谷歌Google Keep浮出水面" "资讯" "c(\"Google Keep\", \"Google\", \"云笔记\", \"Evernote\", \"Windows Phone\")" NA "E" "Evernote"
"19952" "Evernote更新Android SDK：“印象笔记”平台独立" "资讯" "c(\"Evernote\", \"印象笔记\", \"移动应用\", \"Android\", \"Windows Phone\")" NA "E" "Evernote"
"19953" "移动周报：不做内容，只钻技术的快播" "资讯" "c(\"移动周报\", \"快播\", \"智能电视\", \"微信\", \"Android\")" NA "E" "Evernote"
"19954" "Evernote遭到攻击，5000万用户密码重置" "资讯" "c(\"Evernote\", \"黑客\", \"安全\", \"微信\", \"Android\")" NA "E" "Evernote"
"19955" "Evernote正在与Apple联合开发硬件记忆工具，未来两年公司上市" "资讯" "c(\"苹果\", \"Moleskine\", \"Evernote\", \"微信\", \"Android\")" NA "E" "Evernote"
"19956" "中文版Evernote百宝箱上线：开发者海外推广新渠道" "资讯" "c(\"移动开发\", \"Evernote\", \"印象笔记\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"19957" "全新设计Evernote 5 Mac版即将发布" "资讯" "c(\"Evernote\", \"Evernote\", \"印象笔记\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"19958" "Evernote和台湾大哥大合作 进军台湾市场" "资讯" "c(\"台湾\", \"Evernote\", \"\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"19959" "Evernote推企业服务 开发智能笔记本" "资讯" "c(\"产品\", \"Evernote\", \"\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"19960" "舌尖上的Evernote：“食记”记录你所有的美食体验" "资讯" "c(\"生活\", \"android\", \"照片\", \"evernote\", \"产品\")" NA "E" "Evernote"
"19961" "海外App中国淘金三道坎：山寨、盈利和本土化" "资讯" "c(\"新浪微博\", \"中国移动\", \"数据中心\", \"evernote\", \"app\")" NA "E" "Evernote"
"19962" "海外巨头大举入华 国内移动开发者举步维艰" "资讯" "c(\"移动游戏\", \"手机操作系统\", \"移动开发\", \"移动互联网\", \"evernote\")" NA "E" "Evernote"
"19963" "大象的约会：专访Evernote CEO Phil Libin先生" "资讯" "c(\"Evernote\", \"CEO\", \"Phil\", \"Libin\", \"evernote\")" NA "E" "Evernote"
"19964" "命名“印象笔记” Evernote正式进军中国" "资讯" "c(\"工作\", \"服务器\", \"数据中心\", \"evernote\", \"印象笔记\")" NA "E" "Evernote"
"19965" "Evernote：Phil Libin打造的云笔记帝国" "资讯" "c(\"数据中心\", \"penultimate\", \"云笔记\", \"服务器\", \"evernote\")" NA "E" "Evernote"
"19966" "Evernote收购iPad手写应用Penultimate" "资讯" "c(\"数据中心\", \"penultimate\", \"云笔记\", \"跨平台\", \"evernote\")" NA "E" "Evernote"
"19967" "云笔记应用Evernote进军中国 欲建立数据中心" "资讯" "c(\"存储\", \"服务器\", \"数据中心\", \"云笔记\", \"evernote\")" NA "E" "Evernote"
"19968" "Evernote融资7000万美元 估值10亿进军中国市场" "资讯" "c(\"工作\", \"融资\", \"evernote\", \"云笔记\", \"云存储\")" NA "E" "Evernote"
"19969" "Evernote将进行第五轮融资 公司估值达10亿美元" "资讯" "c(\"windows phon\", \"blackberry\", \"融资\", \"云笔记\", \"evernote\")" NA "E" "Evernote"
"19970" "Evernote架构探析：为什么不用NoSQL？" "资讯" "c(\"服务器\", \"存储系统\", \"数据中心\", \"evernote\", \"nosql\")" NA "E" "Evernote"
"19971" "《近匠》专访小熊尼奥：从软硬结合到IP合作，AR产品的机遇" "资讯" "c(\"Qualcomm\", \"AR\", \"小熊尼奥\", \"儿童教育\", \"智能硬件\")" NA "E" "儿童教育"
"19972" "采集颜色、自动同步，还有比这更牛叉的儿童触控笔么？" "资讯" "c(\"Mozbii\", \"儿童教育\", \"智能硬件\", \"儿童教育\", \"智能硬件\")" NA "E" "儿童教育"
"19973" "寓教于乐  贝瓦依托移动平台打造中国式儿童“轻教育”" "资讯" "c(\"贝瓦\", \"王时光\", \"儿童应用\", \"移动互联网\", \"儿童教育\")" NA "E" "儿童教育"
"19974" "儿童教育类应用海外推广经验" "资讯" "c(\"教育\", \"互联网\", \"海外推广\", \"应用\", \"儿童教育\")" NA "E" "儿童教育"
"19975" "儿童教育类苹果iPad应用程序设计及开发" "资讯" "c(\"儿童教育\", \"移动开发\", \"教育\", \"ipad应用程序\", \"游戏\")" NA "E" "儿童教育"
"19976" "Email的模块化设计" "极客头条" "c(\"Email\", \"模块化\", \"设计\", \"ipad应用程序\", \"游戏\")" "pike0002" "E" "Email"
"19977" "Mutt —— 一个通过终端发送邮件的Email客户端" "极客头条" "c(\"邮件\", \"终端\", \"email\", \"ipad应用程序\", \"游戏\")" "u011109959" "E" "Email"
"19978" "44年Email服务迎来“第二春” 未来将更加个性化" "资讯" "c(\"邮件\", \"Email\", \"营销\", \"Facebook\", \"Mailbox\")" NA "E" "Email"
"19979" "Boss有可能正在监视你！ 藏？你早已无处可藏！" "资讯" "c(\"微软\", \"Facebook\", \"Yammer\", \"email\", \"Crane\")" NA "E" "Email"
"19980" "Clutch.io：iOS应开发者的动力加速器" "资讯" "c(\"web\", \"email\", \"ios\", \"clutch\", \"应用开发\")" NA "E" "Email"
"19981" "又一轮融资：社交化邮件管理插件Xobni受青睐" "资讯" "c(\"创业\", \"融资\", \"网络\", \"email\", \"xobni\")" NA "E" "Email"
"19982" "Facebook推出发送按钮 方便好友分享内容" "资讯" "c(\"email\", \"facebook\", \"电子商务\", \"产品\", \"last.fm\")" NA "E" "Email"
"19983" "亚马逊将推出面向企业用户的“Simple Email”服务" "资讯" "c(\"simple\", \"云计算\", \"互联网\", \"email\", \"亚马逊\")" NA "E" "Email"
"19984" "Facebook推Fmail挑战Email 62%受访者不考虑" "资讯" "c(\"互联网\", \"平台\", \"email\", \"fmail\", \"facebook\")" NA "E" "Email"
"19985" "微软发布Exchange 2010 RTM版" "资讯" "c(\"exchange2010\", \"发布\", \"功能\", \"email\", \"facebook\")" NA "E" "Email"
"19986" "苹果向开发者开放App Store资源中心" "资讯" "c(\"email\", \"公告\", \"测试\", \"iphone\", \"facebook\")" NA "E" "Email"
"19987" "微软发布Moodle插件 同样基于GPL v2" "资讯" "c(\"email\", \"linux\", \"教育\", \"日历\", \"虚拟化\")" NA "E" "Email"
"19988" "林锐博士“软件研发管理” 免费讲座" "资讯" "c(\"工具\", \"平台\", \"email\", \"电话\", \"项目管理\")" NA "E" "Email"
"19989" "瑞星播报：6日需警惕“IRC波特变种XAG”病毒" "资讯" "c(\"email\", \"网游\", \"service\", \"windows\", \"网络\")" NA "E" "Email"
"19990" "提高IE和Email的安全性的四步骤" "资讯" "c(\"windows\", \"工具\", \"服务器\", \"microsoft\", \"浏览器\")" NA "E" "Email"
"19991" "Unity生态圈将变？EA前总裁接替创始人任新CEO" "资讯" "c(\"Unity\", \"David Helgason\", \"EA\", \"John Riccitiello\", \"移动游戏\")" NA "E" "EA"
"19992" "EA，你是来拉仇恨的吗？" "资讯" "c(\"EA\", \"评价\", \"地下城守护者\", \"移动游戏\", \"Google Play\")" NA "E" "EA"
"19993" "看看你会几个？9大最火的移动开发技能" "资讯" "c(\"移动开发\", \"EA\", \"Java\", \".NET\", \"CSS\")" NA "E" "EA"
"19994" "植物大战僵尸2：“免费+内付费”模式引发争论" "资讯" "c(\"移动游戏\", \"植物大战僵尸\", \"EA\", \"免费增值模式\", \"PopCap\")" NA "E" "EA"
"19995" "时空旅行+内付费“植物大战僵尸2”下月18日全球同步发行！" "资讯" "c(\"植物大战僵尸\", \"PopCap\", \"EA\", \"移动游戏\", \"PopCap\")" NA "E" "EA"
"19996" "EA主宰iPhone游戏：前10位独占8席" "资讯" "c(\"2010\", \"平台\", \"游戏\", \"iphone\", \"ea\")" NA "E" "EA"
"19997" "EA美女副总裁跳槽 出任云游戏服务商战略官" "资讯" "c(\"平台\", \"游戏\", \"服务商\", \"跳槽\", \"ea\")" NA "E" "EA"
"19998" "EA在黑莓App World上推出8款游戏" "资讯" "c(\"应用程序\", \"RIM\", \"App World\", \"BlackBerry\", \"游戏\")" NA "E" "EA"
"19999" "传EA斥资2.5亿美元收购Facebook游戏开发商" "资讯" "c(\"playfish\", \"facebook\", \"收购\", \"游戏开发商\", \"ea\")" NA "E" "EA"
"20000" "暴雪称霸PC游戏销售榜 魔兽世界巫妖王之怒夺冠" "资讯" "c(\"魔兽世界\", \"activision\", \"fallout\", \"blizzard\", \"典藏版\")" NA "E" "EA"
"20001" "Evernote关闭3个办公室，裁员47人" "极客头条" "c(\"Evernote\", \"裁员\", \"fallout\", \"blizzard\", \"典藏版\")" "u012396362" "E" "Evernote"
"20002" "要与EverNote竞争？微软本月底将向Mac用户发布OneNote" "资讯" "c(\"Evernote\", \"微软\", \"OneNote\", \"Office\", \"Mac\")" NA "E" "Evernote"
"20003" "成功打造Evernote API生态系统的五大经验" "资讯" "c(\"evernote\", \"API\", \"用户体验\", \"可穿戴设备\", \"Mac\")" NA "E" "Evernote"
"20004" "把服务器搬进来：Splashtop在中国搭建Bridging Cloud" "资讯" "c(\"Splashtop\", \"Apple\", \"Evernote\", \"云计算\", \"开发经验\")" NA "E" "Evernote"
"20005" "Evernote推孵化器 不占股权" "资讯" "c(\"Evernote\", \"孵化器\", \"Devcup\", \"云计算\", \"开发经验\")" NA "E" "Evernote"
"20006" "一周消息树：谷歌推出云笔记产品Google Keep" "资讯" "c(\"一周消息树\", \"Google Keep\", \"Google\", \"EverNote\", \"Windows Phone\")" NA "E" "Evernote"
"20007" "剑指Evernote 谷歌正式推出Google Keep" "资讯" "c(\"Google Keep\", \"Google\", \"云笔记\", \"Evernote\", \"Windows Phone\")" NA "E" "Evernote"
"20008" "与EverNote竞争？谷歌Google Keep浮出水面" "资讯" "c(\"Google Keep\", \"Google\", \"云笔记\", \"Evernote\", \"Windows Phone\")" NA "E" "Evernote"
"20009" "Evernote更新Android SDK：“印象笔记”平台独立" "资讯" "c(\"Evernote\", \"印象笔记\", \"移动应用\", \"Android\", \"Windows Phone\")" NA "E" "Evernote"
"20010" "移动周报：不做内容，只钻技术的快播" "资讯" "c(\"移动周报\", \"快播\", \"智能电视\", \"微信\", \"Android\")" NA "E" "Evernote"
"20011" "Evernote遭到攻击，5000万用户密码重置" "资讯" "c(\"Evernote\", \"黑客\", \"安全\", \"微信\", \"Android\")" NA "E" "Evernote"
"20012" "Evernote正在与Apple联合开发硬件记忆工具，未来两年公司上市" "资讯" "c(\"苹果\", \"Moleskine\", \"Evernote\", \"微信\", \"Android\")" NA "E" "Evernote"
"20013" "中文版Evernote百宝箱上线：开发者海外推广新渠道" "资讯" "c(\"移动开发\", \"Evernote\", \"印象笔记\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"20014" "全新设计Evernote 5 Mac版即将发布" "资讯" "c(\"Evernote\", \"Evernote\", \"印象笔记\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"20015" "Evernote和台湾大哥大合作 进军台湾市场" "资讯" "c(\"台湾\", \"Evernote\", \"\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"20016" "Evernote推企业服务 开发智能笔记本" "资讯" "c(\"产品\", \"Evernote\", \"\", \"应用推广\", \"Android\")" NA "E" "Evernote"
"20017" "舌尖上的Evernote：“食记”记录你所有的美食体验" "资讯" "c(\"生活\", \"android\", \"照片\", \"evernote\", \"产品\")" NA "E" "Evernote"
"20018" "海外App中国淘金三道坎：山寨、盈利和本土化" "资讯" "c(\"新浪微博\", \"中国移动\", \"数据中心\", \"evernote\", \"app\")" NA "E" "Evernote"
"20019" "海外巨头大举入华 国内移动开发者举步维艰" "资讯" "c(\"移动游戏\", \"手机操作系统\", \"移动开发\", \"移动互联网\", \"evernote\")" NA "E" "Evernote"
"20020" "大象的约会：专访Evernote CEO Phil Libin先生" "资讯" "c(\"Evernote\", \"CEO\", \"Phil\", \"Libin\", \"evernote\")" NA "E" "Evernote"
"20021" "命名“印象笔记” Evernote正式进军中国" "资讯" "c(\"工作\", \"服务器\", \"数据中心\", \"evernote\", \"印象笔记\")" NA "E" "Evernote"
"20022" "Evernote：Phil Libin打造的云笔记帝国" "资讯" "c(\"数据中心\", \"penultimate\", \"云笔记\", \"服务器\", \"evernote\")" NA "E" "Evernote"
"20023" "Evernote收购iPad手写应用Penultimate" "资讯" "c(\"数据中心\", \"penultimate\", \"云笔记\", \"跨平台\", \"evernote\")" NA "E" "Evernote"
"20024" "云笔记应用Evernote进军中国 欲建立数据中心" "资讯" "c(\"存储\", \"服务器\", \"数据中心\", \"云笔记\", \"evernote\")" NA "E" "Evernote"
"20025" "Evernote融资7000万美元 估值10亿进军中国市场" "资讯" "c(\"工作\", \"融资\", \"evernote\", \"云笔记\", \"云存储\")" NA "E" "Evernote"
"20026" "Evernote将进行第五轮融资 公司估值达10亿美元" "资讯" "c(\"windows phon\", \"blackberry\", \"融资\", \"云笔记\", \"evernote\")" NA "E" "Evernote"
"20027" "Evernote架构探析：为什么不用NoSQL？" "资讯" "c(\"服务器\", \"存储系统\", \"数据中心\", \"evernote\", \"nosql\")" NA "E" "Evernote"
"20028" "面向WP和Android！微软车库发布多款免费应用" "资讯" "c(\"移动应用\", \"微软\", \"免费\", \"Android\", \"Windows Phone\")" NA "E" "Excel"
"20029" "Spread Studio 8 新特性：表格（Table）功能" "极客头条" "c(\"表格\", \"Excel\", \"免费\", \"Android\", \"Windows Phone\")" "powertoolsteam" "E" "Excel"
"20030" "《介绍一款开源的类Excel电子表格软件》续：七牛云存储实战（C#）" "极客头条" "c(\"云存储\", \"电子\", \"七牛\", \"软件\", \"开源\")" "powertoolsteam" "E" "Excel"
"20031" "如何读写Excel 电子表格" "极客头条" "c(\"电子\", \"excel\", \"七牛\", \"软件\", \"开源\")" "u011110579" "E" "Excel"
"20032" "最新版Chrome OS加入Word和Excel编辑功能 直指微软" "资讯" "c(\"Google\", \"Chrome OS \", \"微软\", \"Word\", \"Excel\")" NA "E" "Excel"
"20033" "【百度文库的开源实现】OpenOffice+swftools+PyODConverter+FlexPaper实现网页上展示Word、Excel、PPT、PDF等文档" "极客头条" "c(\"百度\", \"开源\", \"Excel\", \"OpenOffice\", \"Word\")" "jiangtao" "E" "Excel"
"20034" "Windows 8安装时间最短21分钟 只需点11次鼠标" "资讯" "c(\"文档\", \"excel\", \"微软\", \"windows\", \"安装时间\")" NA "E" "Excel"
"20035" "给程序员的Vim速查卡" "资讯" "c(\"vim\", \"excel\", \"速查卡\", \"windows\", \"安装时间\")" NA "E" "Excel"
"20036" "浅析微软Excel漏洞及解决方案" "资讯" "c(\"security\", \"互联网\", \"microsoft\", \"excel\", \"微软\")" NA "E" "Excel"
"20037" "微软发布超级计算机版Excel测试版本" "资讯" "c(\"任务\", \"工作\", \"编程\", \"excel\", \"微软\")" NA "E" "Excel"
"20038" "微软下月正式全面停售Office Accounting系列会计软件" "资讯" "c(\"excel\", \"产品\", \"微软\", \"microsoft\", \"office\")" NA "E" "Excel"
"20039" "微软网络版Office功能揭秘：Excel可多人协作" "资讯" "c(\"浏览器\", \"excel\", \"office\", \"网络\", \"微软\")" NA "E" "Excel"
"20040" "来自TechEd大会的Office 2010最新截图" "资讯" "c(\"截图\", \"office\", \"powerpoint\", \"outlook\", \"excel\")" NA "E" "Excel"
"20041" "用友应用平台 E-Cell“升级”微软Excel" "资讯" "c(\"用友\", \"E-cell\", \"微软\", \"Excel\", \"excel\")" NA "E" "Excel"
"20042" "微软IBM再起文档之争：Excel被指破坏ODF文件" "资讯" "c(\"工作\", \"excel\", \"ibm\", \"微软\", \"文档\")" NA "E" "Excel"
"20043" "微软:BI应为大众服务 Excel是很好的BI展示工具" "资讯" "c(\"bi商业智能\", \"excel\", \"微软\", \"bi\", \"数据挖掘\")" NA "E" "Excel"
"20044" "别再用Excel，ZK电子表格提供更棒的使用经验！" "资讯" "c(\"企业应用\", \"excel\", \"1.0\", \"spreadsheet\", \"zk电子表格\")" NA "E" "Excel"
"20045" "微软：本周三个安全更新 暂不会修正Excel漏洞" "资讯" "c(\"os\", \"windows\", \"excel\", \"微软\", \"zk电子表格\")" NA "E" "Excel"
"20046" "微软下周将发布三个补丁 仍有漏洞未修复" "资讯" "c(\"windows\", \"xp\", \"excel\", \"测试\", \"微软\")" NA "E" "Excel"
"20047" "RecoverPoint和VPLEX系统工程师谭强：高可用性环境的搭建" "资讯" "c(\"云计算\", \"云计算大会\", \"数据中心\", \"EMC\", \"EMC2013\")" NA "E" "EMC2013"
"20048" "EMC云计算事业部顾问崔大鹏：如何打造可信的大数据技术" "资讯" "c(\"云计算\", \"大数据\", \"EMC\", \"云计算大会\", \"崔大鹏\")" NA "E" "EMC2013"
"20049" "EMC解决方案集团大中华区总经理 卜晓军：实现应用程序转型" "资讯" "c(\"EMC\", \"卜晓军\", \"虚拟化\", \"云计算\", \"云计算大会\")" NA "E" "EMC2013"
"20050" "EMC合作伙伴销售经理杜术清：实现云的三种途径" "资讯" "c(\"EMC\", \"EMC2013\", \"云计算大会\", \"云计算\", \"数据中心\")" NA "E" "EMC2013"
"20051" "EMC企业存储产品部高级产品经理李君鹏：新一代 EMC将引领存储转型" "资讯" "c(\"EMC\", \"李君鹏\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC2013"
"20052" "EMC云和虚拟化数据中心咨询服务经理褚洪峰：新一代云应用程序可以增长700%" "资讯" "c(\"EMC\", \"褚洪峰\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC2013"
"20053" "京东商城副总裁兼首席科学家何刚：京东的云战略" "资讯" "c(\"京东商城\", \"何刚\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC2013"
"20054" "EMC李岩：数据爆棚下，如何去保护数据的有效和安全" "资讯" "c(\"云计算\", \"云计算大会\", \"EMC\", \"EMC2013\", \"李岩\")" NA "E" "EMC2013"
"20055" "EMC杨峰：凭借分析和存储解决方案，充分利用大数据" "资讯" "c(\"EMC2013\", \"大数据\", \"Hadoop\", \"云计算大会\", \"云计算\")" NA "E" "EMC2013"
"20056" "EMC数据计算事业部总经理刘伟光：大数据改变业务" "资讯" "c(\"EMC2013\", \"云计算大会\", \"大数据\", \"刘伟光\", \"云计算\")" NA "E" "EMC2013"
"20057" "Pivotal全球业务发展与策略副总裁David Menninger：揭秘Pivotal，新PaaS平台" "资讯" "c(\"pivotal\", \"云计算\", \"云计算大会\", \"EMC2013\", \"David Menninger\")" NA "E" "EMC2013"
"20058" "VMware全球研发高级副总裁范承工：移动/云时代的IT基础" "资讯" "c(\"VMware\", \"EMC\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "E" "EMC2013"
"20059" "EMC全球高级副总裁、大中华区总裁叶成辉：软件定义数据中心实现统一、开放的管理" "资讯" "c(\"EMC\", \"叶成辉\", \"云计算大会\", \"EMC2013\", \"云计算\")" NA "E" "EMC2013"
"20060" "EMC数据计算产品事业部刘琳：新一代PaaS平台前瞻" "资讯" "c(\"云计算\", \"大数据\", \"云计算大会\", \"EMC\", \"EMC2013\")" NA "E" "EMC2013"
"20061" "EMC在第五届中国云计算大会发布战略：EMC引领转型，软件定义存储" "资讯" "c(\"EMC2013\", \"EMC\", \"京东\", \"云计算\", \"云计算大会\")" NA "E" "EMC2013"
"20062" "十年IT灾难全面回顾和总结" "资讯" "c(\"IT\", \"Windows\", \"Oracle\", \"ERP\", \"项目管理\")" NA "E" "ERP"
"20063" "为什么企业偏爱开源？" "资讯" "c(\"开源\", \"企业\", \"开发者\", \"开源社区\", \"ERP\")" NA "E" "ERP"
"20064" "CloudFlare：为什么能从富达、谷歌、微软、百度和高通筹到1.1亿美元？" "资讯" "c(\"数据库\", \"SaaS\", \"ERP\", \"CRM\", \"SSL\")" NA "E" "ERP"
"20065" "SAP S/4HANA：唯一存储的是数据，数据精简90%" "资讯" "c(\"SAP\", \"HANA\", \"ERP\", \"S/4HANA\", \"Business Suite\")" NA "E" "ERP"
"20066" "专访阿朱：企业信息化的革命前夜" "资讯" "c(\"社区之星\", \"访谈\", \"阿朱\", \"吕建伟\", \"互联网\")" NA "E" "ERP"
"20067" "[观点]传统ERP的好日子没有了？" "资讯" "c(\"system\", \"产品\", \"互联网\", \"产品设计\", \"erp\")" NA "E" "ERP"
"20068" "肯塔基大学在戴尔最新云服务上测试ERP" "资讯" "c(\"肯塔基大学\", \"戴尔\", \"云服务\", \"ERP\", \"erp\")" NA "E" "ERP"
"20069" "微软高管揭秘五大发展计划 将推云ERP服务" "资讯" "c(\"微软\", \"发展计划\", \"音乐\", \"云计算\", \"erp\")" NA "E" "ERP"
"20070" "服务费渐长 未来ERP将走向免费？" "资讯" "c(\"工作\", \"产品\", \"技术人\", \"企业erp\", \"erp\")" NA "E" "ERP"
"20071" "寓教于乐  贝瓦依托移动平台打造中国式儿童“轻教育”" "资讯" "c(\"贝瓦\", \"王时光\", \"儿童应用\", \"移动互联网\", \"儿童教育\")" NA "E" "儿童应用"
"20072" "再培养一个扎克伯克：六款适合儿童上手编程的App" "资讯" "c(\"儿童应用\", \"JavaScript\", \"Ruby\", \"Scratch\", \"Alice\")" NA "E" "儿童应用"
"20073" "适合儿童上手的八款编程工具" "资讯" "c(\"游戏\", \"儿童编程\", \"Stencyl\", \"Khan Academy\", \"Scratch\")" NA "E" "儿童应用"
"20074" "影响一代人：海外儿童应用与童书应用实践" "资讯" "c(\"NosyCrow\", \"App\", \"Butterfield\", \"Wilson\", \"儿童应用\")" NA "E" "儿童应用"
"20075" "别只顾着山寨国外应用了 关注一下儿童应用市场吧！" "资讯" "c(\"活动\", \"互联网\", \"手机游戏\", \"儿童应用\", \"创业\")" NA "E" "儿童应用"
"20076" "ES6学习——Promises：应用示例" "极客头条" "c(\"promise\", \"ES6\", \"class\", \"javascript\", \"Symbol\")" "xmt1139057136" "E" "ES6"
"20077" "从CoffeeScript的角度看ES6中的新特性" "极客头条" "c(\"CoffeeScript\", \"ES6\", \"class\", \"javascript\", \"Symbol\")" "pingxu" "E" "ES6"
"20078" "ES6学习笔记" "极客头条" "c(\"es6\", \"javascript\", \"ECMAscript6\", \"javascript\", \"Symbol\")" "qq_16859463" "E" "ES6"
"20079" "ES6学习——类语法：继承中的原型链" "极客头条" "c(\"ES6\", \"javascript\", \"function\", \"class\", \"prototype\")" "xmt1139057136" "E" "ES6"
"20080" "ES6学习——新的语法：Symbol API介绍" "极客头条" "c(\"ES6\", \"javascript\", \"function\", \"Symbol\", \"prototype\")" "xmt1139057136" "E" "ES6"
"20081" "在gulp中使用ES6" "极客头条" "c(\"gulp\", \"es6\", \"function\", \"Symbol\", \"prototype\")" "sinat_30504589" "E" "ES6"
"20082" "深入浅出 ES6（十七）：展望未来" "极客头条" "c(\"前端\", \"JavaScript\", \"ES6\", \"Symbol\", \"prototype\")" "lenville" "E" "ES6"
"20083" "初步探究ES6之箭头函数" "极客头条" "c(\"函数\", \"javascript\", \"es6\", \"箭头函数\", \"prototype\")" "xmt1139057136" "E" "ES6"
"20084" "读懂 ECMAScript 规格" "极客头条" "c(\"ES6\", \"javascript\", \"es6\", \"箭头函数\", \"prototype\")" "whqet" "E" "ES6"
"20085" "初步探究ES6之let,const和块级作用域" "极客头条" "c(\"javascript\", \"函数\", \"es6\", \"箭头函数\", \"prototype\")" "xmt1139057136" "E" "ES6"
"20086" "ThinkJS 2.0：使用ES6/7全部特性开发Node项目" "资讯" "c(\"ES6\", \"ES7\", \"ThinkJS\", \"箭头函数\", \"prototype\")" NA "E" "ES6"
"20087" "ES6模拟布朗运动" "极客头条" "c(\"es6\", \"webpack\", \"canvas\", \"nodejs\", \"算法\")" "hedondev" "E" "ES6"
"20088" "Sublime Text 之运行 ES6 (基于babel)" "极客头条" "c(\"ES6\", \"webpack\", \"canvas\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20089" "深入浅出ES6（十二）：代理 Proxies" "极客头条" "c(\"ES6\", \"webpack\", \"canvas\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20090" "ES6 in modern developments" "极客头条" "c(\"前端\", \"开发\", \"ES6\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20091" "ECMAScript 6 模块架构" "极客头条" "c(\"ES6\", \"模块\", \"ES6\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20092" "ES5, ES6, ES2016, ES.Next: JavaScript 的版本是怎么回事？（译文）" "极客头条" "c(\"ES6\", \"JS\", \"javascript\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20093" "ECMAScript 6不完全教程" "极客头条" "c(\"ES6\", \"javascript\", \"javascript\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20094" "深入浅出ES6（十）：集合" "极客头条" "c(\"ES6\", \"javascript\", \"javascript\", \"nodejs\", \"算法\")" "whqet" "E" "ES6"
"20095" "升级到Node V4的七个理由  支持大量ES6特性" "资讯" "c(\"Node v4\", \"ES6\", \"Node\", \"nodejs\", \"算法\")" NA "E" "ES6"
"20096" "【探秘ES6】系列专栏（十二）：类语法let和const" "资讯" "c(\"ES6\", \"开发者\", \"Node\", \"nodejs\", \"算法\")" NA "E" "ES6"
"20097" "【探秘ES6】系列专栏（十一）：类语法" "资讯" "c(\"探秘ES6\", \"ES6\", \"JavaScript\", \"Web开发\", \"算法\")" NA "E" "ES6"
"20098" "【探秘ES6】系列专栏（十）：更深入了解生成器" "资讯" "c(\"探秘ES6\", \"ES6\", \"JavaScript\", \"Web开发\", \"算法\")" NA "E" "ES6"
"20099" "【探秘ES6】系列专栏（九）：使用Babel和Broccoli" "资讯" "c(\"探秘ES6\", \"ES6\", \"JavaScript\", \"Web开发\", \"算法\")" NA "E" "ES6"
"20100" "TypeScript 1.5发布，支持大量ES6新特性" "资讯" "c(\"visual studio\", \"javascript\", \"ES6\", \"TypeScript 1.5\", \"算法\")" NA "E" "ES6"
"20101" "【探秘ES6】系列专栏（八）：JS的第七种基本类型Symbols" "资讯" "c(\"探秘ES6\", \"ES6\", \"Web开发\", \"JavaScript\", \"算法\")" NA "E" "ES6"
"20102" "【探秘ES6】系列专栏（七）：箭头函数" "资讯" "c(\"探秘ES6\", \"ES6\", \"Web开发\", \"JavaScript\", \"算法\")" NA "E" "ES6"
"20103" "【探秘ES6】系列专栏（六）：解构赋值" "资讯" "c(\"探秘ES6\", \"ES6\", \"Web开发\", \"JavaScript\", \"算法\")" NA "E" "ES6"
"20104" "探秘ES6系列专栏：剩余参数和默认参数" "极客头条" "c(\"ES6\", \"JavaScript\", \"Web开发\", \"JavaScript\", \"算法\")" "chenqiuge1984" "E" "ES6"
"20105" "【探秘ES6】系列专栏（五）：剩余参数和默认参数" "资讯" "c(\"ES6\", \"JavaScript\", \"Web开发\", \"探秘ES6\", \"算法\")" NA "E" "ES6"
"20106" "【探秘ES6】系列专栏（四）：模版字符串" "资讯" "c(\"Web开发\", \"ES6\", \"JavaScript\", \"探秘ES6\", \"算法\")" NA "E" "ES6"
"20107" "【探秘ES6】系列专栏（三）：生成器" "资讯" "c(\"Web开发\", \"JavaScript\", \"ES6\", \"探秘ES6\", \"算法\")" NA "E" "ES6"
"20108" "【探秘ES6】系列专栏（二）：迭代器和for-of循环" "资讯" "c(\"Web开发\", \"ES6\", \"JavaScript\", \"探秘ES6\", \"算法\")" NA "E" "ES6"
"20109" "【探秘ES6】系列专栏（一）：ES6简介" "资讯" "c(\"Web开发\", \"Javascript\", \"ES6\", \"探秘ES6\", \"算法\")" NA "E" "ES6"
"20110" "基于ES6，使用React、Webpack、Babel构建模块化JavaScript应用" "资讯" "c(\"JavaScript\", \"ES6\", \"React\", \"探秘ES6\", \"算法\")" NA "E" "ES6"
"20111" "【ES6专栏】全面解析ECMAScript 6模块系统" "资讯" "c(\"JavaScript\", \"ECMAScript 6\", \"模块化\", \"ES6\", \"算法\")" NA "E" "ES6"
"20112" "《二战风云》发布至今，已为顽石互动狂赚2.7亿" "资讯" "c(\"二战风云\", \"吴刚\", \"顽石互动\", \"移动游戏\", \"推广盈利\")" NA "E" "二战风云"
"20113" "9家在iOS平台上收入最高的中国公司" "资讯" "c(\"iOS\", \"二战风云\", \"斗地主\", \"盈利\", \"移动开发\")" NA "E" "二战风云"
"20114" "TOP30移动大抉择之二战风云：日收入6万美元的移动游戏" "资讯" "c(\"中国移动\", \"移动游戏\", \"top30\", \"吴刚\", \"二战风云\")" NA "E" "二战风云"
"20115" "专访Esri中国区技术总监：打造新一代WebGIS平台" "资讯" "c(\"esri\", \"GIS\", \"地理信息服务\", \"html5\", \"WebGIS\")" NA "E" "Esri"
"20116" "专访陈抒：C++至今不可替代" "资讯" "c(\"社区之星\", \"Esri\", \"C++\", \"访谈\", \"WebGIS\")" NA "E" "Esri"
"20117" "Esri王昊：ArcGIS Online将在中国落地" "资讯" "c(\"GIS\", \"Esri\", \"C++\", \"访谈\", \"WebGIS\")" NA "E" "Esri"
"20118" "2012 Esri中国开发者大会在京召开" "资讯" "c(\"互联网\", \"javascript\", \"web开发\", \"esri\", \"敏捷开发\")" NA "E" "Esri"
"20119" "Esri中国区域用户大会开幕 “GIS之父”精彩演讲引发高潮(现场组图)" "资讯" "c(\"教育\", \"产品\", \"互联网\", \"gis\", \"esri\")" NA "E" "Esri"
"20120" "高德软件推出在线地图服务新模式" "资讯" "c(\"平台\", \"服务器\", \"互联网\", \"esri\", \"高德软件\")" NA "E" "Esri"
"20121" "ArcGIS全面支持iPhone操作系统" "资讯" "c(\"服务器\", \"esri\", \"iphone\", \"gis平台\", \"网络\")" NA "E" "Esri"
"20122" "《一周开源弹》02期：COS系统不是杂种，XP退场是美国衰落？！" "资讯" "c(\"开源\", \"手机操作系统\", \"搜狗输入法\", \"eric raymond\", \"开源社区\")" NA "E" "Eric Raymond"
"20123" "带你走进Erlang（入门篇）" "资讯" "c(\"Erlang\", \"编程语言\", \"函数式编程\", \"eric raymond\", \"开源社区\")" NA "E" "Erlang"
"20124" "为何9亿用户的WhatsApp，只需50名工程师？" "极客头条" "c(\"开发\", \"代码\", \"Erlang\", \"Whatsapp\", \"开源社区\")" "chihyin" "E" "Erlang"
"20125" "为何WhatsApp能用50名工程师服务9亿用户（英）" "极客头条" "c(\"WhatsApp\", \"Erlang\", \"架构\", \"Whatsapp\", \"开源社区\")" "u010415101" "E" "Erlang"
"20126" "【七问七答】对话Erlang核心成员Eric Merritt" "资讯" "c(\"Erlang\", \"软件工程师\", \"Eric Merritt\", \"编程语言\", \"开源社区\")" NA "E" "Erlang"
"20127" "rebar 热更 Erlang 代码实践" "极客头条" "c(\"Erlang\", \"软件工程师\", \"Eric Merritt\", \"编程语言\", \"开源社区\")" "u012607712" "E" "Erlang"
"20128" "Erlang 内存泄漏分析" "极客头条" "c(\"内存泄漏\", \"Erlang\", \"Eric Merritt\", \"编程语言\", \"开源社区\")" "qiansg123" "E" "Erlang"
"20129" "Erlang 真的很好！" "极客头条" "c(\"Erlang\", \"Erlang\", \"Eric Merritt\", \"编程语言\", \"开源社区\")" "xx7667240" "E" "Erlang"
"20130" "Erlang 开发者的福音：IntelliJ IDEA 的 Erlang 插件" "极客头条" "c(\"intellij idea\", \"开发者\", \"erlang\", \"插件\", \"开源社区\")" "u011106205" "E" "Erlang"
"20131" "有关GO和Erlang的一些思考" "极客头条" "c(\"erlang\", \"go\", \"erlang\", \"插件\", \"开源社区\")" "c2u" "E" "Erlang"
"20132" "日600亿消息，月4.65亿用户——WhatsApp的Erlang世界" "资讯" "c(\"云计算\", \"数据中心\", \"WhatsApp\", \"Erlang\", \"开源社区\")" NA "E" "Erlang"
"20133" "Recon-Erlang线上系统诊断工具" "极客头条" "c(\"erlang\", \"数据中心\", \"WhatsApp\", \"Erlang\", \"开源社区\")" "linxiyu52" "E" "Erlang"
"20134" "为什么Facebook Chat用Erlang开发？" "极客头条" "c(\"facebook\", \"erlang\", \"WhatsApp\", \"Erlang\", \"开源社区\")" "pike0002" "E" "Erlang"
"20135" "价值190亿的Whatsapp背后：每天用Erlang处理500亿条信息" "极客头条" "c(\"erlang\", \"whatsapp\", \"WhatsApp\", \"Erlang\", \"开源社区\")" "tanmao_xx" "E" "Erlang"
"20136" "Erlang语言重大变更:记录(Record)已死，映射(Map)当立" "极客头条" "c(\"erlang\", \"语言\", \"map\", \"record\", \"开源社区\")" "u010415101" "E" "Erlang"
"20137" "Quasar与Pulsar：将Erlang和Go里酷酷的Actor特性引入JVM" "极客头条" "c(\"Go\", \"Erlang\", \"JVM\", \"record\", \"开源社区\")" "liujiangce" "E" "Erlang"
"20138" "修改驱动，使用Erlang+VoltDB实现每秒87.7万事务" "资讯" "c(\"EC2\", \"Erlang\", \"事务\", \"服务器\", \"集群\")" NA "E" "Erlang"
"20139" "“好奇号”火星车和它搭载的软件" "资讯" "c(\"Erlang\", \"编程语言\", \"C\", \"服务器\", \"集群\")" NA "E" "Erlang"
"20140" "[观点]减少代码嵌套" "资讯" "c(\"测试\", \"erlang\", \"代码\", \"工作\", \"数据库\")" NA "E" "Erlang"
"20141" "Erlang之父教你如何入手" "资讯" "c(\"语言\", \"编译器\", \"erlang\", \"文本编辑\", \"开发工具\")" NA "E" "Erlang"
"20142" "Couchbase 2.0性能将大幅提升" "资讯" "c(\"erlang\", \"测试工具\", \"couchbase\", \"couchdb\", \"文档\")" NA "E" "Erlang"
"20143" "7 种正在崛起的程序语言" "资讯" "c(\"erlang\", \"matlab\", \"python\", \"javascript\", \"数据分析\")" NA "E" "Erlang"
