"89168" "Stack based vs Register based Virtual Machine Architecture" "极客头条" "c(\"操作系统\", \"jvm\", \"java\", \"vmware\", \"虚拟机\")" "xmt1139057136" "V" "VMware"
"89169" "VMware任道远：迎接软件定义新时代" "资讯" "c(\"云计算\", \"大数据\", \"VMware\", \"Cloud Foundry\", \"Docker\")" NA "V" "VMware"
"89170" "Google寄望VMware联合创始人协助冲击企业云计算市场" "资讯" "c(\"Google\", \"Android\", \"VMware\", \"Bebop团队\", \"云计算平台\")" NA "V" "VMware"
"89171" "VMware ESXi自动化部署实践" "极客头条" "c(\"vmware\", \"esxi\", \"自动化\", \"Bebop团队\", \"云计算平台\")" "wsgzao" "V" "VMware"
"89172" "盘点VMWorld 2015发布的最重要的6项技术" "极客头条" "c(\"vmworld\", \"vmware\", \"自动化\", \"Bebop团队\", \"云计算平台\")" "cristinana" "V" "VMware"
"89173" "传闻成真：戴尔收购了EMC公司" "资讯" "c(\"云计算\", \"VMware\", \"EMC\", \"混合云\", \"云计算平台\")" NA "V" "VMware"
"89174" "下一代软件定义安全SDS白皮书发布 可为相关从业者提供理论支撑" "资讯" "c(\"云计算\", \"OpenStack\", \"VMware\", \"IaaS\", \"云计算平台\")" NA "V" "VMware"
"89175" "双管齐下，VMware的容器新战略" "极客头条" "c(\"图片\", \"vmware\", \"容器\", \"IaaS\", \"云计算平台\")" "mrex326428" "V" "VMware"
"89176" "ZeroStack从后台帮助企业控制简化私有云" "资讯" "c(\"OpenStack\", \"云计算\", \"VMware\", \"私有云\", \"SaaS\")" NA "V" "VMware"
"89177" "苏宁张小斌：OpenStack实践基础知识（一）" "资讯" "c(\"OpenStack\", \"开源IaaS\", \"CloudStack\", \"VMware\", \"KVM\")" NA "V" "VMware"
"89178" "第七届中国云计算大会混合云应用与实践论坛：混合云的优势与应用" "资讯" "c(\"CCCC2015\", \"混合云\", \"中国电信\", \"VMware\", \"计世资讯\")" NA "V" "VMware"
"89179" "为何走上OpenStack不归路？Monty Taylor、Dan Wendlandt领衔13位大牛等你切磋！" "资讯" "c(\"开源软件\", \"OpenStack\", \"Docker\", \"OpenStack技术大会\", \"2015 OpenCloud\")" NA "V" "VMware"
"89180" "VMware和Docker的双城记" "资讯" "c(\"Docker\", \"容器\", \"虚拟化\", \"VMware\", \"2015 OpenCloud\")" NA "V" "VMware"
"89181" "VMware大中华区技术总监何英华：2015年云计算趋势为SDDC、混合云、移动化交付" "资讯" "c(\"云计算\", \"VMware\", \"数据中心\", \"混合云\", \"2015 OpenCloud\")" NA "V" "VMware"
"89182" "演化的数据中心安全：趋势科技聚焦APT防御和虚拟化安全" "资讯" "c(\"趋势科技\", \"虚拟化\", \"安全\", \"VMware\", \"2015 OpenCloud\")" NA "V" "VMware"
"89183" "让Windows无缝地跑在Mac上，VMware发布VMware Fusion 7" "资讯" "c(\"虚拟化\", \"VMware\", \"操作系统\", \"Mac\", \"2015 OpenCloud\")" NA "V" "VMware"
"89184" "VMware VSAN、VSA和外部存储阵列" "极客头条" "c(\"vmware\", \"存储\", \"操作系统\", \"Mac\", \"2015 OpenCloud\")" "cristinana" "V" "VMware"
"89185" "VMware李映：10亿注资在华怎么花" "资讯" "c(\"VMware\", \"开源\", \"虚拟化\", \"Mac\", \"2015 OpenCloud\")" NA "V" "VMware"
"89186" "VMware vSphere 5.5零基础入门系列（二）：VMware vSphere Client简介及安装演示" "极客头条" "c(\"vmware\", \"vsphere\", \"虚拟化\", \"Mac\", \"2015 OpenCloud\")" "cristinana" "V" "VMware"
"89187" "VMware vSphere 5.5零基础入门系列（一）：ESXi简介及安装" "极客头条" "c(\"VMware\", \"vSphere\", \"虚拟化\", \"Mac\", \"2015 OpenCloud\")" "cristinana" "V" "VMware"
"89188" "Docker实践者不能错过2014 Container技术大会的九大理由！（讲师议题全面揭晓）" "资讯" "c(\"con2\", \"Docker\", \"Container\", \"Google\", \"红帽\")" NA "V" "VMware"
"89189" "【Container讲师】喻勇：Container技术在Cloud Foundry中的应用和演化" "资讯" "c(\"vmware\", \"docker\", \"con2\", \"PaaS\", \"云计算平台\")" NA "V" "VMware"
"89190" "Docker周报：VMware携手Docker" "极客头条" "c(\"vmware\", \"Docker\", \"con2\", \"PaaS\", \"云计算平台\")" "u010702509" "V" "VMware"
"89191" "VMware vCloud Hybrid Service混合云解决方案" "极客头条" "c(\"解决方案\", \"混合云\", \"vmware\", \"Hybrid\", \"云计算平台\")" "cristinana" "V" "VMware"
"89192" "大步向中国混合云领域迈进—专访VMware任道远" "资讯" "c(\"混合云\", \"vmware\", \"vmware\", \"Hybrid\", \"云计算平台\")" NA "V" "VMware"
"89193" "对比ScaleIO和VMware的VSAN技术(上)" "极客头条" "c(\"vmware\", \"ScaleIO\", \"vmware\", \"Hybrid\", \"云计算平台\")" "u014480367" "V" "VMware"
"89194" "AWS发布面向vCenter的管理门户 与VMware争夺云端市场" "资讯" "c(\"AWS\", \"vmware\", \"数据中心\", \"公有云\", \"私有云\")" NA "V" "VMware"
"89195" "【观察】从阿里招股书看四年阿里云数据及与AWS、VMware的对比" "资讯" "c(\"阿里云\", \"IBM\", \"AWS\", \"观察\", \"VMware\")" NA "V" "VMware"
"89196" "VMware vSphere基础知识精要（上）" "极客头条" "c(\"vsphere\", \"vmware\", \"AWS\", \"观察\", \"VMware\")" "u014480367" "V" "VMware"
"89197" "云计算战争：OpenStack vs. VMware" "资讯" "c(\"云计算\", \"OpenStack\", \"VMware\", \"观察\", \"VMware\")" NA "V" "VMware"
"89198" "云计算战争：OpenStack vs VMware" "极客头条" "c(\"Openstack\", \"云计算\", \"Vmware\", \"观察\", \"VMware\")" "linxiyu52" "V" "VMware"
"89199" "VMware 产品及功能概述" "极客头条" "c(\"vmware\", \"产品\", \"Vmware\", \"观察\", \"VMware\")" "u014480367" "V" "VMware"
"89200" "集成GemFire，Hadoop生态圈的又一把火" "资讯" "c(\"大数据\", \"Hadoop\", \"Pivotal\", \"EMC\", \"VMware\")" NA "V" "VMware"
"89201" "任道远上任VMware中国研发中心总经理" "资讯" "c(\"虚拟化\", \"云计算\", \"基础架构\", \"VMware\", \"VMware\")" NA "V" "VMware"
"89202" "谷歌、VMware在Chromebooks上双赢了，微软你怎么看？" "资讯" "c(\"云计算\", \"Google\", \"VMware\", \"AWS\", \"DaaS\")" NA "V" "VMware"
"89203" "微软得小心了！谷歌与VMware合作推动Chrome OS上使用Windows应用" "资讯" "c(\"微软\", \"Google\", \"移动操作系统\", \"Horizon DaaS\", \"虚拟化\")" NA "V" "VMware"
"89204" "高薪利器：四大热门云计算认证推荐" "资讯" "c(\"云计算\", \"认证\", \"IBM\", \"VMware\", \"虚拟化\")" NA "V" "VMware"
"89205" "Pivotal聘用eBay前副总裁，继续发力云计算市场" "资讯" "c(\"云计算\", \"EMC\", \"VMware\", \"Pivotal\", \"Hugh E. Williams\")" NA "V" "VMware"
"89206" "VMware推出vCloud Suite及vSphere新版：可用性及性能双丰收" "资讯" "c(\"大数据\", \"EMC\", \"VMware\", \"数据中心\", \"SDN\")" NA "V" "VMware"
"89207" "VMware、红帽对决云管理平台" "资讯" "c(\"混合云\", \"数据中心\", \"Red Hat\", \"OpenStack\", \"VMware\")" NA "V" "VMware"
"89208" "EMC全球营销CTO转投VMware" "资讯" "c(\"EMC\", \"CTO\", \"VMware\", \"Chuck Hollis\", \"人物\")" NA "V" "VMware"
"89209" "一周观察：Cloud Foundry生态圈渐成型" "资讯" "c(\"Cloud Foundry\", \"VMware\", \"Pivotal\", \"京东商城\", \"网易\")" NA "V" "VMware"
"89210" "开源平台Cloud Foundry获IBM支持" "资讯" "c(\"Cloud Foundry\", \"Pivotal\", \"IBM\", \"百度\", \"VMware\")" NA "V" "VMware"
"89211" "VMware与SAP共同推出基于VMware云基础架构的SAP解决方案服务" "资讯" "c(\"VMware\", \"SAP\", \"基础架构\", \"应用\", \"解决方案\")" NA "V" "VMware"
"89212" "VMware全球研发高级副总裁范承工：移动/云时代的IT基础" "资讯" "c(\"VMware\", \"EMC\", \"云计算\", \"云计算大会\", \"EMC2013\")" NA "V" "VMware"
"89213" "Pivotal获通用电气1.05亿美元支持 或将改变大数据和物联网的游戏规则" "资讯" "c(\"VMware\", \"EMC\", \"Pivotal\", \"云先锋\", \"PaaS\")" NA "V" "VMware"
"89214" "OpenStack将怎样影响软件行业？" "资讯" "c(\"OpenStack\", \"VMware\", \"服务器\", \"花旗银行\", \"程辉\")" NA "V" "VMware"
"89215" "Pivotal宣布成立 EMC、VMware、通用电气铁三角组合正式起航" "资讯" "c(\"Pivotal\", \"Greenplum\", \"Cloud Foundry\", \"VMware\", \"EMC\")" NA "V" "VMware"
"89216" "7个大数据流言——避免错误的Hadoop和云分析决策" "资讯" "c(\"云计算\", \"大数据\", \"Hadoop\", \"VMware\", \"虚拟化\")" NA "V" "VMware"
"89217" "AWS、VMware和OpenStack谁是赢家？" "资讯" "c(\"VMware\", \"OpenStack\", \"AWS\", \"云计算\", \"Eucalyptus\")" NA "V" "VMware"
"89218" "paypal和ebay的80000台服务器将用openstack替代vmware" "极客头条" "c(\"服务器\", \"OpenStack\", \"eBay\", \"PayPal\", \"VMware\")" "baozi0" "V" "VMware"
"89219" "VMware携手亿阳信通 铺垫混合服务" "资讯" "c(\"VMware\", \"混合云\", \"云计算\", \"AWS\", \"OpenStack\")" NA "V" "VMware"
"89220" "VMware/Oracle向公有云拓展生态系统" "资讯" "c(\"VMware\", \"Oracle\", \"Nimbula\", \"云计算\", \"AWS\")" NA "V" "VMware"
"89221" "VMware发布Horizon Suite 三款应用打包折扣低" "资讯" "c(\"VMware\", \"VDI\", \"Horizon Suite\", \"云计算\", \"AWS\")" NA "V" "VMware"
"89222" "EMC中国凭什么说营收5年再增5倍？" "资讯" "c(\"emc\", \"greenplum\", \"vmware\", \"云计算\", \"大数据\")" NA "V" "VMware"
"89223" "Cloud Foundry面临代码分支" "资讯" "c(\"vmware\", \"PaaS\", \"Cloud Foundry\", \"Pivotal Initiative\", \"代码分支\")" NA "V" "VMware"
"89224" "以AWS和vCloud为标杆看四大开源平台的定位" "资讯" "c(\"数据中心\", \"云计算\", \"vmware\", \"AWS\", \"OpenStack\")" NA "V" "VMware"
"89225" "怎样用好Eucalyptus？" "资讯" "c(\"vmware\", \"AWS\", \"OpenStack\", \"CloudStack\", \"OpenNebula\")" NA "V" "VMware"
"89226" "最佳员工移动平台：VMware Horizon Suite" "资讯" "c(\"VMware\", \"虚拟化\", \"终端\", \"跨平台\", \"VMwareHorizon\")" NA "V" "VMware"
"89227" "一周云事件：亚马逊对消费者的吸引力超过苹果" "资讯" "c(\"Cloud Foundry\", \"亚马逊\", \"NTT\", \"VMware\", \"VMwareHorizon\")" NA "V" "VMware"
"89228" "VMware掌控Puppet 老用户会被锁定吗？" "资讯" "c(\"vmware\", \"运维\", \"chef\", \" puppet\", \"VMwareHorizon\")" NA "V" "VMware"
"89229" "VMware严控ESXi API 引发用户和ISV被绑架担忧" "资讯" "c(\"vmware\", \"api\", \"dell\", \"OpenStack\", \"易思捷\")" NA "V" "VMware"
"89230" "VMware CTO Steve Herrod离职 加盟风险投资公司" "资讯" "c(\"VMware\", \"人物\", \"职场\", \"SteveHerrod\", \"易思捷\")" NA "V" "VMware"
"89231" "PaaS玩家们，怎么演好自己的角色？" "资讯" "c(\"PaaS\", \"VMware\", \"CloudFoundry\", \"用友\", \"易思捷\")" NA "V" "VMware"
"89232" "HBTC精彩回顾 Hadoop专家分享大数据技术工具与最佳实践" "资讯" "c(\"网易\", \"阿里巴巴\", \"Hortonworks\", \"腾讯\", \"IBM\")" NA "V" "VMware"
"89233" "VMware最快下周宣布分拆Cloud Foundry" "资讯" "c(\"VMware\", \"PaaS\", \"CloudFoundry\", \"EMC\", \"IBM\")" NA "V" "VMware"
"89234" "2012vForum：更加注重开发者" "资讯" "c(\"vForum\", \"数据中心\", \"VMware\", \"虚拟化\", \"IBM\")" NA "V" "VMware"
"89235" "大牛云集 SpringOne大会首次落户中国" "资讯" "c(\"VMware\", \"CloudFoundry\", \"SpringOne\", \"Spring\", \"SpringSource\")" NA "V" "VMware"
"89236" "Apple、VMware组团狙杀Microsoft Office！" "资讯" "c(\"Microsoft\", \"Office\", \"VMware\", \"Apple\", \"SpringSource\")" NA "V" "VMware"
"89237" "OpenStack基金会正式成立 VMware敌友难辨？" "资讯" "c(\"OpenStack\", \"VMware\", \"VMware\", \"Apple\", \"SpringSource\")" NA "V" "VMware"
"89238" "VMware、Intel、NEC成为OpenStack基金会金牌会员" "资讯" "c(\"Intel\", \"NEC\", \"VMware\", \"OpenStack\", \"SpringSource\")" NA "V" "VMware"
"89239" "VMware加入OpenStack究竟意味着什么？" "资讯" "c(\"VMware\", \"OpenStack\", \"VMware\", \"OpenStack\", \"SpringSource\")" NA "V" "VMware"
"89240" "云计算如何更好的提高资源利用率" "资讯" "c(\"公有云\", \"私有云\", \"OpenStack\", \"AWS\", \"VMware\")" NA "V" "VMware"
"89241" "云计算一周热文回顾：一点万亿的谷歌数据分析" "资讯" "c(\"云热点\", \"谷歌\", \"Hadoop\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89242" "浅谈Google与VMware十年辉煌背后的人才战略" "资讯" "c(\"VMware\", \"Google\", \"人才\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89243" "浅解VMware加入OpenStack的原因" "资讯" "c(\"VMware\", \"OpenStack\", \"Citrix\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89244" "VMware强力加盟OpenStack 焉知福祸？" "资讯" "c(\"VMware\", \"OpenStack\", \"Citrix\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89245" "Dell云发布新特色 IaaS平台再添新战力" "资讯" "c(\"Dell\", \"IaaS\", \"AWS\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89246" "首例可感染虚拟机的病毒Crisis被发现" "资讯" "c(\"安全\", \"Crisis\", \"VMware\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89247" "Cloud Foundry Eclipse集成支持数据通道功能" "资讯" "c(\"CloudFoundry\", \"Eclipse\", \"VMware\", \"VMware\", \"MongoDB\")" NA "V" "VMware"
"89248" "OSAC专访程辉：VMware收购Nicira不会对OpenStack造成影响" "资讯" "c(\"程辉\", \"Nicira\", \"VMware\", \"OpenStack\", \"IaaS\")" NA "V" "VMware"
"89249" "使用云服务还要花钱？你OUT了" "资讯" "c(\"免费\", \"VMware\", \"Rackspace\", \"红帽\", \"混合云\")" NA "V" "VMware"
"89250" "软件吞噬一切：Oracle抢购Xsigo" "资讯" "c(\"VMware\", \"Oracle\", \"SDN\", \"云计算\", \"Xsigo\")" NA "V" "VMware"
"89251" "Oracle收购Xsigo VMware、Cisco竞争加剧" "资讯" "c(\"Oracle\", \"Xsigo\", \"VMware\", \"Nicira\", \"Cisco\")" NA "V" "VMware"
"89252" "Nicira落入VMware之手 Cisco错失良机？" "资讯" "c(\"EMC\", \"VMware\", \"Cisco\", \"Nicira\", \"OpenStack\")" NA "V" "VMware"
"89253" "12.6亿美元 虚拟化技术厂商VMware收购Nicira" "资讯" "c(\"收购\", \"VMware\", \"Nicira\", \"Nicira\", \"OpenStack\")" NA "V" "VMware"
"89254" "EMC/VMware业务大整合 CEO人事变动" "资讯" "c(\"EMC\", \"VMware\", \"Cloud\", \"Foundry\", \"虚拟化\")" NA "V" "VMware"
"89255" "VMware剥离Cloud Foundry 应对AWS" "资讯" "c(\"PaaS\", \"Cloud\", \"Foundry\", \"云计算\", \"VMware\")" NA "V" "VMware"
"89256" "VMware发布Zimbra 8.0 实现快速部署私有云" "资讯" "c(\"VMware\", \"Zimbra\", \"Foundry\", \"云计算\", \"VMware\")" NA "V" "VMware"
"89257" "OpenStack与Citrix VMware Microsoft在VDI市场上燃起新战火" "资讯" "c(\"VDI\", \"Microsoft\", \"VMware\", \"Citrix\", \"OpenStack\")" NA "V" "VMware"
"89258" "红帽发布混合云管理软件CloudForms" "资讯" "c(\"公有云\", \"私有云\", \"混合云\", \"VMware\", \"OpenStack\")" NA "V" "VMware"
"89259" "<U+200B>新版CloudFoundry揭秘" "资讯" "c(\"VMware\", \"云计算\", \"Foundry\", \"Cloud\", \"PaaS\")" NA "V" "VMware"
"89260" "2012年桌面虚拟化的发展之路" "资讯" "c(\"服务器\", \"虚拟化\", \"vmware\", \"配置管理\", \"桌面虚拟化\")" NA "V" "VMware"
"89261" "VMware全球首席技术官Steve Herrod：2012年“开放PaaS”继续增长" "资讯" "c(\"虚拟化\", \"数据中心\", \"paas\", \"vmware\", \"互联网\")" NA "V" "VMware"
"89262" "Atos、EMC和VMware组建开放式云计算战略联盟" "资讯" "c(\"产品\", \"emc\", \"vmware\", \"云计算\", \"数据中心\")" NA "V" "VMware"
"89263" "Cloud Foundry开发者大会嘉宾PPT分享" "资讯" "c(\"PaaS\", \"Cloud\", \"Foundry\", \"云计算\", \"VMware\")" NA "V" "VMware"
"89264" "Cloud Foundry开发者大会移师上海 打造第二个硅谷" "资讯" "c(\"PaaS\", \"Cloud\", \"Foundry\", \"云计算\", \"VMware\")" NA "V" "VMware"
"89265" "Cloud Foundry开发者大会北京开启 Mark赞开发者水平高" "资讯" "c(\"VMware\", \"云计算\", \"Foundry\", \"Cloud\", \"PaaS\")" NA "V" "VMware"
"89266" "移动办公成为趋势 VMware研发看重中国" "资讯" "c(\"vmware\", \"产品\", \"平台\", \"虚拟化\", \"云计算\")" NA "V" "VMware"
"89267" "谁将会成为下一个“Dropbox”？比赛仍在进行中" "资讯" "c(\"vmware\", \"平台\", \"跨平台\", \"产品\", \"存储\")" NA "V" "VMware"
"89268" "且看开放PaaS平台Cloud Foundry的强大阵容" "资讯" "c(\"VMware\", \"云计算\", \"Foundry\", \"Cloud\", \"PaaS\")" NA "V" "VMware"
"89269" "2012年F5 Networks应用交付高峰论坛北京站成功落幕" "资讯" "c(\"sharepoint\", \"vmware\", \"数据中心\", \"负载均衡\", \"f5\")" NA "V" "VMware"
"89270" "Vmware Spring Hadoop：支持Hadoop应用" "资讯" "c(\"spring\", \"hadoop\", \"groovy\", \"mapreduce\", \"vmware\")" NA "V" "VMware"
"89271" "开源成熟PaaS平台 Cloud Foundry云开发者大会首次来到国内" "资讯" "c(\"云计算\", \"VMware\", \"Foundry\", \"Cloud\", \"PasS\")" NA "V" "VMware"
"89272" "云计算公司VMwareQ4净利2亿美元 同比增67%" "资讯" "c(\"2010\", \"任务\", \"虚拟化\", \"云计算\", \"vmware\")" NA "V" "VMware"
"89273" "谷歌任命VMware联合创始人格林为董事会董事" "资讯" "c(\"腾讯\", \"虚拟化\", \"谷歌\", \"格林\", \"vmware\")" NA "V" "VMware"
"89274" "Linux 3.2内核正式版发布" "资讯" "c(\"ubuntu\", \"vmware\", \"linux\", \"系统内核\", \"3.2\")" NA "V" "VMware"
"89275" "数据显示：云计算2012年将走向普及" "资讯" "c(\"vmware\", \"数据中心\", \"云计算\", \"虚拟化\", \"数据\")" NA "V" "VMware"
"89276" "Vmware推出适用Kindle Fire的Windows虚拟软件" "资讯" "c(\"Vmware\", \"Kindle\", \"Fire\", \"Windows\", \"虚拟化\")" NA "V" "VMware"
"89277" "VMware和英伟达联手 提高虚拟桌面性能" "资讯" "c(\"vmware\", \"英伟达\", \"虚拟化\", \"服务器\", \"虚拟图像平台\")" NA "V" "VMware"
"89278" "VMware Zimbra产品中国区研发经理曹海荣：需求决定功能" "资讯" "c(\"web服务\", \"vmware\", \"云浏览器\", \"产品\", \"silk\")" NA "V" "VMware"
"89279" "Hyper-V 3发布 微软虚拟化平台迎全新升级" "资讯" "c(\"Hyper-V\", \"服务器\", \"VMware\", \"微软\", \"虚拟化\")" NA "V" "VMware"
"89280" "思科与VMware扩大合作 将推虚拟可扩展LAN" "资讯" "c(\"vmware\", \"扩展\", \"防火墙\", \"数据中心\", \"思科\")" NA "V" "VMware"
"89281" "VMworld 2011：VMware推出数据库即服务新模式" "资讯" "c(\"数据库\", \"虚拟化\", \"greenplum\", \"vmware\", \"vmworld\")" NA "V" "VMware"
"89282" "VMworld：惠普Matrix刀片用最新vSphere" "资讯" "c(\"刀片\", \"虚拟化\", \"惠普\", \"VMware\", \"vmworld\")" NA "V" "VMware"
"89283" "VMware为vCloud数据中心增加迁移和恢复工具" "资讯" "c(\"云计算\", \"vmware\", \"工具\", \"数据中心\", \"vcloud\")" NA "V" "VMware"
"89284" "戴尔与Vmware联合打做企业级云计算" "资讯" "c(\"it厂商\", \"戴尔\", \"数据中心\", \"云计算\", \"vmware\")" NA "V" "VMware"
"89285" "VMware vSphere 5携新功能强势出击" "资讯" "c(\"vsphere\", \"windows\", \"服务器\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89286" "国外近四成服务器是“虚”的" "资讯" "c(\"平台\", \"vmware\", \"虚拟机\", \"服务器\", \"虚拟化\")" NA "V" "VMware"
"89287" "用户不满VMware新版vSphere 5授权方式" "资讯" "c(\"服务器\", \"防火墙\", \"存储系统\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89288" "VMware vCD1.5助企业和服务供应商创建和运营安全的混合云" "资讯" "c(\"VMware\", \"vCloud\", \"Director\", \"混合云\", \"安全\")" NA "V" "VMware"
"89289" "企业服务器虚拟化率不到40%" "资讯" "c(\"vmware\", \"中间件\", \"服务器\", \"虚拟化\", \"虚拟机\")" NA "V" "VMware"
"89290" "VMware推出VMware VSphere 5和云基础架构套件" "资讯" "c(\"服务器\", \"数据中心\", \"云计算\", \"虚拟机\", \"vmware\")" NA "V" "VMware"
"89291" "Gartner：VMware不再是x86虚拟化市场霸主" "资讯" "c(\"虚拟化\", \"Citrix\", \"Microsoft\", \"VMware\", \"vmware\")" NA "V" "VMware"
"89292" "HP存储将集成VMware API" "资讯" "c(\"api\", \"vmware\", \"存储\", \"vaai\", \"hp\")" NA "V" "VMware"
"89293" "VMware推出应用平台vFabric 5" "资讯" "c(\"虚拟化\", \"vfabric\", \"服务器\", \"平台\", \"vmware\")" NA "V" "VMware"
"89294" "VMware收购企业内部微博之称的协作软件厂商Socialcast" "资讯" "c(\"微博\", \"powerpoint\", \"企业应用\", \"socialcast\", \"vmware\")" NA "V" "VMware"
"89295" "IBM、红帽等创建开放虚拟化联盟对抗VMware" "资讯" "c(\"虚拟化\", \"英特尔\", \"vmware\", \"红帽\", \"ibm\")" NA "V" "VMware"
"89296" "VMware收购IT管理解决方案厂商Shavlik" "资讯" "c(\"vmware\", \"产品\", \"虚拟化\", \"云计算\", \"shavlik\")" NA "V" "VMware"
"89297" "VMware引终端用户计算模式变革之旅 勾勒远景" "资讯" "c(\"vmware\", \"终端\", \"开发工具\", \"协作平台\", \"桌面环境\")" NA "V" "VMware"
"89298" "VMware收购云计算企业PPT服务商SlideRocket" "资讯" "c(\"google\", \"vmware\", \"虚拟化\", \"sliderocket\", \"云计算\")" NA "V" "VMware"
"89299" "VMware一季度净利润1.26亿美元 同比增长60%" "资讯" "c(\"腾讯\", \"vmware\", \"虚拟化\", \"净利润\", \"一季度\")" NA "V" "VMware"
"89300" "VMware推出首款开放PaaS平台Cloud Foundry" "资讯" "c(\"web服务\", \"平台\", \"paas\", \"cloudfoundry\", \"vmware\")" NA "V" "VMware"
"89301" "VMware将推出针对安卓和Mac的虚拟化客户端" "资讯" "c(\"VMware\", \"安卓\", \"Macx\", \"虚拟化\", \"客户端\")" NA "V" "VMware"
"89302" "VMware收购Mozy 加强在线备份服务" "资讯" "c(\"mozy\", \"云计算\", \"数据备份\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89303" "VMware推出iPad版VMwareView虚拟桌面终端" "资讯" "c(\"虚拟桌面终端\", \"VMwareView\", \"iPad\", \"VMware\", \"vmware\")" NA "V" "VMware"
"89304" "iPad也能云计算 VMware推出iPad版vSphere应用" "资讯" "c(\"iPad\", \"云计算\", \"VMware\", \"vSphere\", \"vmware\")" NA "V" "VMware"
"89305" "亚马逊EC2可直接导入VMware虚拟机镜像" "资讯" "c(\"虚拟机\", \"VMware\", \"EC2\", \"亚马逊\", \"vmware\")" NA "V" "VMware"
"89306" "四大巨头云策略：各领风骚" "资讯" "c(\"云策略\", \"红帽\", \"Eucalyptus\", \"VMware\", \"微软\")" NA "V" "VMware"
"89307" "解读VMware云计算术语" "资讯" "c(\"虚拟化\", \"云计算\", \"远程连接\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89308" "VMware管理员如何管理XenServer？" "资讯" "c(\"虚拟机\", \"服务器\", \"vmware\", \"interface\", \"xenserver\")" NA "V" "VMware"
"89309" "VMware发布Zimbra 7 推动终端用户计算战略" "资讯" "c(\"终端\", \"虚拟化\", \"服务器\", \"zimbra\", \"vmware\")" NA "V" "VMware"
"89310" "VMware预测：2011年虚拟化和云计算趋势" "资讯" "c(\"企业应用\", \"虚拟化\", \"数据中心\", \"云计算\", \"vmware\")" NA "V" "VMware"
"89311" "李开复：微软当前大敌是VMware而非Google" "资讯" "c(\"李开复\", \"vmware\", \"google\", \"微软\", \"vmware\")" NA "V" "VMware"
"89312" "VMware面向Android智能手机的虚拟化" "资讯" "c(\"服务器\", \"手机\", \"android\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89313" "LG将VMware虚拟化技术加入Android手机产品" "资讯" "c(\"手机\", \"虚拟化\", \"android\", \"vmware\", \"lg\")" NA "V" "VMware"
"89314" "VMware推出Code2Cloud 引领云时代应用开发" "资讯" "c(\"code2cloud\", \"开发工具\", \"web服务\", \"云时代\", \"vmware\")" NA "V" "VMware"
"89315" "Spring框架创始人：向云计算的迁移势在必行" "资讯" "c(\"数据中心\", \"框架\", \"spring\", \"云计算\", \"vmware\")" NA "V" "VMware"
"89316" "EMC叶成辉：私有云一定要选择不同厂商产品" "资讯" "c(\"服务器\", \"vforum\", \"greenplum\", \"emc\", \"vmware\")" NA "V" "VMware"
"89317" "VMware数据中心平台副总裁：帮助开发者融入云计算" "资讯" "c(\"vmware\", \"平台\", \"云计算\", \"数据中心\", \"vforum\")" NA "V" "VMware"
"89318" "VMware全球执行副总裁：在中国私有云是云计算的起点" "资讯" "c(\"vforum\", \"防火墙\", \"分布式计算\", \"云计算\", \"vmware\")" NA "V" "VMware"
"89319" "宋家瑜：VMware在虚拟化领域已一家独大" "资讯" "c(\"数据中心\", \"vmware\", \"虚拟化\", \"vfabric\", \"宋家瑜\")" NA "V" "VMware"
"89320" "亚马逊弹性云计算推出一年免费服务" "资讯" "c(\"ec2\", \"aws\", \"亚马逊\", \"VMware\", \"宋家瑜\")" NA "V" "VMware"
"89321" "英特尔拉拢大客户组建开放数据中心联盟" "资讯" "c(\"vmware\", \"互联网\", \"数据中心\", \"英特尔\", \"云计算\")" NA "V" "VMware"
"89322" "VMware正式交付VMware View 4.5" "资讯" "c(\"桌面环境\", \"数据中心\", \"4.5\", \"view\", \"vmware\")" NA "V" "VMware"
"89323" "云计算操作系统灭掉CMDB带来的哲学思考" "资讯" "c(\"vmware\", \"平台\", \"structure\", \"云计算\", \"服务器\")" NA "V" "VMware"
"89324" "Vmware vCloud介绍" "资讯" "c(\"2010\", \"百度\", \"hadoop\", \"云计算\", \"vmware\")" NA "V" "VMware"
"89325" "专家分析：VMware需要OS对抗微软" "资讯" "c(\"服务器\", \"云计算\", \"虚拟化\", \"数据中心\", \"操作系统相关\")" NA "V" "VMware"
"89326" "VMware vCloud Director象征意义大于实际意义？" "资讯" "c(\"服务器\", \"虚拟机\", \"云计算\", \"财务系统\", \"数据中心\")" NA "V" "VMware"
"89327" "微软与VMware谁更擅长灾难恢复？" "资讯" "c(\"工具\", \"产品\", \"微软\", \"vmware\", \"数据库\")" NA "V" "VMware"
"89328" "VMware拓展云基础架构战略 交付新产品推动“IT即服务”" "资讯" "c(\"云计算\", \"产品\", \"数据中心\", \"负载均衡\", \"vmware\")" NA "V" "VMware"
"89329" "VMware研发Project Horizon云应用交付服务" "资讯" "c(\"虚拟机\", \"vmware\", \"数据中心\", \"服务器\", \"虚拟化\")" NA "V" "VMware"
"89330" "VMware整合Java开发框架 推云计算应用平台" "资讯" "c(\"云计算\", \"框架\", \"vmware\", \"应用服务器\", \"java\")" NA "V" "VMware"
"89331" "Oracle发布集成虚拟化产品组合 目标直指VMware" "资讯" "c(\"vmware\", \"数据中心\", \"产品\", \"oracle\", \"虚拟化\")" NA "V" "VMware"
"89332" "云计算时代：LAMP何去何从？" "资讯" "c(\"vmware\", \"平台\", \"python\", \"microsoft\", \"cassandra\")" NA "V" "VMware"
"89333" "桌面虚拟化思杰再度领先VMware？" "资讯" "c(\"平台\", \"产品\", \"虚拟化\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89334" "受虚拟化冲击 2010服务器硬件市场仍疲软" "资讯" "c(\"x86\", \"存储\", \"虚拟化\", \"服务器\", \"vmware\")" NA "V" "VMware"
"89335" "思科、VMware和NetApp公布首个端到端FCoE配置" "资讯" "c(\"思科\", \"vmware\", \"数据库服务器\", \"数据中心\", \"虚拟化\")" NA "V" "VMware"
"89336" "VMware革新许可证销售模式 以适应云计算" "资讯" "c(\"跨平台\", \"云计算\", \"vmware\", \"扩展\", \"服务器\")" NA "V" "VMware"
"89337" "如何提升VMware VCB的备份性能" "资讯" "c(\"作业\", \"扩展\", \"存储\", \"vmware\", \"microsoft\")" NA "V" "VMware"
"89338" "VMware第二季净利7500万美元 同比增长166%" "资讯" "c(\"微软\", \"虚拟化\", \"vmware\", \"vmware\", \"microsoft\")" NA "V" "VMware"
"89339" "VMware vSphere 4.1持续创新 助中小企业拥抱虚拟化" "资讯" "c(\"云计算\", \"服务器\", \"数据中心\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89340" "VMware发布VMware vSphere 4.1引领云计算" "资讯" "c(\"平台\", \"服务器\", \"虚拟机\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89341" "VMware CEO：将操作系统赶出数据中心" "资讯" "c(\"structure\", \"frameworks\", \"服务器\", \"vmware\", \"数据中心\")" NA "V" "VMware"
"89342" "Orange加入VMware vCloud initiative计划" "资讯" "c(\"互联网\", \"vmware\", \"initiative\", \"vcloud\", \"orangevmware\")" NA "V" "VMware"
"89343" "软通动力亮相“第二届中国云计算大会”" "资讯" "c(\"vmware\", \"平台\", \"企业应用\", \"中国移动\", \"云计算\")" NA "V" "VMware"
"89344" "VMware发布桌面虚拟化工具Workstation 7.1版" "资讯" "c(\"性能优化\", \"工具\", \"虚拟化\", \"workstation\", \"vmware\")" NA "V" "VMware"
"89345" "Google联手VMware 让Java走进云端" "资讯" "c(\"microsoft\", \"云计算\", \"数据中心\", \"java\", \"vmware\")" NA "V" "VMware"
"89346" "VMware与Google合作云计算" "资讯" "c(\"浏览器\", \"云计算\", \"数据中心\", \"企业应用\", \"google\")" NA "V" "VMware"
"89347" "VMware收购Gemstone 完善云计算战略" "资讯" "c(\"金融\", \"平台\", \"服务器\", \"vmware\", \"云计算\")" NA "V" "VMware"
"89348" "VMware：没有操作系统照样玩转云计算" "资讯" "c(\"阿里巴巴\", \"数据中心\", \"邮件服务器\", \"vmware\", \"云计算\")" NA "V" "VMware"
"89349" "Parallels携中文商标“铂勒睿斯”重振大中华区“虚拟化”软件市场" "资讯" "c(\"apple\", \"vmware\", \"产品\", \"microsoft\", \"containers\")" NA "V" "VMware"
"89350" "主流备份软件如何在VMware环境下工作" "资讯" "c(\"产品\", \"数据库\", \"vmware\", \"备份\", \"虚拟化\")" NA "V" "VMware"
"89351" "VMware推出vSphere五折促销计划 助中小企业虚拟化进程" "资讯" "c(\"VMware\", \"vSphere\", \"虚拟化\", \"中小企业\", \"虚拟化\")" NA "V" "VMware"
"89352" "VMware与西门子合作    深化虚拟化合作" "资讯" "c(\"产品\", \"通讯\", \"vmware\", \"虚拟化\", \"虚拟化\")" NA "V" "VMware"
"89353" "实战CPU无VT运行Win7 XP模式" "资讯" "c(\"windows\", \"vmware\", \"微软\", \"虚拟化\", \"xp\")" NA "V" "VMware"
"89354" "虚拟化市场价格之争  VMware减价1/2" "资讯" "c(\"system\", \"工具\", \"服务器\", \"虚拟机\", \"vmware\")" NA "V" "VMware"
"89355" "VMware宣称vSphere 4.0优惠50%" "资讯" "c(\"工具\", \"产品\", \"虚拟化\", \"虚拟机\", \"服务器\")" NA "V" "VMware"
"89356" "VMware的虚拟机管理解决方案" "资讯" "c(\"工具\", \"存储\", \"服务器\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89357" "EMC发布VMware环境下Celerra新软件" "资讯" "c(\"EMC\", \"VMware\", \"Celerra\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89358" "CA公司宣布加入云安全联盟提供身份访问管理技术" "资讯" "c(\"vmware\", \"英特尔\", \"云计算\", \"云安全\", \"ca\")" NA "V" "VMware"
"89359" "VMware将收购母公司EMC数据中心管理软件" "资讯" "c(\"VMware\", \"EMC\", \"Ionix\", \"云安全\", \"ca\")" NA "V" "VMware"
"89360" "VMware或准备停止提供对旧版软件下载" "资讯" "c(\"平台\", \"虚拟机\", \"服务器\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89361" "VMware vSphere 4下载量突破50万" "资讯" "c(\"云计算\", \"服务器\", \"虚拟化\", \"vsphere4\", \"vmware\")" NA "V" "VMware"
"89362" "VMware提供vCloud开源支持 加强云计算服务互助性" "资讯" "c(\"数据中心\", \"web服务\", \"云计算\", \"vcloud\", \"vmware\")" NA "V" "VMware"
"89363" "VMware虚拟机上网设置巧应用" "资讯" "c(\"translation\", \"服务器\", \"web服务\", \"虚拟机\", \"vmware\")" NA "V" "VMware"
"89364" "VMware vSphere与微软Hyper-V间的比较" "资讯" "c(\"VMware\", \"vSphere\", \"微软\", \"Hyper-V\", \"vmware\")" NA "V" "VMware"
"89365" "看开源虚拟化Xen能否击败VMware" "资讯" "c(\"虚拟化\", \"linux内核\", \"vmware\", \"xen\", \"开源虚拟化\")" NA "V" "VMware"
"89366" "专家质疑:云计算扼杀应用开发？" "资讯" "c(\":\", \"VMWare\", \"收购\", \"SpringSource\", \"开源虚拟化\")" NA "V" "VMware"
"89367" "NetApp思科VMware1月26日将宣布合作" "资讯" "c(\"平台\", \"虚拟化\", \"存储系统\", \"vmware\", \"思科\")" NA "V" "VMware"
"89368" "VMware将12日宣布收购雅虎开源电邮部门" "资讯" "c(\"emc\", \"产品\", \"工作\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89369" "VMware或将收购雅虎开源电子邮件部门" "资讯" "c(\"emc\", \"产品\", \"工作\", \"虚拟化\", \"vmware\")" NA "V" "VMware"
"89370" "2009年度虚拟化调查：VMware宝刀未老" "资讯" "c(\"项目管理\", \"数据中心\", \"移动开发技术\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89371" "VMware助力客户大幅降低运营成本" "资讯" "c(\"虚拟机\", \"云计算\", \"服务器\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89372" "更好的管理VMware虚拟化基础设施的四要素" "资讯" "c(\"技术人\", \"虚拟机\", \"数据中心\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89373" "调查 部分VMware用户计划使用替代产品" "资讯" "c(\"产品\", \"虚拟机\", \"虚拟化\", \"服务器\", \"vmware\")" NA "V" "VMware"
"89374" "VMware为企业提供最有价值虚拟化解决方案" "资讯" "c(\"服务器\", \"存储系统\", \"数据中心\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89375" "VMware公布ESX/ESXi 4 Update 1 支持Win7/Windows Server 2008 R2" "资讯" "c(\"虚拟化\", \"microsoft\", \"虚拟机\", \"server\", \"vmware\")" NA "V" "VMware"
"89376" "虚拟化软件VMware Workstation 7.0" "资讯" "c(\"encryption\", \"服务器\", \"文本编辑\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89377" "VMware李严冰：我们不需要和微软作比较" "资讯" "c(\"英特尔\", \"服务器\", \"数据中心\", \"vmware\", \"微软\")" NA "V" "VMware"
"89378" "VMware帮助美的集团提升系统管理灵活性" "资讯" "c(\"websphere\", \"虚拟机\", \"存储系统\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89379" "VMware 近日正式交付 VMware Fusion 3" "资讯" "c(\"虚拟机\", \"云计算\", \"虚拟化\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89380" "云计算中企业数据保护和用户身份认证最佳实践方案" "资讯" "c(\"平台\", \"vmware\", \"网络\", \"虚拟化\", \"云计算\")" NA "V" "VMware"
"89381" "VMware View引领桌面虚拟化变革浪潮" "资讯" "c(\"虚拟化\", \"数据中心\", \"桌面环境\", \"分布式计算\", \"vmware\")" NA "V" "VMware"
"89382" "VMware大幅度降低企业级自动化灾难恢复的成本和复杂性" "资讯" "c(\"云计算\", \"虚拟化\", \"服务器\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89383" "VMware发布虚拟化运用Fusion 3" "资讯" "c(\"windows\", \"os\", \"引擎\", \"优化\", \"vmware\")" NA "V" "VMware"
"89384" "Vista攻击代码曝光 微软面临修复漏洞压力" "资讯" "c(\"vmware\", \"服务器\", \"虚拟机\", \"测试工具\", \"微软\")" NA "V" "VMware"
"89385" "VMware正式提交vCloud API  持续推进开放云计算标准" "资讯" "c(\"云计算\", \"rackspace\", \"数据中心\", \"api\", \"vmware\")" NA "V" "VMware"
"89386" "VMware COO：我们非常了解微软" "资讯" "c(\"技术人\", \"云计算\", \"虚拟机\", \"负载均衡\", \"vmware\")" NA "V" "VMware"
"89387" "VMware和惠普联合发布新方案简化数据中心管理" "资讯" "c(\"工作\", \"技术人\", \"虚拟化\", \"vmware\", \"数据中心\")" NA "V" "VMware"
"89388" "看开源虚拟化Xen能否击败VMware" "资讯" "c(\"虚拟机\", \"linux内核\", \"xen\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89389" "简化数据中心管理 VMware合作伙伴支持vCenter" "资讯" "c(\"思科\", \"扩展\", \"虚拟化\", \"vmware\", \"数据中心\")" NA "V" "VMware"
"89390" "VMware vSphere与微软Hyper-V间的比较" "资讯" "c(\"服务器\", \"虚拟化\", \"数据仓库\", \"vmware\", \"微软\")" NA "V" "VMware"
"89391" "VMware的高管：VMware做好了迎战微软的准备" "资讯" "c(\"服务器\", \"虚拟化\", \"数据中心\", \"vmware\", \"微软\")" NA "V" "VMware"
"89392" "Riverbed解决方案支持VMware vSphere 4平台" "资讯" "c(\"虚拟化\", \"数据中心\", \"riverbed\", \"vmware\", \"平台\")" NA "V" "VMware"
"89393" "VMware面向中小企业免费提供新服务VMware Go" "资讯" "c(\"虚拟化\", \"测试\", \"产品\", \"服务器\", \"vmware\")" NA "V" "VMware"
"89394" "让人迷惑的Windows 7系统任务栏" "资讯" "c(\"活动\", \"vmware\", \"虚拟机\", \"windows\", \"任务\")" NA "V" "VMware"
"89395" "存储技巧：如何应对VMware部署规模增长" "资讯" "c(\"虚拟化\", \"数据库\", \"数据中心\", \"vmware\", \"存储\")" NA "V" "VMware"
"89396" "VMware vSphere 4助客户大幅降低每个应用的成本" "资讯" "c(\"医疗\", \"虚拟化\", \"架构设计\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89397" "纽约时报：VMware或成微软第二大竞争对手" "资讯" "c(\"开发工具\", \"浏览器\", \"数据中心\", \"vmware\", \"微软\")" NA "V" "VMware"
"89398" "Linux集群系统Vmware虚拟机建设方案" "资讯" "c(\"linux内核\", \"linux\", \"vmware\", \"集群\", \"虚拟机\")" NA "V" "VMware"
"89399" "VMware5环境下集群LVS实战解析" "资讯" "c(\"脚本\", \"服务器\", \"浏览器\", \"vmware\", \"集群\")" NA "V" "VMware"
"89400" "VMware宣布收购SpringSource公司" "资讯" "c(\"云计算\", \"虚拟化\", \"数据中心\", \"web应用开发\", \"vmware\")" NA "V" "VMware"
"89401" "Linux下安装VMware虚拟机的过程详解" "资讯" "c(\"windows\", \"linux\", \"vmware\", \"虚拟机\", \"vmware\")" NA "V" "VMware"
"89402" "VMware虚拟机配置实例" "资讯" "c(\"编译器\", \"服务器\", \"防火墙\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89403" "单个VMware虚拟机故障监控和重置" "资讯" "c(\"tools\", \"工作\", \"server\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89404" "虚拟机NAT功能连接物理网络故障一例" "资讯" "c(\"network\", \"vmware\", \"网络\", \"虚拟机\", \"虚拟机\")" NA "V" "VMware"
"89405" "图文：Linux下VMware虚拟机NAT上网实现" "资讯" "c(\"windows\", \"服务器\", \"linux\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89406" "图文：VMware nat方式与主机共享上网设置" "资讯" "c(\"internet\", \"网络\", \"虚拟机\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89407" "VMware虚拟机上网设置和故障排查" "资讯" "c(\"路由器\", \"服务器\", \"dns服务器\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89408" "诡异的Vmware虚拟机自动关机故障" "资讯" "c(\"file\", \"list\", \"thread\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89409" "VMware将以4.2亿收购SpringSource" "资讯" "c(\"服务器\", \"云计算\", \"虚拟化\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89410" "Intel计划减持一半VMware股票" "资讯" "c(\"emc\", \"思科\", \"vmware\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89411" "VMWare虚拟机上网若干招" "资讯" "c(\"网络\", \"通讯\", \"vmware\", \"虚拟机\", \"vmware\")" NA "V" "VMware"
"89412" "VMware虚拟机上网设置巧应用" "资讯" "c(\"translation\", \"服务器\", \"web服务\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89413" "VMware vCenter Chargeback推广遇价格难题" "资讯" "c(\"产品\", \"农业\", \"虚拟化\", \"服务器\", \"vmware\")" NA "V" "VMware"
"89414" "如何预防由VMware驱动和后门程序导致的系统故障" "资讯" "c(\"磁盘\", \"通讯\", \"工作\", \"防火墙\", \"vmware\")" NA "V" "VMware"
"89415" "为什么企业云计算是不可避免的" "资讯" "c(\"工作\", \"vmware\", \"产品\", \"虚拟化\", \"云计算\")" NA "V" "VMware"
"89416" "TechTarget中国举办“中小企业虚拟化部署流程”技术沙龙" "资讯" "c(\"平台\", \"活动\", \"vmware\", \"服务器\", \"虚拟化\")" NA "V" "VMware"
"89417" "谷歌搜索服务API技术主管将跳槽VMware" "资讯" "c(\"vmware\", \"跳槽\", \"api\", \"api技术主管\", \"谷歌\")" NA "V" "VMware"
"89418" "谷歌搜索服务API技术主管将跳槽VMware" "资讯" "c(\"twitter\", \"工作\", \"云计算\", \"api\", \"vmware\")" NA "V" "VMware"
"89419" "怎么样在 VMWare 虚拟PC上安装Linux" "资讯" "c(\"互联网\", \"虚拟机\", \"浏览器\", \"dependencies\", \"vmware\")" NA "V" "VMware"
"89420" "真实体验:VMware服务器迁移的教训" "资讯" "c(\"技术人\", \"数据库\", \"虚拟机\", \"vmware\", \"服务器\")" NA "V" "VMware"
"89421" "Google工程主管再次跳槽 曾让鲍尔默当众摔椅子" "资讯" "c(\"工作\", \"vmware\", \"windows\", \"互联网\", \"google\")" NA "V" "VMware"
"89422" "戴尔推出采用四核AMD皓龙处理器的虚拟化服务器" "资讯" "c(\"扩展\", \"vmware\", \"产品\", \"虚拟机\", \"虚拟化\")" NA "V" "VMware"
"89423" "NEC为NTTCom数据中心提供节能服务器" "资讯" "c(\"vmware\", \"云计算\", \"虚拟化\", \"服务器\", \"数据中心\")" NA "V" "VMware"
"89424" "VMware vSphere 4强化存储性能 实现虚拟化内部云" "资讯" "c(\"企业应用\", \"存储系统\", \"vmware\", \"存储\", \"虚拟化\")" NA "V" "VMware"
"89425" "VMware建数据中心 外界猜测其目标是云计算供应商" "资讯" "c(\"服务器\", \"虚拟机\", \"vmware\", \"云计算\", \"数据中心\")" NA "V" "VMware"
"89426" "戴尔推出采用四核AMD皓龙处理器的虚拟化服务器" "资讯" "c(\"扩展\", \"vmware\", \"产品\", \"虚拟机\", \"虚拟化\")" NA "V" "VMware"
"89427" "虚拟化技术打造绿色数据中心 管理成本可减少40%" "资讯" "c(\"vmware\", \"server\", \"工作\", \"虚拟化\", \"数据中心\")" NA "V" "VMware"
"89428" "惠普VMware宣布结成合作伙伴关系,共同进军虚拟化管理市场" "资讯" "c(\"hp\", \"服务器\", \"配置管理\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89429" "曙光基于VMWare构架Oracle RAC集群数据库" "资讯" "c(\"管理和监控\", \"vmware\", \"oracle\", \"集群\", \"曙光\")" NA "V" "VMware"
"89430" "VMware View提供“随身桌面” 助力医疗信息化" "资讯" "c(\"虚拟化\", \"数据中心\", \"桌面环境\", \"vmware\", \"医疗\")" NA "V" "VMware"
"89431" "在VMware中安装和配置Windows集群" "资讯" "c(\"通讯\", \"服务器\", \"虚拟机\", \"vmware\", \"windows\")" NA "V" "VMware"
"89432" "性能为代价 NFS与NAS谁更适合VMware？" "资讯" "c(\"服务器\", \"虚拟机\", \"虚拟化\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89433" "7-Eleven通过VMware基础架构加快部署步伐" "资讯" "c(\"测试\", \"虚拟化\", \"浏览器\", \"虚拟机\", \"vmware\")" NA "V" "VMware"
"89434" "VMware虚拟化帮助了贵州农行简化管理" "资讯" "c(\"虚拟机\", \"英特尔\", \"数据中心\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89435" "VMware实现了一汽-大众的服务器整合" "资讯" "c(\"虚拟机\", \"虚拟化\", \"企业应用\", \"vmware\", \"服务器\")" NA "V" "VMware"
"89436" "VMware虚拟化技术确保上海通用汽车生产连续性" "资讯" "c(\"制造\", \"虚拟机\", \"数据中心\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89437" "Windows下运行Linux程序Virtual Desktop" "资讯" "c(\"vmware\", \"firefox\", \"虚拟机\", \"linux\", \"windows\")" NA "V" "VMware"
"89438" "VMware安装Redhat不能输入密码问题解决" "资讯" "c(\"联想\", \"防火墙\", \"虚拟机\", \"redhat\", \"vmware\")" NA "V" "VMware"
"89439" "宿主机WindowsXP与虚拟机Linux之间Telnet" "资讯" "c(\"vmware\", \"终端\", \"服务器\", \"linux\", \"虚拟机\")" NA "V" "VMware"
"89440" "如何转换VMware虚拟磁盘镜像到Virtual Server" "资讯" "c(\"服务器\", \"ftp服务器\", \"vmware\", \"server\", \"磁盘\")" NA "V" "VMware"
"89441" "VMware vSphere助力TradeBeam实施云计算战略" "资讯" "c(\"项目管理\", \"存储系统\", \"数据中心\", \"vmware\", \"云计算\")" NA "V" "VMware"
"89442" "如何确保VMware VCenter Server的安全" "资讯" "c(\"validation\", \"虚拟机\", \"数据中心\", \"server\", \"vmware\")" NA "V" "VMware"
"89443" "监控VMware ESX的11种第三方工具" "资讯" "c(\"performance\", \"microsoft\", \"虚拟化\", \"vmware\", \"工具\")" NA "V" "VMware"
"89444" "用VMware创建VIMA以简化ESXi管理" "资讯" "c(\"工具\", \"脚本\", \"虚拟化\", \"interface\", \"vmware\")" NA "V" "VMware"
"89445" "VMware Infrastructure备份解决方案详解" "资讯" "c(\"任务\", \"网络\", \"数据备份\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89446" "开源不适合VMware" "资讯" "c(\"微软\", \"虚拟化\", \"服务器\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89447" "专家剖析微软Hyper-V虚拟化架构与VMware的差异" "资讯" "c(\"虚拟机\", \"硬件驱动\", \"vmware\", \"微软\", \"虚拟化\")" NA "V" "VMware"
"89448" "非虚拟环境让Windows飞速运行Linux程序" "资讯" "c(\"vmware\", \"firefox\", \"虚拟机\", \"linux\", \"windows\")" NA "V" "VMware"
"89449" "服务器虚拟化平台:VMWare ESX 3.5安装图记" "资讯" "c(\"硬件驱动\", \"vmware\", \"平台\", \"服务器\", \"虚拟化\")" NA "V" "VMware"
"89450" "VMware虚拟Linux系统NAT方式上网图解" "资讯" "c(\"服务器\", \"路由器\", \"虚拟机\", \"linux\", \"vmware\")" NA "V" "VMware"
"89451" "VMWare ESX和Ser2008谁能笑到最后 ERP压力测试" "资讯" "c(\"技术人\", \"数据库\", \"存储系统\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89452" "Ubuntu 7.04下安装虚拟机VMware Server" "资讯" "c(\"module\", \"server\", \"ubuntu\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89453" "VMware的有力竞争者：对比Hyper-V与VI3" "资讯" "c(\"虚拟化\", \"服务器\", \"migration\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89454" "VMWare中的虚拟交换机" "资讯" "c(\"网络\", \"路由器\", \"虚拟机\", \"vmware\", \"vmware\")" NA "V" "VMware"
"89455" "升级到vSphere前提条件 判断CPU是否64位" "资讯" "c(\"vmware\", \"产品\", \"测试\", \"工具\", \"服务器\")" NA "V" "VMware"
"89456" "iPhone上的VMware vCenter Mobile Access" "资讯" "c(\"服务器\", \"虚拟机\", \"iphone\", \"vmware\", \"mobile\")" NA "V" "VMware"
"89457" "VMware vSphere 4体验之主机配置文件" "资讯" "c(\"测试\", \"集群\", \"reference\", \"服务器\", \"vmware\")" NA "V" "VMware"
"89458" "vSphere 4体验之vSphere上的Windows 7" "资讯" "c(\"vmware\", \"server\", \"服务器\", \"虚拟机\", \"windows\")" NA "V" "VMware"
"89459" "VMware vSphere 4体验之为虚拟机热添加内存" "资讯" "c(\"测试\", \"微软\", \"windows\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89460" "利用vSphere让RDM与SAN存储系统上的实际LUN相匹配" "资讯" "c(\"存储\", \"vmware\", \"服务器\", \"虚拟机\", \"存储系统\")" NA "V" "VMware"
"89461" "黑客可利用Windows虚拟机攻击其他系统" "资讯" "c(\"vmware\", \"linux\", \"虚拟化\", \"windows\", \"虚拟机\")" NA "V" "VMware"
"89462" "VMware漏洞：Windows虚拟机可攻击Mac主机" "资讯" "c(\"linux\", \"虚拟化\", \"vmware\", \"windows\", \"虚拟机\")" NA "V" "VMware"
"89463" "在VMware中使用NAS的优点" "资讯" "c(\"微软\", \"windows\", \"服务器\", \"存储系统\", \"vmware\")" NA "V" "VMware"
"89464" "数据中心怎样实现高密度服务器配置？" "资讯" "c(\"vmware\", \"测试\", \"虚拟机\", \"服务器\", \"数据中心\")" NA "V" "VMware"
"89465" "在VMWare虚拟机上安装Android" "资讯" "c(\"工作\", \"扩展\", \"磁盘\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89466" "VMware新技术 使用手机管理虚拟机" "资讯" "c(\"浏览器\", \"数据中心\", \"vmware\", \"手机\", \"虚拟机\")" NA "V" "VMware"
"89467" "解决VMware虚拟环境的数据保护难题" "资讯" "c(\"虚拟机\", \"数据库\", \"数据备份\", \"应用服务器\", \"vmware\")" NA "V" "VMware"
"89468" "解析：VMM2008管理Vmware Esx 3.5" "资讯" "c(\"虚拟化\", \"migration\", \"powershell\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89469" "如何避免VMware虚拟机出现备份缺陷" "资讯" "c(\"虚拟化\", \"microsoft\", \"杀毒软件\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89470" "Symantec针对VMware推灾难复原方案" "资讯" "c(\"migration\", \"performance\", \"虚拟化\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89471" "美国五角大楼应用程序虚拟化面临的威胁" "资讯" "c(\"微软\", \"vmware\", \"服务器\", \"数据备份\", \"虚拟化\")" NA "V" "VMware"
"89472" "简单几招教你玩转 VMware 虚拟机" "资讯" "c(\"browser\", \"windows\", \"测试\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89473" "ESX Service Console安装备份程序之部署技巧" "资讯" "c(\"linux\", \"vmware\", \"脚本\", \"虚拟机\", \"service\")" NA "V" "VMware"
"89474" "ESX Service Console安装备份程序之缺点分析" "资讯" "c(\"linux\", \"脚本\", \"vmware\", \"server\", \"service\")" NA "V" "VMware"
"89475" "在每个VM中安装本地备份程序之缺点分析女" "资讯" "c(\"vmware\", \"服务器\", \"vmware\", \"server\", \"service\")" NA "V" "VMware"
"89476" "VMware数据备份和恢复方法的三种方法" "资讯" "c(\"脚本\", \"框架\", \"虚拟机\", \"vmware\", \"数据备份\")" NA "V" "VMware"
"89477" "实战教程：VMware虚拟机的裸设备级备份" "资讯" "c(\"工具\", \"数据库\", \"硬件驱动\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89478" "AMD展示其同Intel物理服务器间动态迁移能力" "资讯" "c(\"微软\", \"vmware\", \"英特尔\", \"虚拟化\", \"服务器\")" NA "V" "VMware"
"89479" "VMware漏洞是虚拟化的危机吗" "资讯" "c(\"服务器\", \"数据中心\", \"dhcp软件\", \"vmware\", \"虚拟化\")" NA "V" "VMware"
"89480" "09存储市场iSCSI SAN销售名列前茅" "资讯" "c(\"vmware\", \"虚拟化\", \"服务器\", \"存储系统\", \"存储\")" NA "V" "VMware"
"89481" "VMware虚拟机中鼠标中键无法使用的问题" "资讯" "c(\"input\", \"ubuntu\", \"vmware\", \"虚拟机\", \"存储\")" NA "V" "VMware"
"89482" "VMware虚拟化管理工具让管理员变轻松" "资讯" "c(\"虚拟机\", \"powershell\", \"vmware\", \"工具\", \"虚拟化\")" NA "V" "VMware"
"89483" "浅析使用VMware Server虚拟化服务器的五大理由" "资讯" "c(\"微软\", \"vmware\", \"server\", \"服务器\", \"虚拟化\")" NA "V" "VMware"
"89484" "网络配置决定虚拟环境安全" "资讯" "c(\"微软\", \"vmware\", \"防火墙\", \"杀毒软件\", \"网络\")" NA "V" "VMware"
"89485" "VMware助力用友伟库网提升服务器利用率 降低运营成本" "资讯" "c(\"平台\", \"互联网\", \"vmware\", \"服务器\", \"用友伟库\")" NA "V" "VMware"
"89486" "VMware虚拟机热备份的几种方法" "资讯" "c(\"windows\", \"工具\", \"服务器\", \"vmware\", \"虚拟机\")" NA "V" "VMware"
"89487" "解决VMware快照故障的方法" "资讯" "c(\"虚拟化\", \"浏览器\", \"数据库\", \"服务器\", \"vmware\")" NA "V" "VMware"
"89488" "KVM虚拟化常见问题" "资讯" "c(\"扩展\", \"vmware\", \"properties\", \"linux内核\", \"虚拟化\")" NA "V" "VMware"
"89489" "VMware计划2010年启用手机虚拟技术" "资讯" "c(\"虚拟机\", \"数据备份\", \"2010\", \"vmware\", \"手机\")" NA "V" "VMware"
"89490" "VMware计划2010年启用手机虚拟技术" "资讯" "c(\"虚拟机\", \"数据备份\", \"2010\", \"vmware\", \"手机\")" NA "V" "VMware"
"89491" "VMware交付vSphere4  构筑云计算未来之路" "资讯" "c(\"虚拟机\", \"虚拟化\", \"数据中心\", \"vmware\", \"云计算\")" NA "V" "VMware"
"89492" "专为中小企业 惠普新刀片BladeSystem c3000解析" "资讯" "c(\"vmware\", \"优化\", \"网络\", \"microsoft\", \"数据中心\")" NA "V" "VMware"
"89493" "VMware助力企业和政府机构走向绿色" "资讯" "c(\"终端\", \"能源\", \"虚拟机\", \"虚拟化\", \"数据中心\")" NA "V" "VMware"
"89494" "VMware vSphere 4获众多合作伙伴全力支持" "资讯" "c(\"思科\", \"云计算\", \"英特尔\", \"虚拟化\", \"服务器\")" NA "V" "VMware"
"89495" "VMware云操作系统让SMB小型IT环境轻松实现“始终可用”" "资讯" "c(\"集群\", \"工作\", \"防火墙\", \"虚拟机\", \"数据中心\")" NA "V" "VMware"
"89496" "VMware推出业界首款云操作系统 提供“IT即服务”" "资讯" "c(\"VMware\", \"云操作系统\", \"云计算\", \"vSphere\", \"IT即服务\")" NA "V" "VMware"
"89497" "VMware Mac版本漏洞可任意执行恶意代码" "资讯" "c(\"os\", \"虚拟化\", \"windows\", \"linux\", \"虚拟机\")" NA "V" "VMware"
"89498" "传4月21日VMware发布下一代虚拟软件vSphere" "资讯" "c(\"虚拟化\", \"服务器\", \"数据中心\", \"vmware\", \"虚拟化，vsphere，\")" NA "V" "VMware"
"89499" "VMware推出新计划 确保客户节省开支" "资讯" "c(\"产品\", \"扩展\", \"平台\", \"虚拟化\", \"数据中心\")" NA "V" "VMware"
"89500" "独家：VMWare推出在线“程序成本”计算器" "资讯" "c(\"服务器\", \"虚拟化\", \"数据中心\", \"vmware\", \"虚拟化，\")" NA "V" "VMware"
"89501" "浪潮将与VMware建立联合实验室" "资讯" "c(\"存储系统\", \"服务器\", \"联合实验室\", \"浪潮\", \"vmware\")" NA "V" "VMware"
"89502" "VMware与曙光达成OEM协议" "资讯" "c(\"宋家瑜\", \"VMware\", \"曙光\", \"OEM\", \"vmware\")" NA "V" "VMware"
"89503" "VMware与曙光达成OEM协议" "资讯" "c(\"虚拟化\", \"嵌入式\", \"服务器\", \"数据中心\", \"vmware\")" NA "V" "VMware"
"89504" "IBM牵头签署《开放云宣言》 微软谷歌缺席" "资讯" "c(\"vmware\", \"salesforce\", \"云计算\", \"ibm\", \"微软\")" NA "V" "VMware"
"89505" "VMware正式启用中文名称——威睿" "资讯" "c(\"浪潮\", \"平台\", \"技术人\", \"用友伟库\", \"数据中心\")" NA "V" "VMware"
"89506" "如何打造最安全的服务器虚拟化环境" "资讯" "c(\"vmware\", \"网络\", \"防火墙\", \"杀毒软件\", \"虚拟化\")" NA "V" "VMware"
"89507" "黑客大赛苹果及微软操作系统均被攻破" "资讯" "c(\"safari\", \"vmware\", \"security\", \"网络\", \"浏览器\")" NA "V" "VMware"
"89508" "2009年信息安全行业值得注意的十大趋势" "资讯" "c(\"vmware\", \"网络\", \"加密\", \"防火墙\", \"英特尔\")" NA "V" "VMware"
"89509" "微软实际行动回归开发者为中心 拥抱全平台开发者" "资讯" "c(\"asp.net\", \"visual studio\", \".net\", \"微软\", \"开源\")" NA "V" "Visual Studio"
"89510" "Matlab通过mex调用CUDA的方法" "极客头条" "c(\"matlab\", \"cuda\", \"visual studio\", \"mex\", \"开源\")" "bendanban" "V" "Visual Studio"
"89511" "AWS Elastic Beanstalk" "资讯" "c(\"visual studio\", \"amazon ec2\", \"aws\", \"mex\", \"开源\")" NA "V" "Visual Studio"
"89512" "TypeScript 1.5发布，支持大量ES6新特性" "资讯" "c(\"visual studio\", \"javascript\", \"ES6\", \"TypeScript 1.5\", \"开源\")" NA "V" "Visual Studio"
"89513" "从Build 2015说起：微软不是缺兵少将的“西蜀”，或在物联网时代复兴" "资讯" "c(\"物联网\", \"微软\", \"移动互联网\", \"云计算平台\", \"开发人员\")" NA "V" "Visual Studio"
"89514" "TIOBE 2015年5月编程语言排行榜：微软系语言份额上升" "资讯" "c(\"编程语言\", \"tiobe\", \"visual studio\", \"搜索引擎\", \"程序员\")" NA "V" "Visual Studio"
"89515" "微软新Visual Studio Code开发工具支持Mac和Linux" "资讯" "c(\"微软\", \"编辑器\", \"编码\", \"visual studio\", \"开发工具\")" NA "V" "Visual Studio"
"89516" ".NET开源决策者潘正磊：什么样的成功情境才是开源的成果" "资讯" "c(\"潘正磊\", \"开源\", \".net\", \"开源软件\", \"visual studio\")" NA "V" "Visual Studio"
"89517" "微软开源Visual Studio构建工具MSBuild" "资讯" "c(\"visual studio\", \"微软\", \"开源\", \"MSBuild\", \"visual studio\")" NA "V" "Visual Studio"
"89518" "微软开源版ASP.NET 5支持Linux构建程序" "资讯" "c(\"微软\", \"开源\", \"asp.net\", \"linux\", \"visual studio\")" NA "V" "Visual Studio"
"89519" "面向WP和Android！微软车库发布多款免费应用" "资讯" "c(\"移动应用\", \"微软\", \"免费\", \"Android\", \"Windows Phone\")" NA "V" "Visual Studio"
"89520" ".NET开发者必备的工具箱" "资讯" "c(\"开发工具\", \".NET\", \"Visual Studio\", \"API\", \"dotPeek\")" NA "V" "Visual Studio"
"89521" "微软收购跨平台移动开发工具套件HockeyApp" "资讯" "c(\"微软\", \"收购\", \"跨平台\", \"移动开发工具\", \"HockeyApp\")" NA "V" "Visual Studio"
"89522" "使用Visual Studio 进行SQL Server源代码管理和部署" "极客头条" "c(\"visual studio\", \"sql server\", \"管理\", \"源代码\", \"HockeyApp\")" "yxy1992_123" "V" "Visual Studio"
"89523" "盘点VS2015 预览版的5个新特性" "资讯" "c(\"Visual Studio\", \"IDE\", \"微软\", \"源代码\", \"HockeyApp\")" NA "V" "Visual Studio"
"89524" "第一个IDE稳定版本：Google发布Android Studio 1.0" "资讯" "c(\"Android Studio 1.0\", \"Google\", \"Visual Studio\", \"开发者\", \"应用\")" NA "V" "Visual Studio"
"89525" "5个难以置信的VS 2015预览版新特性" "极客头条" "c(\"Visual Studio\", \"Google\", \"Visual Studio\", \"开发者\", \"应用\")" "yxy1992_123" "V" "Visual Studio"
"89526" "Compiling Java in Visual Studio" "极客头条" "c(\"java\", \"visual studio\", \"Visual Studio\", \"开发者\", \"应用\")" "liuzhuoran1110" "V" "Visual Studio"
"89527" "详解Visual Studio Emulator for Android，微软的Mobile First！" "资讯" "c(\"移动开发\", \"Android\", \"微软\", \"iOS\", \".NET\")" NA "V" "Visual Studio"
"89528" "开发者工具Visual Studio 2013 Update 4 RC已开放下载" "极客头条" "c(\"Visual Studio\", \"开发者\", \"编程\", \"iOS\", \".NET\")" "qiansg123" "V" "Visual Studio"
"89529" "不用Visual Studio，5分钟轻松实现一张报表" "极客头条" "c(\"Visual Studio\", \"报表\", \"编程\", \"iOS\", \".NET\")" "yxy1992_123" "V" "Visual Studio"
"89530" "Visual Studio 14最新版免费下载" "极客头条" "c(\"Visual Studio\", \"报表\", \"编程\", \"iOS\", \".NET\")" "qiansg123" "V" "Visual Studio"
"89531" "微软推Bing开发助理 能帮VS开发者快速找到代码片段和示例" "资讯" "c(\"Visual Studio\", \"微软\", \"Bing开发助理\", \"搜索\", \"Bing\")" NA "V" "Visual Studio"
"89532" "跨平台开发如何事半功倍 Xamarin推出免费培训" "资讯" "c(\"跨平台\", \"Xamarin\", \"C#\", \"visual studio\", \".net framework\")" NA "V" "Visual Studio"
"89533" "UnityVS的开发商SyntaxTree被微软收购 今后开放下载" "资讯" "c(\"微软\", \"SyntaxTree\", \"Visual Studio\", \"开发者\", \"收购\")" NA "V" "Visual Studio"
"89534" "微软被传收购Xamarin 强势推进移动新战略" "资讯" "c(\"移动开发者\", \"跨平台\", \"Xamarin\", \"CSDN\", \"C#\")" NA "V" "Visual Studio"
"89535" "PTVS 2.1 Beta版发布 Visual Studio的Python工具" "资讯" "c(\"visual studio\", \"python\", \"PTVS\", \"Django\", \"开源\")" NA "V" "Visual Studio"
"89536" "微软Build2014大会第二天干货总结 Microsoft Azure拥抱Puppet、Chef、MongoDB..." "资讯" "c(\"微软\", \"puppet\", \"chef\", \"azure\", \"visual studio\")" NA "V" "Visual Studio"
"89537" "微软Build2014第一天应了解的15件事" "资讯" "c(\"微软\", \"Build大会\", \"windows\", \"windows phone\", \"Visual Studio\")" NA "V" "Visual Studio"
"89538" "TypeScript1.0发布，完美支持Visual Studio系列产品" "资讯" "c(\"typescript\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" NA "V" "Visual Studio"
"89539" "微软BUILD 2014大会发布了Visusal Studio 2013 Update 2" "极客头条" "c(\"Visual Studio\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" "jiangtao" "V" "Visual Studio"
"89540" "微软Build2014第一天要点精华汇总（组图）" "资讯" "c(\"微软\", \"windows 8.1\", \"windows\", \"ie11\", \"操作系统\")" NA "V" "Visual Studio"
"89541" "好玩，用Visual Studio构建和修改Linux内核" "极客头条" "c(\"Linux内核\", \"Visual Studio\", \"windows\", \"ie11\", \"操作系统\")" "liujiangce" "V" "Visual Studio"
"89542" "SAP携手Xamarin和Service2Media 提供移动应用开发框架" "资讯" "c(\"SAP\", \"应用开发\", \"移动平台\", \"Xamarin\", \"visual studio\")" NA "V" "Visual Studio"
"89543" "Visual Studio的八个调试建议：像老大哥一样调试" "极客头条" "c(\"visual studio\", \"调试\", \"移动平台\", \"Xamarin\", \"visual studio\")" "u011106205" "V" "Visual Studio"
"89544" "程序员的福音：微软推VS2013扩展Bing Code Search" "资讯" "c(\"扩展\", \"Microsoft\", \"开发环境\", \"程序员\", \"Visual Studio\")" NA "V" "Visual Studio"
"89545" "Android++：为Android App开发而生的Visual Studio的原生扩展" "极客头条" "c(\"visual studio\", \"android\", \"app\", \"扩展\", \"Visual Studio\")" "u011106205" "V" "Visual Studio"
"89546" "“详解Visual Studio 2013”全国巡讲北京站：无忧开发iOS及Android应用" "资讯" "c(\"visual studio\", \"C#\", \"CSDN\", \"移动开发者\", \"Xamarin\")" NA "V" "Visual Studio"
"89547" "微软潘正磊谈DevOps、Visual Studio 2013新功能、.NET未来" "资讯" "c(\"潘正磊\", \"微软\", \"windows azure\", \"windows phone\", \"Visual Studio\")" NA "V" "Visual Studio"
"89548" "IE11中全新增强的F12开发人员工具" "资讯" "c(\"微软\", \"visual studio\", \"IE\", \"IE11\", \"浏览器\")" NA "V" "Visual Studio"
"89549" "将Visual Studio打造成为Node.js IDE" "资讯" "c(\"微软\", \"visual studio\", \"NTVS\", \"Node.js\", \"开源\")" NA "V" "Visual Studio"
"89550" "TUP第30期：微软资深专家论如何用Visual Studio开发iOS、Android应用" "资讯" "c(\"tup\", \"visual studio\", \"移动开发者\", \"Xamarin\", \"MSDN\")" NA "V" "Visual Studio"
"89551" "[TUP第30期]直击移动应用开发难点  探讨跨平台最佳解决方案" "资讯" "c(\"tup\", \"CSDN\", \"visual studio\", \"移动开发\", \"开发工具\")" NA "V" "Visual Studio"
"89552" "libgit2：纯C语言实现的Git开发包" "资讯" "c(\"git\", \"stackoverflow\", \"visual studio\", \"开源\", \"libgit2\")" NA "V" "Visual Studio"
"89553" "在Visual Studio中使用JavaScript、HTML5打造跨平台移动应用" "极客头条" "c(\"Visual Studio\", \"原生应用\", \"JavaScript\", \"跨平台\", \"Icenium\")" "tangxiaoyin" "V" "Visual Studio"
"89554" "Windows 8.1和Visual Studio 2013正式发布" "极客头条" "c(\"Visual Studio\", \"Windows\", \"微软\", \"跨平台\", \"Icenium\")" "lispython" "V" "Visual Studio"
"89555" "微软隐藏最深的秘密武器之一——Visual Studio可作为Python IDE" "资讯" "c(\"微软\", \"Python\", \"Visual Studio\", \"Django\", \"PTVS\")" NA "V" "Visual Studio"
"89556" "Visual Studio 2013 Preview和.NET 4.5.1同时发布 支持Win 8.1应用开发" "资讯" "c(\".NET\", \"Visual Studio\", \"微软\", \"Build 2013\", \"PTVS\")" NA "V" "Visual Studio"
"89557" "iOS版本分布图 vs Android版本分布图，93%的iOS用户使用iOS 6，5%还在iOS 5。 Android版本分裂 严重，4.1版本以上仅有33%，4.1 Jelly Bean是和iOS 6去年夏天同期发布的，4.0是和iOS 5同期发布的。而且这个统计还不包括中国android手机厂商（因为不支持google services）" "极客头条" "c(\"Android\", \"iOS\", \"发布\", \"手机\", \"Google\")" "jiangtao" "V" "Visual Studio"
"89558" "Visual Studio 2013 Preview新功能预览" "资讯" "c(\"Visual Studio\", \"TFS\", \"微软\", \"手机\", \"Google\")" NA "V" "Visual Studio"
"89559" "主流编译器对C++11的支持现状比较" "资讯" "c(\"C++\", \"编译器\", \"Clang\", \"Visual Studio\", \"C++11\")" NA "V" "Visual Studio"
"89560" "苹果拟建新云基础设施，Verizon变卖数据中心" "极客头条" "c(\"云计算\", \"苹果\", \"Verizon\", \"Visual Studio\", \"C++11\")" "huc_rc" "V" "Verizon"
"89561" "Verizon建设巨型物联网集群 100秒可启动五万个Docker容器" "资讯" "c(\"Verizon\", \"Docker\", \"容器\", \"物联网\", \"开发者\")" NA "V" "Verizon"
"89562" "Verizon研究显示：中国成为2012年度网络间谍攻击的主要来源" "资讯" "c(\"安全\", \"DDoS\", \"Verizon\", \"DBIR\", \"开发者\")" NA "V" "Verizon"
"89563" "Verizon：2011年1亿用户数据遭黑客窃取" "资讯" "c(\"Verizon\", \"黑客\", \"泄露\", \"Anonymous\", \"开发者\")" NA "V" "Verizon"
"89564" "谷歌重新考虑谷歌钱包移动支付系统发展策略" "资讯" "c(\"verizon\", \"谷歌\", \"网易\", \"手机\", \"开发者\")" NA "V" "Verizon"
"89565" "NPD：iPhone在美最畅销 新用户多数选Android" "资讯" "c(\"verizon\", \"三星\", \"android\", \"用户\", \"iphone\")" NA "V" "Verizon"
"89566" "全球云计算投资135亿 亚洲北美占90%" "资讯" "c(\"verizon\", \"电信\", \"运营商\", \"云计算\", \"云服务\")" NA "V" "Verizon"
"89567" "T-Mobile CTO：iPhone 5将支持T-Mobile网络" "资讯" "c(\"手机\", \"verizon\", \"t-mobile\", \"android\", \"iphone\")" NA "V" "Verizon"
"89568" "苹果赢得专利侵权案 HTC被裁定禁入美国市场" "资讯" "c(\"verizon\", \"电话\", \"手机\", \"htc\", \"苹果\")" NA "V" "Verizon"
"89569" "Netflix CEO：美国视频流服务已展开军备竞赛" "资讯" "c(\"verizon\", \"网络\", \"互联网\", \"竞赛\", \"netflix\")" NA "V" "Verizon"
"89570" "Groupon大跌15%接近发行价 竞争加剧引忧虑" "资讯" "c(\"网络\", \"verizon\", \"产品\", \"竞争\", \"groupon\")" NA "V" "Verizon"
"89571" "报告称61%全球顶级品牌商已创建Google+页面" "资讯" "c(\"搜索引擎\", \"verizon\", \"google\", \"品牌商\", \"google+\")" NA "V" "Verizon"
"89572" "RIM斥资1亿美元购云服务商NewBay Software" "资讯" "c(\"verizon\", \"电信\", \"黑莓\", \"newbay\", \"rim\")" NA "V" "Verizon"
"89573" "内部消息显示苹果下周二推Sprint版iPhone 5" "资讯" "c(\"网络\", \"产品\", \"verizon\", \"手机\", \"iphone\")" NA "V" "Verizon"
"89574" "全球品牌价值30强：谷歌第一苹果第二" "资讯" "c(\"verizon\", \"微软\", \"英特尔\", \"品牌价值\", \"谷歌\")" NA "V" "Verizon"
"89575" "谷歌董事长：Android 4.0最早将于10月发布" "资讯" "c(\"verizon\", \"手机\", \"4.0\", \"android\", \"谷歌\")" NA "V" "Verizon"
"89576" "软件化成为大趋势：Verizon收购云计算软件创业公司" "资讯" "c(\"互联网\", \"verizon\", \"创业\", \"收购\", \"云计算\")" NA "V" "Verizon"
"89577" "Android手机仍是美国智能机市场主要驱动力" "资讯" "c(\"黑莓\", \"智能手机\", \"verizon\", \"手机\", \"android\")" NA "V" "Verizon"
"89578" "谷歌下一代手机Nexus 4G曝光：搭载Android 4.0" "资讯" "c(\"网络\", \"verizon\", \"三星\", \"report\", \"android\")" NA "V" "Verizon"
"89579" "全球100强电信品牌排行榜曝光 诺基亚降至11" "资讯" "c(\"咨询\", \"verizon\", \"排行\", \"品牌\", \"电信\")" NA "V" "Verizon"
"89580" "尼尔森：Android智能机美国份额首次下降" "资讯" "c(\"verizon\", \"windows\", \"尼尔森\", \"windows phon\", \"android\")" NA "V" "Verizon"
"89581" "美国多家运营商反对AT&T收购T-Mobile" "资讯" "c(\"service\", \"运营商\", \"verizon\", \"t-mobile\", \"AT&amp;T\")" NA "V" "Verizon"
"89582" "谷歌计划携手合作伙伴共推新版Android" "资讯" "c(\"verizon\", \"网络\", \"产品\", \"android\", \"谷歌\")" NA "V" "Verizon"
"89583" "苹果业绩趣闻：买得起Groupon+Twitter+Zynga" "资讯" "c(\"verizon\", \"facebook\", \"手机\", \"苹果业绩\", \"twitter\")" NA "V" "Verizon"
"89584" "Verizon：2010年全美数据库被盗次数创新高" "资讯" "c(\"2010\", \"verizon\", \"被盗\", \"数据库\", \"twitter\")" NA "V" "Verizon"
"89585" "传Twitter开发新商业用户档案页 与Facebook相似" "资讯" "c(\"verizon\", \"工作\", \"产品\", \"twitter\", \"facebook\")" NA "V" "Verizon"
"89586" "苹果新专利获批 运营商网络或将面临流量考验" "资讯" "c(\"电话\", \"工作\", \"verizon\", \"网络\", \"苹果\")" NA "V" "Verizon"
"89587" "Sprint呼吁调查AT&T并购T-Mobile交易" "资讯" "c(\"电信\", \"verizon\", \"sprint\", \"at&amp;t\", \"t-mobile\")" NA "V" "Verizon"
"89588" "HTC联合Verizon在美推出首款4G手机" "资讯" "c(\"网络\", \"手机\", \"verizon\", \"4g\", \"htc\")" NA "V" "Verizon"
"89589" "iPad 2最受关注十大问题：内存、4G等悬疑" "资讯" "c(\"照片\", \"verizon\", \"电话\", \"游戏\", \"ipad\")" NA "V" "Verizon"
"89590" "iPad2八大改变 配A5双核处理器装iOS4.3" "资讯" "c(\"金山\", \"iphone\", \"verizon\", \"ios\", \"ipad2\")" NA "V" "Verizon"
"89591" "传iOS 4.3终于完工" "资讯" "c(\"网络\", \"测试\", \"verizon\", \"iphone\", \"ios\")" NA "V" "Verizon"
"89592" "微软彻底关闭KIN手机相关服务" "资讯" "c(\"iphone\", \"verizon\", \"手机\", \"微软\", \"kin\")" NA "V" "Verizon"
"89593" "Verizon收购云计算公司Terremark Worldwide" "资讯" "c(\"工具\", \"verizon\", \"云计算\", \"worldwide\", \"terremark\")" NA "V" "Verizon"
"89594" "分析称Android平板电脑日趋成开发者新宠" "资讯" "c(\"程序开发\", \"android\", \"verizon\", \"移动开发\", \"平板\")" NA "V" "Verizon"
"89595" "看图说事：谁是美国智能型手机操作系统王者？" "资讯" "c(\"android\", \"手机\", \"verizon\", \"手机操作系统\", \"apple\")" NA "V" "Verizon"
"89596" "程序下载破100亿：苹果平台化趋势被加固？" "资讯" "c(\"google\", \"verizon\", \"产品\", \"平台\", \"程序开发\")" NA "V" "Verizon"
"89597" "商业周刊：没有乔布斯的苹果仍将繁荣壮大" "资讯" "c(\"verizon\", \"网络\", \"音乐\", \"工作\", \"产品设计\")" NA "V" "Verizon"
"89598" "惠普1.2GHz WebOS平板机曝光 9月中国发售" "资讯" "c(\"verizon\", \"网络\", \"webos\", \"工作\", \"产品设计\")" NA "V" "Verizon"
"89599" "乔布斯:Android销量优于苹果 因iPhone 4转型" "资讯" "c(\"iphone\", \"android\", \"iphone4\", \"verizon\", \"消费者报告\")" NA "V" "Verizon"
"89600" "Verizon CEO揭秘iPhone谈判：苹果条件不苛刻" "资讯" "c(\"Verizon\", \"CEO\", \"iPhone\", \"苹果\", \"消费者报告\")" NA "V" "Verizon"
"89601" "iOS 4.3开测 WiFi私人热点功能加入" "资讯" "c(\"测试\", \"wifi\", \"verizon\", \"私人热点\", \"ios\")" NA "V" "Verizon"
"89602" "Verizon版iPhone十大不如意：无缘4G网络居首" "资讯" "c(\"iphone\", \"网络\", \"4g\", \"phone\", \"verizon\")" NA "V" "Verizon"
"89603" "iPhone登陆Verizon：一石激起几层浪？" "资讯" "c(\"终端\", \"游戏\", \"电信\", \"互联网\", \"verizon\")" NA "V" "Verizon"
"89604" "Verizon CDMA版iPhone发布会现场实录" "资讯" "c(\"手机\", \"产品\", \"云计算\", \"verizon\", \"iphone\")" NA "V" "Verizon"
"89605" "美国最大移动运营商Verizon发布CDMA版iPhone 4" "资讯" "c(\"网络\", \"手机\", \"中国电信\", \"iphone\", \"verizon\")" NA "V" "Verizon"
"89606" "苹果2011年11大目标：推出Verizon版iPhone" "资讯" "c(\"产品\", \"产品设计\", \"iphone\", \"verizon\", \"苹果\")" NA "V" "Verizon"
"89607" "消息称谷歌考虑开发移动支付系统" "资讯" "c(\"手机\", \"移动支付\", \"verizon\", \"谷歌\", \"开发\")" NA "V" "Verizon"
"89608" "AT&T高管暗示可能将失去iPhone独家销售权" "资讯" "c(\"电信\", \"verizon\", \"手机\", \"iphone\", \"at&amp;t\")" NA "V" "Verizon"
"89609" "分析称Verizon或出钱阻止竞争对手运营iPhone" "资讯" "c(\"iphone\", \"android\", \"黑莓\", \"网络\", \"verizon\")" NA "V" "Verizon"
"89610" "诺基亚聘请前Verizon副总裁为首席营销官" "资讯" "c(\"工作\", \"咨询\", \"微软\", \"verizon\", \"诺基亚\")" NA "V" "Verizon"
"89611" "Android全球市场份额暴增至25.5%，跃居全球第二" "资讯" "c(\"2010\", \"手机操作系统\", \"verizon\", \"手机\", \"android\")" NA "V" "Verizon"
"89612" "Facebook占据美国显示广告市场近四分之一份额" "资讯" "c(\"2010\", \"微软\", \"verizon\", \"facebook\", \"android\")" NA "V" "Verizon"
"89613" "Facebook在地理位置服务市场动作频繁" "资讯" "c(\"verizon\", \"手机\", \"地理位置\", \"facebook\", \"市场\")" NA "V" "Verizon"
"89614" "谷歌CEO：Android应用商店多多益善" "资讯" "c(\"verizon\", \"电话\", \"应用商店\", \"谷歌\", \"android\")" NA "V" "Verizon"
"89615" "Gmail网络电话日呼叫量破百万" "资讯" "c(\"verizon\", \"手机\", \"gmail\", \"电话\", \"网络\")" NA "V" "Verizon"
"89616" "消息称Google将于11月26推平板电脑" "资讯" "c(\"chrome\", \"htc\", \"存储\", \"verizon\", \"网络\")" NA "V" "Verizon"
"89617" "WiMAX沦陷之说是误解 美国仍是市场主导" "资讯" "c(\"verizon\", \"思科\", \"网络\", \"英特尔\", \"wimax\")" NA "V" "Verizon"
"89618" "Android 2.2 (Froyo) 源码已经公布" "资讯" "c(\"google\", \"verizon\", \"exchange\", \"浏览器\", \"android\")" NA "V" "Verizon"
"89619" "T-Mobile美国公司CEO将离职" "资讯" "c(\"电信\", \"mobile\", \"verizon\", \"t-mobile\", \"android\")" NA "V" "Verizon"
"89620" "云计算时代电信运营商的挑战" "资讯" "c(\"verizon\", \"service\", \"数据中心\", \"电信\", \"云计算\")" NA "V" "Verizon"
"89621" "竞争再度升级 智能手机陷“专利大战”" "资讯" "c(\"产品\", \"verizon\", \"手机\", \"专利\", \"智能手机\")" NA "V" "Verizon"
"89622" "NPD：Android美国市场份额第一季首超iPhone" "资讯" "c(\"网络\", \"黑莓\", \"verizon\", \"android\", \"android，智能手机\")" NA "V" "Verizon"
"89623" "印度软件外包商觊觎中移动巨额订单" "资讯" "c(\"咨询\", \"电信\", \"verizon\", \"中移动，外包，印度\", \"服务器\")" NA "V" "Verizon"
"89624" "Verizon和Novell推出基于云的安全解决方案" "资讯" "c(\"网络\", \"产品\", \"云计算\", \"数据中心\", \"企业应用\")" NA "V" "Verizon"
"89625" "苹果证实iPad存在Wi-Fi连接问题 提出建议" "资讯" "c(\"verizon\", \"加密\", \"wi-fi\", \"ipad\", \"苹果\")" NA "V" "Verizon"
"89626" "Verizon将于明年年中推出4G手机 今年年底上LTE" "资讯" "c(\"智能手机\", \"Verizon\", \"Sprint\", \"LTE\", \"4G\")" NA "V" "Verizon"
"89627" "Palm或将于明日发布WebOS 1.4固件更新" "资讯" "c(\"webos\", \"verizon\", \"palm pre\", \"智能手机\", \"palm\")" NA "V" "Verizon"
"89628" "惠普正式开放新加坡云计算实验室" "资讯" "c(\"数据中心\", \"惠普，云计算实验室，ci\", \"verizon\", \"平台\", \"云计算\")" NA "V" "Verizon"
"89629" "农历新年 Palm暂停在华生产智能手机本月底恢复" "资讯" "c(\"verizon\", \"产品\", \"手机\", \"智能手机\", \"palm\")" NA "V" "Verizon"
"89630" "AT&T推其它手机 应对iPhone独家运营权结束" "资讯" "c(\"苹果\", \"AT&amp;T\", \"iPhone\", \"CDMA\", \"Verizon\")" NA "V" "Verizon"
"89631" "苹果平板电脑掀热潮 对手抢搭顺风车趁势挺进市场" "资讯" "c(\"spring\", \"verizon\", \"facebook\", \"手机\", \"英特尔\")" NA "V" "Verizon"
"89632" "苹果平板电脑是大号iPhone 用户界面美观" "资讯" "c(\"微软\", \"verizon\", \"平板电脑\", \"iphone\", \"苹果\")" NA "V" "Verizon"
"89633" "外媒预测苹果平板电脑必将失败：有5大原因" "资讯" "c(\"产品\", \"verizon\", \"手机\", \"alpha\", \"平板电脑，苹果，seek\")" NA "V" "Verizon"
"89634" "微软必应成为Verizon智能手机独家搜索引擎" "资讯" "c(\"产品\", \"浏览器\", \"verizon\", \"手机\", \"微软\")" NA "V" "Verizon"
"89635" "Verizon暗示明年运营iPhone 网络已准备就绪" "资讯" "c(\"iphone\", \"网络\", \"phone\", \"verizon\", \"苹果\")" NA "V" "Verizon"
"89636" "2010年苹果将与Verizon合作 可能性70%" "资讯" "c(\"苹果\", \"AT&amp;T\", \"iPhone\", \"Verizon\", \"苹果\")" NA "V" "Verizon"
"89637" "分析师称苹果将放弃AT&T 转投Verizon" "资讯" "c(\"iphone\", \"2010\", \"at&t\", \"verizon\", \"at&t，verizon\")" NA "V" "Verizon"
"89638" "Verizon高管：运营iPhone理所当然不足为奇" "资讯" "c(\"苹果\", \"AT&amp;T\", \"iPhone\", \"CDMA\", \"Verizon\")" NA "V" "Verizon"
"89639" "传苹果为Verizon开发CDMA手机 明年Q3上市" "资讯" "c(\"苹果\", \"AT&amp;T\", \"iPhone\", \"CDMA\", \"Verizon\")" NA "V" "Verizon"
"89640" "Verizon Wireless与谷歌宣布将联合推出Android手机" "资讯" "c(\"Android\", \"谷歌\", \"三星\", \"Verizon\", \"Verizon Wire\")" NA "V" "Verizon"
"89641" "Verizon携手谷歌研发Android平台手机应用" "资讯" "c(\"平台\", \"verizon\", \"android\", \"手机\", \"Verizon Wire\")" NA "V" "Verizon"
"89642" "CFI报告：iPhone用户满意度高于Android和Pre" "资讯" "c(\"verizon\", \"手机\", \"iphone\", \"palm pre\", \"android\")" NA "V" "Verizon"
"89643" "AT-T和Verizon斥资数亿美元进军移动业务" "资讯" "c(\"智能手机\", \"索尼\", \"AT&amp;T\", \"T-Mobile\", \"Verizon\")" NA "V" "Verizon"
"89644" "美国联邦通信委员会下周公布开放互联网计划" "资讯" "c(\"google\", \"网络\", \"verizon\", \"互联网\", \"Verizon\")" NA "V" "Verizon"
"89645" "Ophone应用商品在移动应用商店初期实行零资费" "资讯" "c(\"verizon\", \"internet\", \"互联网\", \"中国移动\", \"ophone\")" NA "V" "Verizon"
"89646" "Verizon推Vcast应用软件商店 加入挑战苹果行列" "资讯" "c(\"android\", \"平台\", \"微软\", \"google\", \"网络应用\")" NA "V" "Verizon"
"89647" "Google拟做大智能电网服务 协助监测能源使用" "资讯" "c(\"制造\", \"verizon\", \"电信\", \"网络\", \"google\")" NA "V" "Verizon"
"89648" "美知名博客五大理由驳苹果收购Twitter传闻" "资讯" "c(\"verizon\", \"facebook\", \"微软\", \"互联网\", \"twitter\")" NA "V" "Verizon"
"89649" "Verizon正与苹果谈判 iPhone或推CDMA版本" "资讯" "c(\"Verizon\", \"iPhone手机\", \"iPhone\", \"苹果\", \"twitter\")" NA "V" "Verizon"
"89650" "在Visual Studio 2010中使用版本控制" "极客头条" "c(\"visual studio 2010\", \"版本控制\", \"iPhone\", \"苹果\", \"twitter\")" "johnhany" "V" "Visual Studio 2010"
"89651" "Python已成美国顶尖高校中最受欢迎的入门编程语言" "资讯" "c(\"编程语言\", \"python\", \"visual basic\", \"生态系统\", \"网络编程\")" NA "V" "Visual Basic"
"89652" "微软实际行动回归开发者为中心 拥抱全平台开发者" "资讯" "c(\"asp.net\", \"visual studio\", \".net\", \"微软\", \"开源\")" NA "V" "Visual Studio"
"89653" "Matlab通过mex调用CUDA的方法" "极客头条" "c(\"matlab\", \"cuda\", \"visual studio\", \"mex\", \"开源\")" "bendanban" "V" "Visual Studio"
"89654" "AWS Elastic Beanstalk" "资讯" "c(\"visual studio\", \"amazon ec2\", \"aws\", \"mex\", \"开源\")" NA "V" "Visual Studio"
"89655" "TypeScript 1.5发布，支持大量ES6新特性" "资讯" "c(\"visual studio\", \"javascript\", \"ES6\", \"TypeScript 1.5\", \"开源\")" NA "V" "Visual Studio"
"89656" "从Build 2015说起：微软不是缺兵少将的“西蜀”，或在物联网时代复兴" "资讯" "c(\"物联网\", \"微软\", \"移动互联网\", \"云计算平台\", \"开发人员\")" NA "V" "Visual Studio"
"89657" "TIOBE 2015年5月编程语言排行榜：微软系语言份额上升" "资讯" "c(\"编程语言\", \"tiobe\", \"visual studio\", \"搜索引擎\", \"程序员\")" NA "V" "Visual Studio"
"89658" "微软新Visual Studio Code开发工具支持Mac和Linux" "资讯" "c(\"微软\", \"编辑器\", \"编码\", \"visual studio\", \"开发工具\")" NA "V" "Visual Studio"
"89659" ".NET开源决策者潘正磊：什么样的成功情境才是开源的成果" "资讯" "c(\"潘正磊\", \"开源\", \".net\", \"开源软件\", \"visual studio\")" NA "V" "Visual Studio"
"89660" "微软开源Visual Studio构建工具MSBuild" "资讯" "c(\"visual studio\", \"微软\", \"开源\", \"MSBuild\", \"visual studio\")" NA "V" "Visual Studio"
"89661" "微软开源版ASP.NET 5支持Linux构建程序" "资讯" "c(\"微软\", \"开源\", \"asp.net\", \"linux\", \"visual studio\")" NA "V" "Visual Studio"
"89662" "面向WP和Android！微软车库发布多款免费应用" "资讯" "c(\"移动应用\", \"微软\", \"免费\", \"Android\", \"Windows Phone\")" NA "V" "Visual Studio"
"89663" ".NET开发者必备的工具箱" "资讯" "c(\"开发工具\", \".NET\", \"Visual Studio\", \"API\", \"dotPeek\")" NA "V" "Visual Studio"
"89664" "微软收购跨平台移动开发工具套件HockeyApp" "资讯" "c(\"微软\", \"收购\", \"跨平台\", \"移动开发工具\", \"HockeyApp\")" NA "V" "Visual Studio"
"89665" "使用Visual Studio 进行SQL Server源代码管理和部署" "极客头条" "c(\"visual studio\", \"sql server\", \"管理\", \"源代码\", \"HockeyApp\")" "yxy1992_123" "V" "Visual Studio"
"89666" "盘点VS2015 预览版的5个新特性" "资讯" "c(\"Visual Studio\", \"IDE\", \"微软\", \"源代码\", \"HockeyApp\")" NA "V" "Visual Studio"
"89667" "第一个IDE稳定版本：Google发布Android Studio 1.0" "资讯" "c(\"Android Studio 1.0\", \"Google\", \"Visual Studio\", \"开发者\", \"应用\")" NA "V" "Visual Studio"
"89668" "5个难以置信的VS 2015预览版新特性" "极客头条" "c(\"Visual Studio\", \"Google\", \"Visual Studio\", \"开发者\", \"应用\")" "yxy1992_123" "V" "Visual Studio"
"89669" "Compiling Java in Visual Studio" "极客头条" "c(\"java\", \"visual studio\", \"Visual Studio\", \"开发者\", \"应用\")" "liuzhuoran1110" "V" "Visual Studio"
"89670" "详解Visual Studio Emulator for Android，微软的Mobile First！" "资讯" "c(\"移动开发\", \"Android\", \"微软\", \"iOS\", \".NET\")" NA "V" "Visual Studio"
"89671" "开发者工具Visual Studio 2013 Update 4 RC已开放下载" "极客头条" "c(\"Visual Studio\", \"开发者\", \"编程\", \"iOS\", \".NET\")" "qiansg123" "V" "Visual Studio"
"89672" "不用Visual Studio，5分钟轻松实现一张报表" "极客头条" "c(\"Visual Studio\", \"报表\", \"编程\", \"iOS\", \".NET\")" "yxy1992_123" "V" "Visual Studio"
"89673" "Visual Studio 14最新版免费下载" "极客头条" "c(\"Visual Studio\", \"报表\", \"编程\", \"iOS\", \".NET\")" "qiansg123" "V" "Visual Studio"
"89674" "微软推Bing开发助理 能帮VS开发者快速找到代码片段和示例" "资讯" "c(\"Visual Studio\", \"微软\", \"Bing开发助理\", \"搜索\", \"Bing\")" NA "V" "Visual Studio"
"89675" "跨平台开发如何事半功倍 Xamarin推出免费培训" "资讯" "c(\"跨平台\", \"Xamarin\", \"C#\", \"visual studio\", \".net framework\")" NA "V" "Visual Studio"
"89676" "UnityVS的开发商SyntaxTree被微软收购 今后开放下载" "资讯" "c(\"微软\", \"SyntaxTree\", \"Visual Studio\", \"开发者\", \"收购\")" NA "V" "Visual Studio"
"89677" "微软被传收购Xamarin 强势推进移动新战略" "资讯" "c(\"移动开发者\", \"跨平台\", \"Xamarin\", \"CSDN\", \"C#\")" NA "V" "Visual Studio"
"89678" "PTVS 2.1 Beta版发布 Visual Studio的Python工具" "资讯" "c(\"visual studio\", \"python\", \"PTVS\", \"Django\", \"开源\")" NA "V" "Visual Studio"
"89679" "微软Build2014大会第二天干货总结 Microsoft Azure拥抱Puppet、Chef、MongoDB..." "资讯" "c(\"微软\", \"puppet\", \"chef\", \"azure\", \"visual studio\")" NA "V" "Visual Studio"
"89680" "微软Build2014第一天应了解的15件事" "资讯" "c(\"微软\", \"Build大会\", \"windows\", \"windows phone\", \"Visual Studio\")" NA "V" "Visual Studio"
"89681" "TypeScript1.0发布，完美支持Visual Studio系列产品" "资讯" "c(\"typescript\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" NA "V" "Visual Studio"
"89682" "微软BUILD 2014大会发布了Visusal Studio 2013 Update 2" "极客头条" "c(\"Visual Studio\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" "jiangtao" "V" "Visual Studio"
"89683" "微软Build2014第一天要点精华汇总（组图）" "资讯" "c(\"微软\", \"windows 8.1\", \"windows\", \"ie11\", \"操作系统\")" NA "V" "Visual Studio"
"89684" "好玩，用Visual Studio构建和修改Linux内核" "极客头条" "c(\"Linux内核\", \"Visual Studio\", \"windows\", \"ie11\", \"操作系统\")" "liujiangce" "V" "Visual Studio"
"89685" "SAP携手Xamarin和Service2Media 提供移动应用开发框架" "资讯" "c(\"SAP\", \"应用开发\", \"移动平台\", \"Xamarin\", \"visual studio\")" NA "V" "Visual Studio"
"89686" "Visual Studio的八个调试建议：像老大哥一样调试" "极客头条" "c(\"visual studio\", \"调试\", \"移动平台\", \"Xamarin\", \"visual studio\")" "u011106205" "V" "Visual Studio"
"89687" "程序员的福音：微软推VS2013扩展Bing Code Search" "资讯" "c(\"扩展\", \"Microsoft\", \"开发环境\", \"程序员\", \"Visual Studio\")" NA "V" "Visual Studio"
"89688" "Android++：为Android App开发而生的Visual Studio的原生扩展" "极客头条" "c(\"visual studio\", \"android\", \"app\", \"扩展\", \"Visual Studio\")" "u011106205" "V" "Visual Studio"
"89689" "“详解Visual Studio 2013”全国巡讲北京站：无忧开发iOS及Android应用" "资讯" "c(\"visual studio\", \"C#\", \"CSDN\", \"移动开发者\", \"Xamarin\")" NA "V" "Visual Studio"
"89690" "微软潘正磊谈DevOps、Visual Studio 2013新功能、.NET未来" "资讯" "c(\"潘正磊\", \"微软\", \"windows azure\", \"windows phone\", \"Visual Studio\")" NA "V" "Visual Studio"
"89691" "IE11中全新增强的F12开发人员工具" "资讯" "c(\"微软\", \"visual studio\", \"IE\", \"IE11\", \"浏览器\")" NA "V" "Visual Studio"
"89692" "将Visual Studio打造成为Node.js IDE" "资讯" "c(\"微软\", \"visual studio\", \"NTVS\", \"Node.js\", \"开源\")" NA "V" "Visual Studio"
"89693" "TUP第30期：微软资深专家论如何用Visual Studio开发iOS、Android应用" "资讯" "c(\"tup\", \"visual studio\", \"移动开发者\", \"Xamarin\", \"MSDN\")" NA "V" "Visual Studio"
"89694" "[TUP第30期]直击移动应用开发难点  探讨跨平台最佳解决方案" "资讯" "c(\"tup\", \"CSDN\", \"visual studio\", \"移动开发\", \"开发工具\")" NA "V" "Visual Studio"
"89695" "libgit2：纯C语言实现的Git开发包" "资讯" "c(\"git\", \"stackoverflow\", \"visual studio\", \"开源\", \"libgit2\")" NA "V" "Visual Studio"
"89696" "在Visual Studio中使用JavaScript、HTML5打造跨平台移动应用" "极客头条" "c(\"Visual Studio\", \"原生应用\", \"JavaScript\", \"跨平台\", \"Icenium\")" "tangxiaoyin" "V" "Visual Studio"
"89697" "Windows 8.1和Visual Studio 2013正式发布" "极客头条" "c(\"Visual Studio\", \"Windows\", \"微软\", \"跨平台\", \"Icenium\")" "lispython" "V" "Visual Studio"
"89698" "微软隐藏最深的秘密武器之一——Visual Studio可作为Python IDE" "资讯" "c(\"微软\", \"Python\", \"Visual Studio\", \"Django\", \"PTVS\")" NA "V" "Visual Studio"
"89699" "Visual Studio 2013 Preview和.NET 4.5.1同时发布 支持Win 8.1应用开发" "资讯" "c(\".NET\", \"Visual Studio\", \"微软\", \"Build 2013\", \"PTVS\")" NA "V" "Visual Studio"
"89700" "iOS版本分布图 vs Android版本分布图，93%的iOS用户使用iOS 6，5%还在iOS 5。 Android版本分裂 严重，4.1版本以上仅有33%，4.1 Jelly Bean是和iOS 6去年夏天同期发布的，4.0是和iOS 5同期发布的。而且这个统计还不包括中国android手机厂商（因为不支持google services）" "极客头条" "c(\"Android\", \"iOS\", \"发布\", \"手机\", \"Google\")" "jiangtao" "V" "Visual Studio"
"89701" "Visual Studio 2013 Preview新功能预览" "资讯" "c(\"Visual Studio\", \"TFS\", \"微软\", \"手机\", \"Google\")" NA "V" "Visual Studio"
"89702" "主流编译器对C++11的支持现状比较" "资讯" "c(\"C++\", \"编译器\", \"Clang\", \"Visual Studio\", \"C++11\")" NA "V" "Visual Studio"
"89703" "Amazon VPC" "资讯" "c(\"数据库\", \"vpn\", \"amazon ec2\", \"aws\", \"C++11\")" NA "V" "VPN"
"89704" "Linux 系统下使用 PPTP 设置自己的 VPN（英）" "极客头条" "c(\"VPN\", \"PPTP\", \"linux\", \"aws\", \"C++11\")" "specs_" "V" "VPN"
"89705" "【CSDN在线培训Q/A】AWS VPC简介与网络架构设计" "资讯" "c(\"aws\", \"VPC\", \"peering connection\", \"VPN\", \"虚拟专用网络\")" NA "V" "VPN"
"89706" "DigitalOcean VPS 上如何安装 VPN" "极客头条" "c(\"vpn\", \"DigitalOcean\", \"vps\", \"VPN\", \"虚拟专用网络\")" "u010037918" "V" "VPN"
"89707" "防不胜防：插线板实为黑客工具 可短信控制" "资讯" "c(\"SSH\", \"HTTP\", \"安全\", \"Linux\", \"VPN\")" NA "V" "VPN"
"89708" "Facebook在欧洲中东非洲出现大面积故障" "资讯" "c(\"twitter\", \"facebook\", \"故障\", \"vpn\", \"服务器\")" NA "V" "VPN"
"89709" "虚拟化的另一个用例：真正的VPN" "资讯" "c(\"vpn\", \"虚拟化\", \"故障\", \"vpn\", \"服务器\")" NA "V" "VPN"
"89710" "讲述VPN技术分析探讨隧道技术三层协议" "资讯" "c(\"服务器\", \"authenticati\", \"网络协议\", \"vpn\", \"encryption\")" NA "V" "VPN"
"89711" "揭开SSL VPN的六大行业“迷局”！" "资讯" "c(\"ssl\", \"vpn\", \"中国移动\", \"财务系统\", \"远程登录\")" NA "V" "VPN"
"89712" "Amazon.com推出beta测试版虚拟私有云计算服务" "资讯" "c(\"vpn\", \"网络\", \"oracle\", \"测试\", \"云计算\")" NA "V" "VPN"
"89713" "思科斥资1.83亿美元收购网络安全公司ScanSafe" "资讯" "c(\"vpn\", \"2010\", \"金山\", \"网络\", \"思科\")" NA "V" "VPN"
"89714" "Array SSL VPN中标同仁堂，百年老店实现远程安全接入" "资讯" "c(\"电信\", \"产品\", \"负载均衡\", \"ssl\", \"金融\")" NA "V" "VPN"
"89715" "Android Donut升级已发，支持多点触摸且提速" "资讯" "c(\"vpn\", \"git\", \"android\", \"donut\", \"google\")" NA "V" "VPN"
"89716" "攻击韩美网络最新源头定位于美国迈阿密" "资讯" "c(\"服务器\", \"vpn\", \"工具\", \"数据中心\", \"网络\")" NA "V" "VPN"
"89717" "Kerio的VPN服务器" "资讯" "c(\"network\", \"database\", \"防火墙\", \"authenticati\", \"vpn\")" NA "V" "VPN"
"89718" "ISA教程：用ISA2006搭建VPN服务器" "资讯" "c(\"通讯\", \"加密\", \"互联网\", \"dns服务器\", \"vpn\")" NA "V" "VPN"
"89719" "技巧：30分钟打造Linux的VPN服务器" "资讯" "c(\"防火墙\", \"microsoft\", \"linux内核\", \"encryption\", \"vpn\")" NA "V" "VPN"
"89720" "金融危机下 如何看待SMB安全变化" "资讯" "c(\"vpn\", \"网络\", \"优化\", \"manager\", \"产品\")" NA "V" "VPN"
"89721" "Visual Studio 2012完美的拥抱GitHub" "极客头条" "c(\"visual studio 2012\", \"github\", \"优化\", \"manager\", \"产品\")" "u013726302" "V" "Visual Studio 2012"
"89722" "VirtualBox答疑解惑" "极客头条" "c(\"virtualbox\", \"github\", \"优化\", \"manager\", \"产品\")" "pike0002" "V" "virtualbox"
"89723" "想在VirtualBox上装64位操作系统吗" "极客头条" "c(\"virtualbox\", \"64位\", \"操作系统\", \"manager\", \"产品\")" "pike0002" "V" "virtualbox"
"89724" "VirtualBox 4.0 正式版发布" "资讯" "c(\"虚拟化\", \"开发工具\", \"数据中心\", \"发布\", \"virtualbox\")" NA "V" "virtualbox"
"89725" "VirtualBox 3.2.12 Final发布" "资讯" "c(\"performance\", \"virtualbox\", \"networking\", \"asynchronous\", \"发布\")" NA "V" "virtualbox"
"89726" "Oracle VM VirtualBox 3.2.0 Beta 1 放出" "资讯" "c(\"Oracle\", \"VM\", \"VirtualBox\", \"开源虚拟机\", \"发布\")" NA "V" "virtualbox"
"89727" "VirtualBox 3.0.2 正式版发布" "资讯" "c(\"virtualbox\", \"软件\", \"sun\", \"linux\", \"发布\")" NA "V" "virtualbox"
"89728" "VirtualBox 3.0.0 Beta 2发布" "资讯" "c(\"virtualbox\", \"软件\", \"sun\", \"linux\", \"发布\")" NA "V" "virtualbox"
"89729" "VirtualBox 2.2.2版本发布" "资讯" "c(\"文档\", \"server\", \"虚拟机\", \"sun\", \"virtualbox\")" NA "V" "virtualbox"
"89730" "微软实际行动回归开发者为中心 拥抱全平台开发者" "资讯" "c(\"asp.net\", \"visual studio\", \".net\", \"微软\", \"开源\")" NA "V" "Visual Studio"
"89731" "Matlab通过mex调用CUDA的方法" "极客头条" "c(\"matlab\", \"cuda\", \"visual studio\", \"mex\", \"开源\")" "bendanban" "V" "Visual Studio"
"89732" "AWS Elastic Beanstalk" "资讯" "c(\"visual studio\", \"amazon ec2\", \"aws\", \"mex\", \"开源\")" NA "V" "Visual Studio"
"89733" "TypeScript 1.5发布，支持大量ES6新特性" "资讯" "c(\"visual studio\", \"javascript\", \"ES6\", \"TypeScript 1.5\", \"开源\")" NA "V" "Visual Studio"
"89734" "从Build 2015说起：微软不是缺兵少将的“西蜀”，或在物联网时代复兴" "资讯" "c(\"物联网\", \"微软\", \"移动互联网\", \"云计算平台\", \"开发人员\")" NA "V" "Visual Studio"
"89735" "TIOBE 2015年5月编程语言排行榜：微软系语言份额上升" "资讯" "c(\"编程语言\", \"tiobe\", \"visual studio\", \"搜索引擎\", \"程序员\")" NA "V" "Visual Studio"
"89736" "微软新Visual Studio Code开发工具支持Mac和Linux" "资讯" "c(\"微软\", \"编辑器\", \"编码\", \"visual studio\", \"开发工具\")" NA "V" "Visual Studio"
"89737" ".NET开源决策者潘正磊：什么样的成功情境才是开源的成果" "资讯" "c(\"潘正磊\", \"开源\", \".net\", \"开源软件\", \"visual studio\")" NA "V" "Visual Studio"
"89738" "微软开源Visual Studio构建工具MSBuild" "资讯" "c(\"visual studio\", \"微软\", \"开源\", \"MSBuild\", \"visual studio\")" NA "V" "Visual Studio"
"89739" "微软开源版ASP.NET 5支持Linux构建程序" "资讯" "c(\"微软\", \"开源\", \"asp.net\", \"linux\", \"visual studio\")" NA "V" "Visual Studio"
"89740" "面向WP和Android！微软车库发布多款免费应用" "资讯" "c(\"移动应用\", \"微软\", \"免费\", \"Android\", \"Windows Phone\")" NA "V" "Visual Studio"
"89741" ".NET开发者必备的工具箱" "资讯" "c(\"开发工具\", \".NET\", \"Visual Studio\", \"API\", \"dotPeek\")" NA "V" "Visual Studio"
"89742" "微软收购跨平台移动开发工具套件HockeyApp" "资讯" "c(\"微软\", \"收购\", \"跨平台\", \"移动开发工具\", \"HockeyApp\")" NA "V" "Visual Studio"
"89743" "使用Visual Studio 进行SQL Server源代码管理和部署" "极客头条" "c(\"visual studio\", \"sql server\", \"管理\", \"源代码\", \"HockeyApp\")" "yxy1992_123" "V" "Visual Studio"
"89744" "盘点VS2015 预览版的5个新特性" "资讯" "c(\"Visual Studio\", \"IDE\", \"微软\", \"源代码\", \"HockeyApp\")" NA "V" "Visual Studio"
"89745" "第一个IDE稳定版本：Google发布Android Studio 1.0" "资讯" "c(\"Android Studio 1.0\", \"Google\", \"Visual Studio\", \"开发者\", \"应用\")" NA "V" "Visual Studio"
"89746" "5个难以置信的VS 2015预览版新特性" "极客头条" "c(\"Visual Studio\", \"Google\", \"Visual Studio\", \"开发者\", \"应用\")" "yxy1992_123" "V" "Visual Studio"
"89747" "Compiling Java in Visual Studio" "极客头条" "c(\"java\", \"visual studio\", \"Visual Studio\", \"开发者\", \"应用\")" "liuzhuoran1110" "V" "Visual Studio"
"89748" "详解Visual Studio Emulator for Android，微软的Mobile First！" "资讯" "c(\"移动开发\", \"Android\", \"微软\", \"iOS\", \".NET\")" NA "V" "Visual Studio"
"89749" "开发者工具Visual Studio 2013 Update 4 RC已开放下载" "极客头条" "c(\"Visual Studio\", \"开发者\", \"编程\", \"iOS\", \".NET\")" "qiansg123" "V" "Visual Studio"
"89750" "不用Visual Studio，5分钟轻松实现一张报表" "极客头条" "c(\"Visual Studio\", \"报表\", \"编程\", \"iOS\", \".NET\")" "yxy1992_123" "V" "Visual Studio"
"89751" "Visual Studio 14最新版免费下载" "极客头条" "c(\"Visual Studio\", \"报表\", \"编程\", \"iOS\", \".NET\")" "qiansg123" "V" "Visual Studio"
"89752" "微软推Bing开发助理 能帮VS开发者快速找到代码片段和示例" "资讯" "c(\"Visual Studio\", \"微软\", \"Bing开发助理\", \"搜索\", \"Bing\")" NA "V" "Visual Studio"
"89753" "跨平台开发如何事半功倍 Xamarin推出免费培训" "资讯" "c(\"跨平台\", \"Xamarin\", \"C#\", \"visual studio\", \".net framework\")" NA "V" "Visual Studio"
"89754" "UnityVS的开发商SyntaxTree被微软收购 今后开放下载" "资讯" "c(\"微软\", \"SyntaxTree\", \"Visual Studio\", \"开发者\", \"收购\")" NA "V" "Visual Studio"
"89755" "微软被传收购Xamarin 强势推进移动新战略" "资讯" "c(\"移动开发者\", \"跨平台\", \"Xamarin\", \"CSDN\", \"C#\")" NA "V" "Visual Studio"
"89756" "PTVS 2.1 Beta版发布 Visual Studio的Python工具" "资讯" "c(\"visual studio\", \"python\", \"PTVS\", \"Django\", \"开源\")" NA "V" "Visual Studio"
"89757" "微软Build2014大会第二天干货总结 Microsoft Azure拥抱Puppet、Chef、MongoDB..." "资讯" "c(\"微软\", \"puppet\", \"chef\", \"azure\", \"visual studio\")" NA "V" "Visual Studio"
"89758" "微软Build2014第一天应了解的15件事" "资讯" "c(\"微软\", \"Build大会\", \"windows\", \"windows phone\", \"Visual Studio\")" NA "V" "Visual Studio"
"89759" "TypeScript1.0发布，完美支持Visual Studio系列产品" "资讯" "c(\"typescript\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" NA "V" "Visual Studio"
"89760" "微软BUILD 2014大会发布了Visusal Studio 2013 Update 2" "极客头条" "c(\"Visual Studio\", \"微软\", \"开发人员\", \"eclipse\", \"javascript\")" "jiangtao" "V" "Visual Studio"
"89761" "微软Build2014第一天要点精华汇总（组图）" "资讯" "c(\"微软\", \"windows 8.1\", \"windows\", \"ie11\", \"操作系统\")" NA "V" "Visual Studio"
"89762" "好玩，用Visual Studio构建和修改Linux内核" "极客头条" "c(\"Linux内核\", \"Visual Studio\", \"windows\", \"ie11\", \"操作系统\")" "liujiangce" "V" "Visual Studio"
"89763" "SAP携手Xamarin和Service2Media 提供移动应用开发框架" "资讯" "c(\"SAP\", \"应用开发\", \"移动平台\", \"Xamarin\", \"visual studio\")" NA "V" "Visual Studio"
"89764" "Visual Studio的八个调试建议：像老大哥一样调试" "极客头条" "c(\"visual studio\", \"调试\", \"移动平台\", \"Xamarin\", \"visual studio\")" "u011106205" "V" "Visual Studio"
"89765" "程序员的福音：微软推VS2013扩展Bing Code Search" "资讯" "c(\"扩展\", \"Microsoft\", \"开发环境\", \"程序员\", \"Visual Studio\")" NA "V" "Visual Studio"
"89766" "Android++：为Android App开发而生的Visual Studio的原生扩展" "极客头条" "c(\"visual studio\", \"android\", \"app\", \"扩展\", \"Visual Studio\")" "u011106205" "V" "Visual Studio"
"89767" "“详解Visual Studio 2013”全国巡讲北京站：无忧开发iOS及Android应用" "资讯" "c(\"visual studio\", \"C#\", \"CSDN\", \"移动开发者\", \"Xamarin\")" NA "V" "Visual Studio"
"89768" "微软潘正磊谈DevOps、Visual Studio 2013新功能、.NET未来" "资讯" "c(\"潘正磊\", \"微软\", \"windows azure\", \"windows phone\", \"Visual Studio\")" NA "V" "Visual Studio"
"89769" "IE11中全新增强的F12开发人员工具" "资讯" "c(\"微软\", \"visual studio\", \"IE\", \"IE11\", \"浏览器\")" NA "V" "Visual Studio"
"89770" "将Visual Studio打造成为Node.js IDE" "资讯" "c(\"微软\", \"visual studio\", \"NTVS\", \"Node.js\", \"开源\")" NA "V" "Visual Studio"
"89771" "TUP第30期：微软资深专家论如何用Visual Studio开发iOS、Android应用" "资讯" "c(\"tup\", \"visual studio\", \"移动开发者\", \"Xamarin\", \"MSDN\")" NA "V" "Visual Studio"
"89772" "[TUP第30期]直击移动应用开发难点  探讨跨平台最佳解决方案" "资讯" "c(\"tup\", \"CSDN\", \"visual studio\", \"移动开发\", \"开发工具\")" NA "V" "Visual Studio"
"89773" "libgit2：纯C语言实现的Git开发包" "资讯" "c(\"git\", \"stackoverflow\", \"visual studio\", \"开源\", \"libgit2\")" NA "V" "Visual Studio"
"89774" "在Visual Studio中使用JavaScript、HTML5打造跨平台移动应用" "极客头条" "c(\"Visual Studio\", \"原生应用\", \"JavaScript\", \"跨平台\", \"Icenium\")" "tangxiaoyin" "V" "Visual Studio"
"89775" "Windows 8.1和Visual Studio 2013正式发布" "极客头条" "c(\"Visual Studio\", \"Windows\", \"微软\", \"跨平台\", \"Icenium\")" "lispython" "V" "Visual Studio"
"89776" "微软隐藏最深的秘密武器之一——Visual Studio可作为Python IDE" "资讯" "c(\"微软\", \"Python\", \"Visual Studio\", \"Django\", \"PTVS\")" NA "V" "Visual Studio"
"89777" "Visual Studio 2013 Preview和.NET 4.5.1同时发布 支持Win 8.1应用开发" "资讯" "c(\".NET\", \"Visual Studio\", \"微软\", \"Build 2013\", \"PTVS\")" NA "V" "Visual Studio"
"89778" "iOS版本分布图 vs Android版本分布图，93%的iOS用户使用iOS 6，5%还在iOS 5。 Android版本分裂 严重，4.1版本以上仅有33%，4.1 Jelly Bean是和iOS 6去年夏天同期发布的，4.0是和iOS 5同期发布的。而且这个统计还不包括中国android手机厂商（因为不支持google services）" "极客头条" "c(\"Android\", \"iOS\", \"发布\", \"手机\", \"Google\")" "jiangtao" "V" "Visual Studio"
"89779" "Visual Studio 2013 Preview新功能预览" "资讯" "c(\"Visual Studio\", \"TFS\", \"微软\", \"手机\", \"Google\")" NA "V" "Visual Studio"
"89780" "主流编译器对C++11的支持现状比较" "资讯" "c(\"C++\", \"编译器\", \"Clang\", \"Visual Studio\", \"C++11\")" NA "V" "Visual Studio"
"89781" "在Visual Studio 2010中使用版本控制" "极客头条" "c(\"visual studio 2010\", \"版本控制\", \"Clang\", \"Visual Studio\", \"C++11\")" "johnhany" "V" "Visual Studio 2010"
"89782" "linux shell vim 常用命令小结" "极客头条" "c(\"linux\", \"shell\", \"vim\", \"Visual Studio\", \"C++11\")" "never_cxb" "V" "Vim"
"89783" "golang 环境配置建议" "极客头条" "c(\"golang\", \"vim\", \"docker\", \"Visual Studio\", \"C++11\")" "lijianying13" "V" "Vim"
"89784" "PHP工程师 VIM配置分享" "极客头条" "c(\"vim\", \"vi\", \"docker\", \"Visual Studio\", \"C++11\")" "wangyupeng129" "V" "Vim"
"89785" "Vim自动补全神器：YouCompleteMe" "极客头条" "c(\"vim\", \"vi\", \"docker\", \"Visual Studio\", \"C++11\")" "wenwen091100304" "V" "Vim"
"89786" "TypeGame: Vim中的打字游戏" "极客头条" "c(\"Vim\", \"游戏\", \"docker\", \"Visual Studio\", \"C++11\")" "sinat_17472915" "V" "Vim"
"89787" "实用手册：130+ 提高开发效率的 vim 常用命令" "极客头条" "c(\"vim\", \"游戏\", \"docker\", \"Visual Studio\", \"C++11\")" "frontfans" "V" "Vim"
"89788" "最漂亮和最强大的 Markdown 编辑器 Vim/Emacs 支持" "极客头条" "c(\"编辑器\", \"markdown\", \"vim\", \"emacs\", \"C++11\")" "arbiter" "V" "Vim"
"89789" "Vim中的语法检查-syntastic" "极客头条" "c(\"vim\", \"markdown\", \"vim\", \"emacs\", \"C++11\")" "notice520" "V" "Vim"
"89790" "Cmd Markdown 发布第七次更新 --- 击键的节奏（Vim/Emacs 支持）" "极客头条" "c(\"markdown\", \"发布\", \"cmd\", \"emacs\", \"vim\")" "arbiter" "V" "Vim"
"89791" "Vim 重复操作的利器--点命令" "极客头条" "c(\"vim\", \"发布\", \"cmd\", \"emacs\", \"vim\")" "notice520" "V" "Vim"
"89792" "每日vim插件--强大的自动补全neocomplete.vim和supertab" "极客头条" "c(\"插件\", \"vim\", \"cmd\", \"emacs\", \"vim\")" "notice520" "V" "Vim"
"89793" "每日vim插件--代码搜索ack.vim/ag/ctlsf.vim" "极客头条" "c(\"插件\", \"ack\", \"vim\", \"emacs\", \"vim\")" "notice520" "V" "Vim"
"89794" "每日vim插件--文件浏览器NERD Tree以及git-nerdtree,vim-nerdtree-tabs" "极客头条" "c(\"NERD Tree\", \"插件\", \"vim\", \"git\", \"vim\")" "notice520" "V" "Vim"
"89795" "每日vim插件--显示git diff:GitGutter.vim" "极客头条" "c(\"插件\", \"diff\", \"git\", \"vim\", \"vim\")" "notice520" "V" "Vim"
"89796" "VIM系列4——概念和技巧" "极客头条" "c(\"vim\", \"diff\", \"git\", \"vim\", \"vim\")" "chijianqiang" "V" "Vim"
"89797" "Vim 7.4发布" "极客头条" "c(\"发布\", \"Vim\", \"git\", \"vim\", \"vim\")" "liujiangce" "V" "Vim"
"89798" "Vim在线教程，适合初学者" "极客头条" "c(\"Vim\", \"Vim\", \"git\", \"vim\", \"vim\")" "chijianqiang" "V" "Vim"
"89799" "喜欢 Vim 里的 Powerline 吗? Emacs 也有!" "极客头条" "c(\"Vim\", \"Emacs\", \"git\", \"vim\", \"vim\")" "cloudsben" "V" "Vim"
"89800" "谁说Vim不是IDE？（四）" "资讯" "c(\"Vim\", \"IDE\", \"开发工具\", \"vim\", \"vim\")" NA "V" "Vim"
"89801" "谁说Vim不是IDE？（三）" "资讯" "c(\"IDE\", \"Vim\", \"开发工具\", \"vim\", \"vim\")" NA "V" "Vim"
"89802" "谁说Vim不是IDE？（二）" "资讯" "c(\"IDE\", \"Vim\", \"开发工具\", \"vim\", \"vim\")" NA "V" "Vim"
"89803" " 谁说Vim不是IDE？（一）" "资讯" "c(\"IDE\", \"Vim\", \"开发工具\", \"vim\", \"vim\")" NA "V" "Vim"
"89804" "游戏：Vim大冒险" "资讯" "c(\"游戏\", \"vim\", \"开发工具\", \"vim\", \"vim\")" NA "V" "Vim"
"89805" "迁移到Vim的10个难关" "资讯" "c(\"文档\", \"图形\", \"工作\", \"文本编辑\", \"vim\")" NA "V" "Vim"
"89806" "类Unix编程必备——Vim+tmux组合出你的专属IDE" "资讯" "c(\"unix\", \"编程\", \"ide\", \"tmux\", \"vim\")" NA "V" "Vim"
"89807" "[3月20日快讯精选]使用Tmux和Vim创建简单的IDE" "资讯" "c(\"windows phon\", \"web开发\", \"vim\", \"快讯精选\", \"linux内核\")" NA "V" "Vim"
"89808" "针对C/C++开发者的Vim插件" "资讯" "c(\"任务\", \"终端\", \"insert\", \"vim\", \"c/c++\")" NA "V" "Vim"
"89809" "给程序员的Vim速查卡" "资讯" "c(\"vim\", \"excel\", \"速查卡\", \"vim\", \"c/c++\")" NA "V" "Vim"
"89810" "简明Vim练级攻略" "资讯" "c(\"文档\", \"windows\", \"文本编辑\", \"练级攻略\", \"vim\")" NA "V" "Vim"
"89811" "Linux系统登录后自动执行应用程序" "资讯" "c(\"vim\", \"bash\", \"windows\", \"脚本\", \"linux\")" NA "V" "Vim"
"89812" "熟练掌握Linux下Vim编辑器的使用小技巧" "资讯" "c(\"邮件服务器\", \"文本编辑\", \"数据库服务器\", \"vim\", \"linux\")" NA "V" "Vim"
"89813" "LINUX下完美播放mplayer安装" "资讯" "c(\"gtk\", \"vim\", \"network\", \"redhat\", \"linux\")" NA "V" "Vim"
"89814" "《近匠》专访小熊尼奥：从软硬结合到IP合作，AR产品的机遇" "资讯" "c(\"Qualcomm\", \"AR\", \"小熊尼奥\", \"儿童教育\", \"智能硬件\")" NA "V" "vuforia"
"89815" "Qualcomm公司李申：Vuforia打破AR设备界线" "资讯" "c(\"Unity\", \"Qualcomm\", \"Vuforia\", \"AR\", \"智能眼镜\")" NA "V" "vuforia"
"89816" "《近匠》AR学校：从教育领域看增强现实机遇何在" "资讯" "c(\"AR学校\", \"赵良华\", \"AR\", \"VR\", \"Vuforia\")" NA "V" "vuforia"
"89817" "“扫描建模”速建AR应用  Vuforia 4.0 SDK更新" "资讯" "c(\"Qualcomm\", \"Vuforia\", \"AR\", \"Unity\", \"Android\")" NA "V" "vuforia"
"89818" "专访PopCap：AR是数字与物质世界的调和剂" "资讯" "c(\"移动游戏\", \"Popcap\", \"AR\", \"Qualcomm\", \"Vuforia\")" NA "V" "vuforia"
"89819" "Uplinq2014：亲身体验Vuforia与智能眼镜设备" "资讯" "c(\"Qualcomm\", \"Vuforia\", \"智能眼镜\", \"SDK\", \"Gear VR\")" NA "V" "vuforia"
"89820" "触摸未来：为什么说AR是未来最重要的人机界面？" "资讯" "c(\"AR\", \"Qualcomm\", \"人工智能\", \"Vuforia\", \"Gear VR\")" NA "V" "vuforia"
"89821" "实例亲授：教你如何创建AR应用" "资讯" "c(\"AR\", \"Vuforia\", \"Qualcomm\", \"Unity\", \"移动游戏\")" NA "V" "vuforia"
"89822" "学习的革命：AR增强现实遇到儿童应用" "资讯" "c(\"增强现实\", \"教育\", \"开发者\", \"移动应用\", \"Vuforia\")" NA "V" "vuforia"
"89823" "《近匠》LegendTech：AR技术现已加入15元豪华午餐" "资讯" "c(\"AR\", \"虚拟现实\", \"Vuforia\", \"Qualcomm\", \"近匠\")" NA "V" "vuforia"
"89824" "Vuforia 2014 视觉大奖赛：寻找最炫酷AR增强现实应用，迈向巅峰！" "资讯" "c(\"Vuforia\", \"Qualcomm \", \"大赛\", \"增强现实\", \"应用开发\")" NA "V" "vuforia"
"89825" "增强现实：10大AR应用窥探移动未来" "资讯" "c(\"AR\", \"移动游戏\", \"移动应用\", \"Vuforia\", \"Qualcomm\")" NA "V" "vuforia"
"89826" "Vuforia SDK全面更新：3.0版可实时生成虚拟场景和物体" "资讯" "c(\"Qualcomm\", \"Vuforia\", \"AR\", \"虚拟现实\", \"交互设计\")" NA "V" "vuforia"
"89827" "Vuforia SDK 3.0发布在即 全球注册开发者已逾10万" "资讯" "c(\"Qualcomm\", \"Vuforia\", \"游戏开发\", \"虚拟现实\", \"交互设计\")" NA "V" "vuforia"
"89828" "Android开发者不可或缺的四大工具" "资讯" "c(\"移动开发\", \"Android\", \"SDK\", \"Basic4Android\", \"Gimbal\")" NA "V" "vuforia"
"89829" "使用ATL创建简单ActiveX控件（一）  ——  创建项目" "极客头条" "c(\"c  \", \"activex\", \"vc\", \"ATL\", \"Gimbal\")" "testcs_dn" "V" "VC"
"89830" "100本c c++ vc学习资料" "极客头条" "c(\"C\", \"c++\", \"vc\", \"ATL\", \"Gimbal\")" "lancoder" "V" "VC"
"89831" "【畅言】没有关系的DS程序员们如何去创业？" "资讯" "c(\"畅言\", \"郝玉杰\", \"创业\", \"VC\", \"程序员\")" NA "V" "VC"
"89832" "创业教父Paul Graham谈创业投资趋势" "资讯" "c(\"创业公司\", \"VC\", \"融资\", \"创始人\", \"投资\")" NA "V" "VC"
"89833" "传奇VC马克.安德雷森：未来的企业什么样？" "资讯" "c(\"马克.安德雷森\", \"VC\", \"融资\", \"创始人\", \"投资\")" NA "V" "VC"
"89834" "云存储服务公司Box“抗击强敌” 将获新一轮融资" "资讯" "c(\"在线办公\", \"云计算\", \"Box\", \"VC\", \"投资\")" NA "V" "VC"
"89835" "美风投家评出10大VC：新算法基于联系和可信度" "资讯" "c(\"中兴\", \"算法\", \"vc\", \"风险投资\", \"投资\")" NA "V" "VC"
"89836" "VC写一个荣光医院修补弹坑游戏助手" "资讯" "c(\"游戏\", \"贾治国\", \"博客精选\", \"VC\", \"投资\")" NA "V" "VC"
"89837" "云之讯罗志坚：让每个应用插上通讯的翅膀，打造通讯生态圈！" "资讯" "c(\"云计算\", \"Voip\", \"博客精选\", \"VC\", \"投资\")" NA "V" "VOIP"
"89838" "中移动推网络电话Jego  后来者能否居上？" "资讯" "c(\"微信\", \"中国移动\", \"Jego\", \"VoIP\", \"投资\")" NA "V" "VOIP"
"89839" "VoIP领域新军：Google Voice联合创始人力推新产品" "资讯" "c(\"twitter\", \"产品\", \"voip\", \"voice\", \"google\")" NA "V" "VOIP"
"89840" "Google下个月关闭Gizmo5 VoIP服务" "资讯" "c(\"服务器\", \"浏览器\", \"google\", \"gizmo5\", \"voip\")" NA "V" "VOIP"
"89841" "Skype的云计划" "资讯" "c(\"数据库\", \"浏览器\", \"云计算\", \"voip\", \"html5\")" NA "V" "VOIP"
"89842" "Skype将发布3G版iPhone应用程序 音质堪比CD" "资讯" "c(\"应用程序\", \"苹果\", \"Skype\", \"iPhone\", \"VoIP\")" NA "V" "VOIP"
"89843" "iPhone SDK更新 允许VoIP软件在3G网络运行" "资讯" "c(\"SDK\", \"iPhone\", \"3G\", \"VoIP\", \"iCall\")" NA "V" "VOIP"
"89844" "托管VoIP服务十大关键问题" "资讯" "c(\"技术人\", \"数据中心\", \"企业应用\", \"voip\", \"托管\")" NA "V" "VOIP"
"89845" "Google收购百万电话号码 或即将推出语音服务" "资讯" "c(\"Google\", \"语音服务\", \"VoIP\", \"通信\", \"托管\")" NA "V" "VOIP"
"89846" "天霆云谈天霆：VDI竞争的核心是协议的竞争" "资讯" "c(\"云计算大会\", \"CCCC2015\", \"CHP\", \"VDI\", \"天霆云\")" NA "V" "VDI"
"89847" "中国网安张剑：提供带有安全的信息化产品" "资讯" "c(\"中国网安\", \"张剑\", \"VDI\", \"云安全\", \"CCCC2015\")" NA "V" "VDI"
"89848" "企业级App探索：开发者们的正途在哪里？" "资讯" "c(\"BYOD\", \"企业移动化\", \"VDI\", \"Citrix\", \"中间件\")" NA "V" "VDI"
"89849" "VMware发布Horizon Suite 三款应用打包折扣低" "资讯" "c(\"VMware\", \"VDI\", \"Horizon Suite\", \"Citrix\", \"中间件\")" NA "V" "VDI"
"89850" "OpenStack与Citrix VMware Microsoft在VDI市场上燃起新战火" "资讯" "c(\"VDI\", \"Microsoft\", \"VMware\", \"Citrix\", \"OpenStack\")" NA "V" "VDI"
"89851" "Oracle提供免费iPad版VDI应用" "资讯" "c(\"浏览器\", \"oracle\", \"encryption\", \"vdi\", \"ipad\")" NA "V" "VDI"
"89852" "2011年虚拟化展望：私有云和VDI方案" "资讯" "c(\"终端\", \"虚拟机\", \"vdi\", \"私有云\", \"虚拟化\")" NA "V" "VDI"
"89853" "我们应该向Vine学习什么" "资讯" "c(\"《程序员》杂志\", \"2014年3月刊\", \"Vine\", \"产品\", \"社交\")" NA "V" "vine"
"89854" "短视频的那些事" "资讯" "c(\"短视频\", \"移动互联网\", \"社交媒体\", \"视频网站\", \"产品\")" NA "V" "vine"
"89855" "2013年最值得关注的十大产品盘点" "资讯" "c(\"产品\", \"LiveCode\", \"PlayStation 4\", \"Almond+\", \"Chromecast\")" NA "V" "vine"
"89856" "Facebook为什么要推Instagram视频分享功能？" "资讯" "c(\"Facebook\", \"Instagram\", \"Twitter\", \"Vine\", \"视频\")" NA "V" "vine"
"89857" "不断抄袭的Facebook正逐步沦为一家普通的公司" "资讯" "c(\"Facebook\", \"Instagram\", \"Google\", \"Twitter\", \"Vine\")" NA "V" "vine"
"89858" "继文字、图片社交之后，移动视频分享领域即将起飞？" "资讯" "c(\"产品\", \"Facebook\", \"Twitter\", \"Viddy\", \"Socialcam\")" NA "V" "vine"
"89859" "微软宣布10月11日关闭社交通信服务Vine" "资讯" "c(\"互联网\", \"交通\", \"社交通信服务\", \"vine\", \"微软\")" NA "V" "vine"
"89860" "微软测试新服务Vine 整合Facebook用于灾难预警" "资讯" "c(\"互联网\", \"facebook\", \"测试\", \"微软\", \"vine\")" NA "V" "vine"
"89861" "参加全球开发者大调查，赢iPhone 6S！" "资讯" "c(\"VisionMobile\", \"调查\", \"生态系统\", \"编程语言\", \"开发人员\")" NA "V" "Visionmobile"
"89862" "全球开发者报告：Windows Phone已死，Windows 10长存" "资讯" "c(\"移动开发\", \"VisionMobile\", \"调查报告\", \"Android\", \"编程语言\")" NA "V" "Visionmobile"
"89863" "参加2015全球开发者大调查，赢iPhone 6！" "资讯" "c(\"VisionMobile\", \"编程语言\", \"物联网\", \"生态系统\", \"调查\")" NA "V" "Visionmobile"
"89864" "全球移动开发者报告：Swift崛起，物联网大火！" "资讯" "c(\"移动开发\", \"VisionMobile\", \"Swift\", \"iOS\", \"Android\")" NA "V" "Visionmobile"
"89865" "全球移动开发者：IAP降温，企业应用成待掘金矿" "资讯" "c(\"移动开发\", \"VisionMobile\", \"iOS\", \"Android\", \"HTML5\")" NA "V" "Visionmobile"
"89866" "全球开发者报告：程序媛崛起，企业应用更赚钱！" "资讯" "c(\"移动开发\", \"开发者\", \"调查报告\", \"企业应用\", \"Mary Meeker\")" NA "V" "Visionmobile"
"89867" "开发汽车应用之前，你必须了解的7件事" "资讯" "c(\"汽车应用\", \"iOS\", \"CarPlay\", \"Android\", \"Google\")" NA "V" "Visionmobile"
"89868" "HTML5调查：做的好，收入不比iOS差" "资讯" "c(\"HTML5\", \"iOS\", \"Android\", \"开发平台\", \"VisionMobile\")" NA "V" "Visionmobile"
"89869" "全球开发者：iOS、Android、WP哪个最赚钱？" "资讯" "c(\"移动开发\", \"盈利模式\", \"iOS\", \"Android\", \"VisionMobile\")" NA "V" "Visionmobile"
"89870" "全球6000开发者：iOS、Android、WP最痴情谁？" "资讯" "c(\"iOS\", \"Android\", \"Windows Phone\", \"移动开发\", \"开发者\")" NA "V" "Visionmobile"
"89871" "VisionMobile：2011年度十大事件" "资讯" "c(\"跨平台\", \"互联网\", \"制造\", \"visionmobile\", \"windows phon\")" NA "V" "Visionmobile"
"89872" "VisionMobile解读：为何移动领域平台间如此不同" "资讯" "c(\"网络\", \"浏览器\", \"windows phon\", \"平台\", \"visionmobile\")" NA "V" "Visionmobile"
